### ISSUE TITLE
Error AADSTS50132 after some time

### ISSUE THREAD

**Issue by MariuszKogut** [AzureAD/microsoft-authentication-library-for-js#1050]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
(other browser not tested yet)

## Library Name
- [x] adal.js 1.1.3

## Library version
Library version: 1.1.3

## Current behavior
In my React based SPA I use userAgentApplication.acquireTokenSilent to get an new access token. This works fine, but after some time a get an error:

```
AuthError.js:20 Uncaught (in promise) InteractionRequiredAuthError: AADSTS50132: The session has expired or has been revoked.
Trace ID: 80f54357-9339-4a92-afc8-486a13360e00
Correlation ID: 18444493-7ddb-467d-a8ff-b1c755ddd6b7
```

As I can see here https://docs.microsoft.com/de-de/azure/active-directory/develop/reference-aadsts-error-codes my password has expired or there was a recent password change. But this is not true.

Our access token lifetime is set to 10 minutes. The error occured after ~ 30 minutes.

Callstack:
```
Timestamp: 2019-10-16 08:18:00Z
    at InteractionRequiredAuthError.AuthError [as constructor] (https://localhost:5001/static/js/17.chunk.js:51653:24)
    at InteractionRequiredAuthError.ServerError [as constructor] (https://localhost:5001/static/js/17.chunk.js:52180:24)
    at new InteractionRequiredAuthError (https://localhost:5001/static/js/17.chunk.js:52113:24)
    at UserAgentApplication.saveTokenFromHash (https://localhost:5001/static/js/17.chunk.js:50814:17)
    at UserAgentApplication.processCallBack (https://localhost:5001/static/js/17.chunk.js:50298:23)
    at UserAgentApplication.handleAuthenticationResponse (https://localhost:5001/static/js/17.chunk.js:50405:10)
    at new UserAgentApplication (https://localhost:5001/static/js/17.chunk.js:49437:14)
    at init (https://localhost:5001/static/js/main.chunk.js:10840:18)
    at Module../src/shared/services/authentication/authentication-service.ts (https://localhost:5001/static/js/main.chunk.js:11019:30)
    at __webpack_require__ (https://localhost:5001/static/js/bundle.js:791:30)
    at fn (https://localhost:5001/static/js/bundle.js:151:20)
    at Module../src/shared/components/authentication/authenticated.tsx (https://localhost:5001/static/js/main.chunk.js:412:105)
    at __webpack_require__ (https://localhost:5001/static/js/bundle.js:791:30)
    at fn (https://localhost:5001/static/js/bundle.js:151:20)
    at Module../src/app.tsx (https://localhost:5001/static/js/main.chunk.js:84:105)
    at __webpack_require__ (https://localhost:5001/static/js/bundle.js:791:30)
    at fn (https://localhost:5001/static/js/bundle.js:151:20)
    at Module.<anonymous> (https://localhost:5001/static/js/main.chunk.js:334:62)
    at Module../src/index.tsx (https://localhost:5001/static/js/main.chunk.js:361:30)
    at __webpack_require__ (https://localhost:5001/static/js/bundle.js:791:30)
    at fn (https://localhost:5001/static/js/bundle.js:151:20)
    at Object.0 (https://localhost:5001/static/js/main.chunk.js:11485:18)
    at __webpack_require__ (https://localhost:5001/static/js/bundle.js:791:30)
    at checkDeferredModules (https://localhost:5001/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (https://localhost:5001/static/js/bundle.js:33:19)
    at https://localhost:5001/static/js/main.chunk.js:1:111
```

## Expected behavior
Silent token refresh should not thrown errors after some time.

## Minimal reproduction of the problem with instructions
See above.

</code></pre>

**Comment by jasonnutter** [comment]
@MariuszKogut Generally speaking, if `acquireTokenSilent` throws with an `InteractionRequiredError` error, you should invoke `acquireTokenPopup` or `acquireTokenRedirect` so that the user can interactively resolve the error, as shown [in the README](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core#3-get-an-access-token-to-call-an-api).

Can you try that, and let us know what sort of UI/flow you get from the Microsoft login UI in this scenario?

**Comment by MariuszKogut** [comment]
Thanks @jasonnutter for clarification.  I even found the reason, why the session was limited. A colleague had applied an AdPolicy to our app registration and restricted "MaxAgeSessionSingleFactor":

```
Set-AzureADPolicy -Id xxx -Definition @('{"TokenLifetimePolicy":{"Version":1,"AccessTokenLifetime":"00:10:00","MaxAgeSessionSingleFactor":"02:00:00"}}')
```

😆
