### ISSUE TITLE
NodeInvocationException: Msal is not defined

### ISSUE THREAD

**Issue by HeMinzhang** [AzureAD/microsoft-authentication-library-for-js#126]
I use asp.net core  web api and angular develop web app in VS2017.
But I use Msal.js get a exception. Can you help me?
[WebApplication1.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/1299843/WebApplication1.zip)
  

> An unhandled exception occurred while processing the request.
> 
> NodeInvocationException: Msal is not defined
> ReferenceError: Msal is not defined
> at new MsalService (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:16375:38)
> at createClass (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:21865:26)
> at _createProviderInstance (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:21838:26)
> at createProviderInstance (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:21672:64)
> at createViewNodes (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:23117:49)
> at callViewAction (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:23573:13)
> at execComponentViewsAction (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:23482:13)
> at createViewNodes (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:23154:5)
> at createRootView (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:23022:5)
> at Object.createProdRootView [as createRootView] (c:\users\rootkit\Source\repos\WebApplication1\WebApplication1\ClientApp\dist\vendor.js:23707:12)

**Comment by HeMinzhang** [comment]
I'm fixed,https://github.com/HeMinzhang/active-directory-b2c-asp.net-core-web-api-angular4
