### ISSUE TITLE
@azure/msal-angular": "^1.0.0-beta.2" -  acquireSilentToken and consent error

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#1294]
## Library
@azure/msal-angular": "^1.0.0-beta.2"

## Description
I am acquireTokenSilent after a successful interactive logon.  However I get an error saying the user has not consented and to send an interactive logon request. Having the user sign in again is not solving the issue.  

I have two app registrations in the Microsoft tenant.  One of the front end and one for the protected API.  All permissions have been granted consent by the Microsoft admins., including the scope listed below.

Something is off and I am unsure where the issue lie.

```
    var tokenRequest = {
      scopes: ["api://a0992c0c-812e-470c-90e9-ee1c339517d7/Users.Read"]   //this is my protected API scope
  };

  this.authService.acquireTokenSilent(tokenRequest)
      .then(response => {
          // get access token from response
          // response.accessToken
          console.log(response.accessToken);
      })
      .catch(err => {
          // could also check if err instance of InteractionRequiredAuthError if you can import the class.
          if (err.name === "InteractionRequiredAuthError") {
              return this.authService.acquireTokenSilent(tokenRequest)
                  .then(response => {
                      // get access token from response
                      // response.accessToken
                      console.log(response.accessToken);
                  })
                  .catch(err => {
                      // handle error
                  });
          }
      });
  }
```

"InteractionRequiredAuthError: AADSTS65001: The user or administrator has not consented to use the application with ID '2b303ff7-99fa-41fb-998b-099e8da2be0d' named 'Windows Insider Web (Test)'. Send an interactive authorization request for this user and resource.
Trace ID: 3b147588-5596-43e6-a5ed-7c15d8c20301
Correlation ID: 650f7c79-1b3c-429c-8978-2776565556d0
Timestamp: 2020-02-19 21:21:25Z
    at InteractionRequiredAuthError.AuthError [as constructor] (https://localhost:4200/vendor.js:81002:28)
    at InteractionRequiredAuthError.ServerError [as constructor] (https://localhost:4200/vendor.js:81492:28)
    at new InteractionRequiredAuthError (https://localhost:4200/vendor.js:81429:28)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.saveTokenFromHash (https://localhost:4200/vendor.js:79471:25)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.processCallBack (https://localhost:4200/vendor.js:79026:29)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.handleAuthenticationResponse (https://localhost:4200/vendor.js:79116:14)
    at MsalService.<anonymous> (https://localhost:4200/vendor.js:78856:34)
    at step (https://localhost:4200/vendor.js:100930:23)
    at Object.next (https://localhost:4200/vendor.js:100911:53)
    at fulfilled (https://localhost:4200/vendor.js:100901:58)"

Any thoughts here?

**Comment by jrmcdona** [comment]
Solved this by changing to this code:

```
  this.maslService.acquireTokenSilent(tokenRequest)
      .then(response => {
          // get access token from response
          // response.accessToken
          console.log(response.accessToken);
      })
      .catch(err => {
          // could also check if err instance of InteractionRequiredAuthError if you can import the class.
          if (err.name === "InteractionRequiredAuthError") {

            this.maslService.acquireTokenRedirect(tokenRequest);
          };
      });
  }
```
