### ISSUE TITLE
ClientAuthError: Could not parse cache key

### ISSUE THREAD

**Issue by josh-manton** [AzureAD/microsoft-authentication-library-for-js#1477]
I am working with v2 of msal in  msal-common-known-athroities branch for the b2c support. When I trigger a logout I get the error below. 

@tnorling  - Any ideas why this would happen?

ClientAuthError: Could not parse cache key. Cache key: msal.81480e89-a5ac-4fce-a464-211f724e99ef.request.params
    at ClientAuthError.AuthError [as constructor] (http://localhost:3000/static/js/15.chunk.js:432:24)
    at new ClientAuthError (http://localhost:3000/static/js/15.chunk.js:648:24)
    at Function.ClientAuthError.createCacheParseError (http://localhost:3000/static/js/15.chunk.js:772:12)
    at http://localhost:3000/static/js/15.chunk.js:1587:33
    at Array.forEach (<anonymous>)
    at CacheHelpers.removeAllAccessTokens (http://localhost:3000/static/js/15.chunk.js:1576:33)
    at AuthorizationCodeModule.<anonymous> (http://localhost:3000/static/js/15.chunk.js:4006:31)
    at step (http://localhost:3000/static/js/15.chunk.js:383:17)
    at Object.next (http://localhost:3000/static/js/15.chunk.js:314:14)
    at http://localhost:3000/static/js/15.chunk.js:286:67
    at new Promise (<anonymous>)
    at __awaiter$1 (http://localhost:3000/static/js/15.chunk.js:263:10)
    at AuthorizationCodeModule.logout (http://localhost:3000/static/js/15.chunk.js:3998:12)
    at PublicClientApplication.logout (http://localhost:3000/static/js/15.chunk.js:6542:21)

**Comment by tnorling** [comment]
@josh-manton B2C for msal 2.0 is not yet supported and this branch is still a work in progress. Additionally, the B2C service does not yet support auth code in browsers so I'm curious how you were even able to sign in. Can you provide more details about your application?

**Comment by josh-manton** [comment]
I saw the pull request to bring msal-common-known-athroities into the default branch. I thought i'd give it a try. If you are saying i'm wasting my time, I'll hold off. I was able to go thought the login flow using the redirect. I see that it is maintain state in the local storage.  The callback is triggered. I have not yet validated the login state.  You can close the ticket.

**Comment by tnorling** [comment]
No worries, there's a few pieces that still need to fall into place for B2C to be supported, this PR being one of them. Rest assured, it is coming soon. We appreciate your patience!
