### ISSUE TITLE
InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in. 

### ISSUE THREAD

**Issue by suresh777** [AzureAD/microsoft-authentication-library-for-js#1560]
I am using msal@1.2.2 version.I don't want to enter my password when i login. For that i am sending prompt none in request parameters. I am getting below exception. But if use msal@1.1.3 version without prompt parameter it is directly logging in without password.

```
InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in.
Trace ID: accb8aa7-1de9-48d7-a2b9-d69f76b14500
Correlation ID: f430358f-ac56-4978-804b-b7477246ac7e
Timestamp: 2020-04-29 11:26:23Z
    at InteractionRequiredAuthError.AuthError [as constructor] (http://localhost:3000/static/js/1.chunk.js:146611:24)
    at InteractionRequiredAuthError.ServerError [as constructor] (http://localhost:3000/static/js/1.chunk.js:147166:24)
    at new InteractionRequiredAuthError (http://localhost:3000/static/js/1.chunk.js:147097:24)
    at UserAgentApplication.saveTokenFromHash (http://localhost:3000/static/js/1.chunk.js:144816:17)
    at UserAgentApplication.processCallBack (http://localhost:3000/static/js/1.chunk.js:144319:23)
    at UserAgentApplication.handleRedirectCallback (http://localhost:3000/static/js/1.chunk.js:143539:12)
    at Login.componentDidMount (http://localhost:3000/static/js/main.chunk.js:1295:71)
    at commitLifeCycles (http://localhost:3000/static/js/1.chunk.js:182333:26)
    at commitLayoutEffects (http://localhost:3000/static/js/1.chunk.js:185303:11)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:162810:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:162859:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:162912:35)
    at commitRootImpl (http://localhost:3000/static/js/1.chunk.js:185045:13)
    at unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:227330:16)
    at runWithPriority$1 (http://localhost:3000/static/js/1.chunk.js:173714:14)
    at commitRoot (http://localhost:3000/static/js/1.chunk.js:184887:7)
    at finishSyncRender (http://localhost:3000/static/js/1.chunk.js:184304:7)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/1.chunk.js:184290:11)
    at http://localhost:3000/static/js/1.chunk.js:173768:28
    at unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:227330:16)
    at runWithPriority$1 (http://localhost:3000/static/js/1.chunk.js:173714:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/1.chunk.js:173763:11)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/1.chunk.js:173751:7)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/1.chunk.js:183697:13)
    at Object.enqueueSetState (http://localhost:3000/static/js/1.chunk.js:175313:9)
    at PersistGate.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/1.chunk.js:222048:20)
    at http://localhost:3000/static/js/1.chunk.js:224613:17
    at Object.dispatch (http://localhost:3000/static/js/1.chunk.js:225785:7)
    at Object.rehydrate (http://localhost:3000/static/js/1.chunk.js:225078:13)
    at _rehydrate (http://localhost:3000/static/js/1.chunk.js:224835:18)
    at http://localhost:3000/static/js/1.chunk.js:224864:11

export const REQUEST = {
  scopes: [“xxxxxxxxxx”],
  prompt: ‘none’
};
msalApp.loginRedirect(REQUEST);
```

**Comment by tnorling** [comment]
@suresh777 If you update to the latest version of msal, 1.3.0 we added an ssoSilent API which can be used for silent login requests. However, for this to work you need to already have an active session with AAD. As a general rule of thumb, when you get the `InteractionRequiredAuthError` you will need to call a redirect or popup method to do the required interaction (login, give consent, etc.) before you can use the silent methods.
