### ISSUE TITLE
Failed to build.

### ISSUE THREAD

**Issue by hifall** [AzureAD/microsoft-authentication-library-for-js#1589]
## Library
- [ ] `msal@1.3.0` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).

## Description
Tried to build this (1.3.0 release) under Ubuntu 18.04LTS with node (10.20.1) and npm (6.14.4), and it gave me:

```
> microsoft-authentication-libraries-for-js@ build /root/microsoft-authentication-library-for-js-1.3.0-release
> lerna run build "--scope" "@azure/msal-browser"

lerna notice cli v3.20.2
lerna info versioning independent
lerna notice filter including "@azure/msal-browser"
lerna info filter [ '@azure/msal-browser' ]
lerna info Executing command in 1 package: "npm run build"
lerna ERR! npm run build exited 1 in '@azure/msal-browser'
lerna ERR! npm run build stdout:

> @azure/msal-browser@2.0.0-beta.0 build /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser
> npm run clean && npm run lint && npm run build:modules


> @azure/msal-browser@2.0.0-beta.0 clean /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser
> shx rm -rf dist lib


> @azure/msal-browser@2.0.0-beta.0 lint /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser
> eslint src --ext .ts


> @azure/msal-browser@2.0.0-beta.0 build:modules /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser
> rollup -c


lerna ERR! npm run build stderr:
[!] Error: Cannot find module 'rollup-plugin-typescript2'
Error: Cannot find module 'rollup-plugin-typescript2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser/rollup.config.js:8:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.require.extensions.(anonymous function) [as .js] (/root/microsoft-authentication-library-for-js-1.3.0-release/node_modules/rollup/dist/shared/loadConfigFile.js:516:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @azure/msal-browser@2.0.0-beta.0 build:modules: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @azure/msal-browser@2.0.0-beta.0 build:modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-04T06_07_41_444Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @azure/msal-browser@2.0.0-beta.0 build: `npm run clean && npm run lint && npm run build:modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @azure/msal-browser@2.0.0-beta.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-04T06_07_41_468Z-debug.log

lerna ERR! npm run build exited 1 in '@azure/msal-browser'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! microsoft-authentication-libraries-for-js@ build: `lerna run build "--scope" "@azure/msal-browser"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microsoft-authentication-libraries-for-js@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-04T06_07_41_508Z-debug.log
```

## Security
No

## Regression
Not sure

**Comment by hifall** [comment]
The debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @azure/msal-browser@2.0.0-beta.0~prebuild: @azure/msal-browser@2.0.0-beta.0
6 info lifecycle @azure/msal-browser@2.0.0-beta.0~build: @azure/msal-browser@2.0.0-beta.0
7 verbose lifecycle @azure/msal-browser@2.0.0-beta.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle @azure/msal-browser@2.0.0-beta.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser/node_modules/.bin:/root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser/node_modules/.bin:/root/microsoft-authentication-library-for-js-1.3.0-release/lib/node_modules/.bin:/root/microsoft-authentication-library-for-js-1.3.0-release/node_modules/.bin:/root/node_modules/.bin:/node_modules/.bin:/usr/bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/microsoft-authentication-library-for-js-1.3.0-release/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @azure/msal-browser@2.0.0-beta.0~build: CWD: /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser
10 silly lifecycle @azure/msal-browser@2.0.0-beta.0~build: Args: [ '-c',
10 silly lifecycle   'npm run clean && npm run lint && npm run build:modules' ]
11 silly lifecycle @azure/msal-browser@2.0.0-beta.0~build: Returned: code: 1  signal: null
12 info lifecycle @azure/msal-browser@2.0.0-beta.0~build: Failed to exec build script
13 verbose stack Error: @azure/msal-browser@2.0.0-beta.0 build: `npm run clean && npm run lint && npm run build:modules`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @azure/msal-browser@2.0.0-beta.0
15 verbose cwd /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-browser
16 verbose Linux 4.15.0-88-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.20.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @azure/msal-browser@2.0.0-beta.0 build: `npm run clean && npm run lint && npm run build:modules`
22 error Exit status 1
23 error Failed at the @azure/msal-browser@2.0.0-beta.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pkanher617** [comment]
@hifall It looks like npm isn't finding the `rollup-plugin-typescript2` package. Try running `npm install` at the root of the repo before running the build command. It should also run `lerna bootstrap` on post-install.

**Comment by hifall** [comment]
@pkanher617, I did run `npm install`, but it did not work.

Today I just tried this again, and after running into the same issue, I manually installed:

```
npm i shx
npm i eslint
npm i typescript
npm i @typescript-eslint/eslint-plugin
npm i @typescript-eslint/parser
npm i @typescript-eslint/eslint-plugin-tslint
npm i tslint
npm i rollup
npm i rollup-plugin-typescript2
npm i rollup-plugin-uglify
npm i @rollup/plugin-json
apt install -y webpack
npm i yargs
```

still got this:

```
root@localhost:~/microsoft-authentication-library-for-js-1.3.0-release# npm run build

> microsoft-authentication-libraries-for-js@ build /root/microsoft-authentication-library-for-js-1.3.0-release
> lerna run build

lerna notice cli v3.20.2
lerna info versioning independent
lerna notice filter including ["msal","@azure/msal-common","@azure/msal-browser","@azure/msal-angular","vanilla-js-test-app","vanilla-js-test-app-2.0"]
lerna info filter [ 'msal',
lerna info filter   '@azure/msal-common',
lerna info filter   '@azure/msal-browser',
lerna info filter   '@azure/msal-angular',
lerna info filter   'vanilla-js-test-app',
lerna info filter   'vanilla-js-test-app-2.0' ]
lerna info Executing command in 4 packages: "npm run build"
lerna info run Ran npm script 'build' in '@azure/msal-common' in 30.1s:

> @azure/msal-common@1.0.0-beta.0 build /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-common
> npm run clean && npm run lint && npm run build:modules


> @azure/msal-common@1.0.0-beta.0 clean /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-common
> shx rm -rf dist lib


> @azure/msal-common@1.0.0-beta.0 lint /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-common
> eslint src --ext .ts


> @azure/msal-common@1.0.0-beta.0 build:modules /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-common
> rollup -c

lerna ERR! npm run build exited 1 in 'msal'
lerna ERR! npm run build stdout:

> msal@1.3.0 build /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-core
> npm run clean && npm run build:modules


> msal@1.3.0 clean /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-core
> shx rm -rf dist lib-commonjs lib-es6


> msal@1.3.0 build:modules /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-core
> tsc && tsc -m es6 --outDir lib-es6 && npm run build:webpack


> msal@1.3.0 build:webpack /root/microsoft-authentication-library-for-js-1.3.0-release/lib/msal-core
> webpack


lerna ERR! npm run build stderr:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/nodejs/webpack/bin/webpack.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msal@1.3.0 build:webpack: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msal@1.3.0 build:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-05T10_42_00_338Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msal@1.3.0 build:modules: `tsc && tsc -m es6 --outDir lib-es6 && npm run build:webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msal@1.3.0 build:modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-05T10_42_00_360Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msal@1.3.0 build: `npm run clean && npm run build:modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msal@1.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-05T10_42_00_402Z-debug.log

lerna ERR! npm run build exited 1 in 'msal'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! microsoft-authentication-libraries-for-js@ build: `lerna run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microsoft-authentication-libraries-for-js@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-05T10_42_00_461Z-debug.log
```

**Comment by pkanher617** [comment]
What is the error that you are getting when you run `npm install`? I am able to clone the repo and run this on a new machine just fine. 

Alternatively, you can run the `npm install` command in each repo individually, then run `lerna bootstrap` at the root to ensure the local packages are being used.

**Comment by tnorling** [comment]
Closing due to inactivity. Let us know if you are still having problems
