### ISSUE TITLE
URL navigated to is https://login.microsoftonline.com/dummyguid/oauth2/v2.0/authorize?response_type=token..., Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by BigThinker** [AzureAD/microsoft-authentication-library-for-js#1610]
## Library
- [x] `msal@^1.3.0`
- [x] `@azure/msal-angular@^1.0.0-beta.5`

## Framework
Angular v9.1.0

## Description
URL navigated to is https://login.microsoftonline.com/dummyguid/oauth2/v2.0/authorize?response_type=token&scope=%20openid%20profile&client_id=dummy&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=dummy&nonce=dummy&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=Aldo%40domain.com&client-request-id=dummy&prompt=none&response_mode=fragment, Token renewal operation failed due to timeout
at ClientAuthError.AuthError [as constructor] (http://localhost:4200/vendor.js:193413:28)
    at new ClientAuthError (http://localhost:4200/vendor.js:193551:28)
    at Function.push../node_modules/msal/lib-es6/error/ClientAuthError.js.ClientAuthError.createTokenRenewalTimeoutError (http://localhost:4200/vendor.js:193578:16)
    at http://localhost:4200/vendor.js:195868:99
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3505:35)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:108275:33)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3504:40)
    at Zone.runTask (http://localhost:4200/polyfills.js:3273:51)
    at invokeTask (http://localhost:4200/polyfills.js:3586:38)
    at ZoneTask.invoke (http://localhost:4200/polyfills.js:3575:52)

## Regression
This is a bug that happens (as far as I've noticed) randomly when accessing a protected route with MsalGuard.

## Configuration
import { Configuration } from 'msal';
import { MsalAngularConfiguration } from '@azure/msal-angular';

//Force to true to not use popup (not preferred since it introduced more bugs).
export const isIE = true;

export const apiConfig: {scopes: string[], webApi: string, ipEndpoint:string} = {
    scopes: [''],
    webApi: 'https://localhost:11111/api',
    ipEndpoint: 'http://api.ipify.org/?format=json'
};

export const msalConfig: Configuration = {
    auth: {
        clientId: 'app-id',
        authority: 'https://login.microsoftonline.com//directory-id',
        validateAuthority: false,
        redirectUri: "http://localhost:4200/",
        postLogoutRedirectUri: "http://localhost:4200/",
        navigateToLoginRequestUrl: true,
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: isIE, // Set this to "true" to save cache in cookies to address trusted zones limitations in IE
    },
};

export const loginRequest: {scopes: string[]} = {
    scopes: ['user.read', 'openid', 'profile'],
};

export const tokenRequest: {scopes: string[]} = {
    scopes: apiConfig.scopes
};

export const protectedResourceMap: [string, string[]][] = [
    [apiConfig.webApi, apiConfig.scopes],
    ['https://graph.microsoft.com/v1.0/me', ['user.read']]
];

export const msalAngularConfig: MsalAngularConfiguration = {
    popUp: !isIE,
    consentScopes: [
        ...loginRequest.scopes,
        ...tokenRequest.scopes,
    ],
    unprotectedResources: [],
    protectedResourceMap,
    extraQueryParameters: {}  
};

## Expected behavior
Error-free route navigation.

## Browsers
I'm using Chrome.

**Comment by BigThinker** [comment]
I get these 2 error messages before getting the error message detailed above.

**Unsafe JavaScript attempt to initiate navigation for frame with origin** 'http://localhost:4200' from frame with URL 'https://login.microsoftonline.com/dummyguid/oauth2/v2.0/authorize?response_type=token&scope=%20openid%20profile&client_id=dummy&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=dummy&nonce=dummy&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=Aldo%40domain.com&client-request-id=dummy&prompt=none&response_mode=fragment'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

**Uncaught DOMException: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame** to 'https://login.microsoftonline.com/dummyguid/oauth2/v2.0/authorize?response_type=token&scope=%20openid%20profile&client_id=dummy&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=dummy&nonce=dummy&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=Aldo%40domain.com&client-request-id=dummy&prompt=none&response_mode=fragment&iframe-request-id=dummyid'.
    at https://login.microsoftonline.com/dummyguid/oauth2/v2.0/authorize?response_type=token&scope=%20openid%20profile&client_id=dummy&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=dummy&nonce=dummy&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=Aldo%40domain.com&client-request-id=dummy&prompt=none&response_mode=fragment:82:326
    at https://login.microsoftonline.com/dummyguid/oauth2/v2.0/authorize?response_type=token&scope=%20openid%20profile&client_id=dummy&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=dummy&nonce=dummy&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=Aldo%40domain.com&client-request-id=dummy&prompt=none&response_mode=fragment:82:331

**Comment by pkanher617** [comment]
> **Unsafe JavaScript attempt to initiate navigation for frame with origin** 'http://localhost:4200' from frame with URL 'https://login.microsoftonline.com/dummyguid/oauth2/v2.0/authorize?response_type=token&scope=%20openid%20profile&client_id=dummy&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=dummy&nonce=dummy&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=Aldo%40domain.com&client-request-id=dummy&prompt=none&response_mode=fragment'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.
> 

@BigThinker Could you try opening the URL that you received in this error in a top frame tab? This error occurs when STS is attempting to show an error in the top frame.

**Comment by pkanher617** [comment]
@BigThinker Any updates on the error?

**Comment by pkanher617** [comment]
Closing since there is no activity.
