### ISSUE TITLE
Regarding azure b2c access Token

### ISSUE THREAD

**Issue by dprem06** [AzureAD/microsoft-authentication-library-for-js#1803]
Redirect Approach:

Failed calling acquire token silent , From this approach I am only able to take id token after that access token calls failed...

**myMSALObj.acquireTokenSilent() this method goes always catch block.** but same scope in popup aproach working fine.

Error:
**AADB2C90077**:  User does not have an existing session and request prompt parameter has a value of 'None'.

InteractionRequiredAuthError: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: 3eb9b9f0-b956-4f29-92d1-ca70d6d5f2c1
Timestamp: 2020-06-19 06:58:24Z

    at InteractionRequiredAuthError.AuthError [as constructor] (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:1523:28)
    at InteractionRequiredAuthError.ServerError [as constructor] (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:2125:28)
    at new InteractionRequiredAuthError (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:5015:28)
    at UserAgentApplication.saveTokenFromHash (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:3436:25)
    at UserAgentApplication.processCallBack (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:2992:29)
    at UserAgentApplication.handleAuthenticationResponse (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:3044:14)
    at UserAgentApplication.<anonymous> (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:2814:34)
    at step (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:254:27)
    at Object.next (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:203:53)
    at fulfilled (https://alcdn.msauth.net/lib/1.3.1/js/msal.js:183:28)

**Comment by jmckennon** [comment]
This is intended. When you call `acquireTokenSilent`, it will attempt to silently access their credentials on AAD. If the user has no active AAD session, this will fail. The `prompt` parameter allows for options on calls. By default it is set to `none` and this value will ensure that the user does not see any interactive prompt. You can read more about prompts on msal js on [the microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior).

Our recommended usage for `acquireTokenSilent` would be to initially try to acquire a token silently, and if you receive errors, to fall back to `acquireTokenRedirect` or `acquireTokenPopup`. This can be seen in our sample: 
```typescript
function getTokenPopup(request) {
    return myMSALObj.acquireTokenSilent(request).catch(error => {
        console.log("silent token acquisition fails. acquiring token using popup");
        // fallback to interaction when silent call fails
        return myMSALObj.acquireTokenPopup(request).then(tokenResponse => {
            console.log(tokenResponse);
            return tokenResponse;
        }).catch(error => {
            console.log(error);
        });
    });
}
```

**Comment by jmckennon** [comment]
Closing this as we're assuming the problem is solved due to inactivity. Please open a new issue if you have further questions. Thanks!
