### ISSUE TITLE
integration with Deno? 

### ISSUE THREAD

**Issue by d4rk0de** [AzureAD/microsoft-authentication-library-for-js#2273]

**Comment by jasonnutter** [comment]
At this time, we are prioritizing MSAL Node for compatibility with the latest versions of Node. We may consider supporting Deno incrementally after GA. cc: @sameerag

**Comment by josh-hemphill** [comment]
In the meantime I've created a polyfilled fork and bundled into a deno package. Once official support comes, I'll be happy to have it removed/archived to prevent confusion. Should also be a good reference when going to create the official package.
https://deno.land/x/azure_msal_deno@v1.1.0
Just needed something in the meantime to get started on a couple of small tools.

**Comment by sameerag** [comment]
@EmLauber can we have this tracked internally in our backlog to evaluate if we can support it?

**Comment by josh-hemphill** [comment]
Since I started on that fork, Deno has released a Node.js compatibility layer that can be used to create a wrapper and a bundle that ultimately calls the Deno api instead of the Node.js. So that would probably make it possible to just add a single file and a CI step to add support for deno.

**Comment by jasonnutter** [comment]
> Since I started on that fork, Deno has released a Node.js compatibility layer that can be used to create a wrapper and a bundle that ultimately calls the Deno api instead of the Node.js. So that would probably make it possible to just add a single file and a CI step to add support for deno.

@josh-hemphill Are you referring to this? https://deno.land/manual/node/compatibility_mode#node-compatibility-mode

**Comment by josh-hemphill** [comment]
Yep, I've had a lot of luck with it, the only significant things I've found that are still missing are the polyfills for node's raw sockets and DNS interfaces.

**Comment by jasonnutter** [comment]
@josh-hemphill Thanks. Not sure when we'll be able to prioritize this, but you are welcome to open a PR demonstrating what support for Deno would look like in MSAL Node.

**Comment by josh-hemphill** [comment]
Got a [comment on my polyfilled version](https://github.com/josh-hemphill/azure-msal-deno/issues/3) that Deno's new much broader node compatibility breaks when trying to use msal-node.
Looks like `msal-node` is GA now, so I'm curious if there's any movement on an official version of msal for deno, or if deno running in compat mode can be added to integrations tests or something for msal-node so that deno users can rely on it working?

**Comment by Symbitic** [comment]
> Got a [comment on my polyfilled version](https://github.com/josh-hemphill/azure-msal-deno/issues/3) that Deno's new much broader node compatibility breaks when trying to use msal-node. Looks like `msal-node` is GA now, so I'm curious if there's any movement on an official version of msal for deno, or if deno running in compat mode can be added to integrations tests or something for msal-node so that deno users can rely on it working?

More specifically, it throws this exception when using `acquireTokenInteractive`:
```
error: Uncaught NodeAuthError: invalid_loopback_server_address_type: Loopback server address is not type string. This is unexpected.
    at new AuthError (file:///C:/Users/me/AppData/Local/deno/npm/registry.npmjs.org/@azure/msal-common/9.1.1/dist/index.cjs.js:517:24)
    at new NodeAuthError (file:///C:/Users/me/AppData/Local/deno/npm/registry.npmjs.org/@azure/msal-node/1.14.6/dist/msal-node.cjs.development.js:1625:5)
    at Function.createInvalidLoopbackAddressTypeError (file:///C:/Users/me/AppData/Local/deno/npm/registry.npmjs.org/@azure/msal-node/1.14.6/dist/msal-node.cjs.development.js:1632:12)
    at LoopbackClient.getRedirectUri (file:///C:/Users/me/AppData/Local/deno/npm/registry.npmjs.org/@azure/msal-node/1.14.6/dist/msal-node.cjs.development.js:2057:27)
    at PublicClientApplication.acquireTokenInteractive (file:///C:/Users/me/AppData/Local/deno/npm/registry.npmjs.org/@azure/msal-node/1.14.6/dist/msal-node.cjs.development.js:2144:40)
    at async file:///C:/Users/me/Downloads/deno-azure.ts:85:19
```

**Comment by EmLauber** [comment]
We have it tracked in our backlog, but at this time we don't have official Deno support prioritized in the coming quarters. We do welcome community PRs though if you'd like to explore adding support directly: [Contributing Guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md ). FYI @jmprieur @bgavrilMS
