### ISSUE TITLE
Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by vcs38** [AzureAD/microsoft-authentication-library-for-js#2295]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 8

## Description
Cannot get access token when app is hosted on azure and everything works in my company's internal server.
I've tested [this](https://gist.github.com/tushargupta51/5fa6d000357120adbc8fd1d5c68853c4#gistcomment-2596636) which seems to genrally work but I'm facing work frames security issues (_Blocked a frame with origin "https://MY_URL" from accessing a cross-origin frame_, or also _Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes_.).

I've also tried to test if we are in an iframe

Here is the code which generates errors:
```
private async getAccessToken(): Promise < string > {
  return new Promise<string>((resolve: Function, reject: Function): void => {
    const isIframe: boolean = window !== window.parent && !window.opener;
    if (!isIframe) { // added as a workaround
      this.msalService.acquireTokenSilent({
        scopes: this.confService.getMicrosoftScopes(),
        redirectUri: `${window.origin}/auth.html`, // added as a workaround
      }).then((authResponse: AuthResponse) => {
        resolve(authResponse.accessToken);
      })
        .catch((error: { name: string }) => {
          if (error.name === "InteractionRequiredAuthError") {
            this.msalService.acquireTokenPopup({
              scopes: this.confService.getMicrosoftScopes(),
            }).then((authResponse: AuthResponse) => {
              resolve(authResponse.accessToken);
            }).catch((acquireTokenPopupError) => {
              console.log(acquireTokenPopupError);
            })
          } else {
            reject('Could not get access token')
          }
        });
    } else {
      setTimeout(() => {
        resolve(null);
      }, 10000)
    }
  });
}

Thank you for your help
```

## Error Message
**Token renewal operation failed due to timeout**

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version: 1.0.0

## MSAL Configuration
    ` {
          provide: MSAL_CONFIG,
         useFactory: (): Configuration => ({
           auth: {
            clientId: 'CLIENT_ID',
             authority: 'https://login.microsoftonline.com/common',
            redirectUri: window.location.origin,
          },
          cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: true, //added to test but worked on CI with false
          },
          system: {
            loadFrameTimeout: 20000 //added to test but worked on CI without
          }
        })
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
        useFactory: (): MsalAngularConfiguration => ({
          popUp: true,
          consentScopes: [
            "user.read",
            "calendars.read",
            "calendars.readwrite",
            "calendars.readwrite.shared",
            "group.read.all",
            "openid",
            "profile"
          ],
          extraQueryParameters: {
            prompt: 'select_account' //added to test but worked on CI without
          }
        })
    },`

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
> but I'm facing work frames security issues (Blocked a frame with origin "https://MY_URL" from accessing a cross-origin frame, or also Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.).

This is potentially the cause of your timeouts. Can you share more details about the errors messages you're seeing?

**Comment by vcs38** [comment]
I've captures the logs for each solution I've tested.
With "normal" scenario the same app works perfectly when deployed on our internal servers.
What I've noticed is that when it works, the app in the hidden frame has not time to load and all the requests to te script are canceled because I guess the iframe was closed. Here is the capture of this (it is written "finished" but it was written "canceled".
![tempsnip](https://user-images.githubusercontent.com/49646013/94557194-86ff6d00-025e-11eb-96f4-89c25647df0b.png)
As soon as this iframe is closed we can see the requests to graph working (me, calendars, events).
On Azure the same app has a different behaviour. The iframe seems to be never closed, all the app is loaded and the requests to graph are never done. 

![tempsnip2](https://user-images.githubusercontent.com/49646013/94557606-14db5800-025f-11eb-9cb3-82bf291d9fb9.png)
The only message I have is this one
````
acquireTokenSilent catch block main.aae7314fd886d26e42fa.js:1 
ClientAuthError: Token renewal operation failed due to timeout.
    at t [as constructor] (https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1728317)
    at new t (https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1728939)
    at Function.t.createTokenRenewalTimeoutError (https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1729895)
    at https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1752560
    at e.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:18867)
    at Object.onInvokeTask (https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1627587)
    at e.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:18788)
    at t.runTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:13946)
    at t.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:19999)
    at invoke (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:19890)
```

**Comment by jmckennon** [comment]
When you receive the "Blocked a frame..." error message, can you try opening the `login.microsoftonline.com` URL in its own tab?

**Comment by vcs38** [comment]
When I open `login.microsoft.com` I can log in and I'm redirected to office365 dashboard.
In my app, I have this message
```
main.aae7314fd886d26e42fa.js:1 DOMException: Blocked a frame with origin "https://kubectl-ppd03.powimo.com" from accessing a cross-origin frame.
    at started.test.window.addEventListener.l._listener (https://fastly.trychameleon.com/assets/chmln/adeaf8112/chmln.js:1:240710)
    at e.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:18867)
    at Object.onInvokeTask (https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1627587)
    at e.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:18788)
    at t.runTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:13946)
    at t.invokeTask [as invoke] (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:19999)
    at p (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:33011)
    at h (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:33317)
```

**Comment by jmckennon** [comment]
Can you generate a fiddler trace of the timeout error you were seeing previously and send it to the email on my profile?

**Comment by vcs38** [comment]
That's done.
Thank you

**Comment by vcs38** [comment]
@jmckennon have you received my trace ?

**Comment by jmckennon** [comment]
@vcs38 The trace that you sent shows an access token being acquired successfully, was that the correct trace that you meant to show us? I was expecting one with errors.

Additionally, `loadFrameTimeout` just increases the time before getting a timeout error. Sometimes playing with the value can help show if the error is truly a timeout and it just needed more time to complete, but this is usually not the case.

**Comment by vcs38** [comment]
I don't have any network issues you are right. 
I acquire the token via the network but it's in the application that I have this error.
For reminding, the same app is deployed on two different environments: one internally and another one on Azure.
What we can see is that the app deployed internally works perfectly maybe because some scripts in the iframe are not loaded (maybe the network is not fast enough ?)

**Comment by vcs38** [comment]
I've seen exactly why I'm having a timeout in msal.js file by debugging.
This fonction creates the timeout:

```javascript
WindowUtils.monitorWindowForHash = function (contentWindow, timeout, urlNavigate, logger, isSilentCall) {
    return new Promise(function (resolve, reject) {
      var maxTicks = timeout / WindowUtils.POLLING_INTERVAL_MS;
      var ticks = 0;
      logger.verbose("monitorWindowForHash polling started");
      var intervalId = setInterval(function () {
        if (contentWindow.closed) {
          logger.error("monitorWindowForHash window closed");
          clearInterval(intervalId);
          reject(ClientAuthError_1.ClientAuthError.createUserCancelledError());
          return;
        }
        var href;
        try {
          /*
           * Will throw if cross origin,
           * which should be caught and ignored
           * since we need the interval to keep running while on STS UI.
           */
          href = contentWindow.location.href;
        }
        catch (e) { }
        if (isSilentCall) {
          /*
           * Always run clock for silent calls
           * as silent operations should be short,
           * and to ensure they always at worst timeout.
           */
          ticks++;
        }
        else {
          // Don't process blank pages or cross domain
          if (!href || href === "about:blank") {
            return;
          }
          /*
           * Only run clock when we are on same domain for popups
           * as popup operations can take a long time.
           */
          ticks++;
        }
        if (href && UrlUtils_1.UrlUtils.urlContainsHash(href)) {
          logger.verbose("monitorWindowForHash found url in hash");
          clearInterval(intervalId);
          resolve(contentWindow.location.hash);
        }
        else if (ticks > maxTicks) {
          logger.error("monitorWindowForHash unable to find hash in url, timing out");
          logger.errorPii("monitorWindowForHash polling timed out for url: " + urlNavigate);
          clearInterval(intervalId);
          reject(ClientAuthError_1.ClientAuthError.createTokenRenewalTimeoutError());
        }
      }, WindowUtils.POLLING_INTERVAL_MS);
    });
  };
```

On Azure I'm reaching this block of code:

```javascript
     else if (ticks > maxTicks) {
          logger.error("monitorWindowForHash unable to find hash in url, timing out");
          logger.errorPii("monitorWindowForHash polling timed out for url: " + urlNavigate);
          clearInterval(intervalId);
          reject(ClientAuthError_1.ClientAuthError.createTokenRenewalTimeoutError());
        }
```

I reach this blocl because the variable href is in error.
I've set a breakpoint at th specific line and href is undefined.

href is set at this specific line:

```javascript
try {
          /*
           * Will throw if cross origin,
           * which should be caught and ignored
           * since we need the interval to keep running while on STS UI.
           */
          href = contentWindow.location.href;
        }
        catch (e) { }
```

What i can see with my breakpoint is that the content of `contentWindow.location.href` is in error as shown below:
![Capture1](https://user-images.githubusercontent.com/49646013/95347031-c102eb80-08bc-11eb-97fe-f12dc88d5d87.PNG)

The full mesage is 
`Exception: DOMException: Blocked a frame with origin "https://kubectl-ppd03.powimo.com" from accessing a cross-origin frame. at https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1752205<error: SecurityError: Blocked a frame with origin "https://kubectl-ppd03.powimo.com" from accessing a cross-origin frame.<error> at e.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:18867) at Object.onInvokeTask (https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1627587) at e.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:18788) at t.runTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:13946) at t.invokeTask (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:19999) at invoke (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:19890) at n.args.<computed> (https://kubectl-ppd03.powimo.com/polyfills.2e9dda1f02a2d7a33f1f.js:1:50848)`

`https://kubectl-ppd03.powimo.com/vendor.308a54bd7208ddbf6258.js:1:1752205` refers to the line `href = contentWindow.location.href;`

Hope this will really help because my company and our clients are blocked

Thanks

**Comment by vcs38** [comment]
I really need some support. Can someone tell me what else can I do ?

**Comment by vcs38** [comment]
Sorry to pollute but I still need some help

**Comment by jmckennon** [comment]
Sorry for the delay here @vcs38. Can you try setting `initialNavigation: 'disabled'` when inside an iframe ([example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9fb15d5cc5ed4203f21ac067ea847d4592fd895c/samples/msal-angular-v2-samples/angular10-browser-sample/src/app/app-routing.module.ts#L26-L32)), while also using the largely increased `loadFrameTimeout` value?

**Comment by jasonnutter** [comment]
MSAL Angular v2 alpha is now available: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

We do not expect applications to experience the same timeout errors from v1, so please try it out and let us know if you still experience these issues.

**Comment by jasonnutter** [comment]
Closing due to inactivity.
