### ISSUE TITLE
msal-browser v 2.3.1 & v2.1.0: logout() works but logout(logoutRequest) throws error

### ISSUE THREAD

**Issue by willzhan** [AzureAD/microsoft-authentication-library-for-js#2452]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-browser@2.3.1`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
Try to use logout API: logout() works well, while logout(logoutRequest) throws error. I have made sure that logoutRequest.account = the login account.

### msal-browser v 2.3.1: 

Uncaught (in promise) ClientAuthError: no_account_found: No account found in cache for given key.
    at X.u [as constructor] (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:4330)
    at new X (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:10991)
    at Function.X.createNoAccountFoundError (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:10352)
    at Un.St.removeAccount (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:40894)
    at Rr.getLogoutUri (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:66489)
    at io.<anonymous> (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:129952)
    at https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:1919
    at Object.next (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:2024)
    at r (https://alcdn.msauth.net/browser/2.3.1/js/msal-browser.min.js:2:795)

### msal-browser v 2.1.0 error: 

Uncaught (in promise) ClientAuthError: no_account_found: No account found in cache for given key. at ClientAuthError.AuthError [as constructor] (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:201:28) at new ClientAuthError (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:490:32) at Function.ClientAuthError.createNoAccountFoundError (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:675:20) at BrowserStorage.CacheManager.removeAccount (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:2399:39) at AuthorizationCodeClient.getLogoutUri (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:3756:35) at PublicClientApplication. (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:7282:52) at step (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:80:27) at Object.next (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:61:57) at fulfilled (https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js:51:62) AuthError @ index.es.js:109 ClientAuthError @ index.es.js:398 ClientAuthError.createNoAccountFoundError @ index.es.js:583 CacheManager.removeAccount @ index.es.js:2307 AuthorizationCodeClient.getLogoutUri @ index.es.js:3664 (anonymous) @ PublicClientApplication.ts:508 step @ msal-browser.js:80 (anonymous) @ msal-browser.js:61 fulfilled @ msal-browser.js:51 Promise.then (async) step @ msal-browser.js:53 (anonymous) @ msal-browser.js:54 __awaiter @ msal-browser.js:50 PublicClientApplication.logout @ PublicClientApplication.ts:504 logout @ oauth20.js:157 login_out @ oauth20.js:171 (anonymous) @ VM37:1

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@willzhan Can you please include your configuration as well as your code usage (e.g. how you are creating `logoutRequest`)?

**Comment by willzhan** [comment]
const logoutRequest = {
account: cachedAccount
};
And thru debugging, I can see the cachedAccount has all the valid attributes.

**Comment by pritipatona** [comment]
facing same issue

**Comment by jasonnutter** [comment]
This issue should be fixed in `@azure/msal-browser@2.8.0`. Please try and let us know if this is still an issue.

**Comment by willzhan** [comment]
Hi Jason,

Just tested in msal/browser v2.8.0. There is still an issue in logging out the specified account using the above syntax. The error is copied below:

Uncaught (in promise) ClientAuthError: no_account_found: No account found in cache for given key.
    at Fe.re [as constructor] (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:9221)
    at new Fe (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:16986)
    at Function.Fe.createNoAccountFoundError (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:16148)
    at oo.Mt.removeAccount (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:44162)
    at qr.getLogoutUri (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:74405)
    at No.<anonymous> (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:149819)
    at https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:1919
    at Object.next (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:2024)
    at r (https://alcdn.msauth.net/browser/2.8.0/js/msal-browser.min.js:2:795)

**Comment by willzhan** [comment]
the logout() without input works fine.
