### ISSUE TITLE
Token renewal operation failed due to timeout with react and electron

### ISSUE THREAD

**Issue by Ladvace** [AzureAD/microsoft-authentication-library-for-js#2695]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.14.4`

## Description
I'm trying to use msla with react on electron, I managed to open the login popup, but after some seconds it close itself and I get the following error

## Error Message
```
AuthError.js:22 Uncaught (in promise) ClientAuthError: Token renewal operation failed due to timeout.
    at ClientAuthError.AuthError [as constructor] (http://localhost:1212/dist/renderer.dev.js:61830:28)
    at new ClientAuthError (http://localhost:1212/dist/renderer.dev.js:61963:28)
    at Function.module.exports../node_modules/msal/lib-es6/error/ClientAuthError.js.ClientAuthError.createTokenRenewalTimeoutError (http://localhost:1212/dist/renderer.dev.js:61986:16)
    at http://localhost:1212/dist/renderer.dev.js:64545:99
```

## MSAL Configuration
```
import React, { useState } from 'react';
import { UserAgentApplication } from 'msal';

const graph = require('@microsoft/microsoft-graph-client');

const userAgetnApp = new UserAgentApplication({
  auth: {
    clientId: ID',
    redirectUri: 'ELECTRONCUSTOMPROTOCOL://auth',
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
});

userAgetnApp.handleRedirectCallback((error, response) => {
  console.error(error);
  console.log('response', response);
});

function getAuthenticatedClient(accessToken) {
  // Initialize Graph client
  const client = graph.Client.init({
    // Use the provided access token to authenticate
    // requests
    authProvider: (done) => {
      done(null, accessToken);
    },
  });

  return client;
}

async function getUserDetails(accessToken) {
  const client = getAuthenticatedClient(accessToken);

  const user = await client
    .api('/me')
    .select('displayName,mail,mailboxSettings,userPrincipalName')
    .get();

  return user;
}

export default function HomePage() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [email, setEmail] = useState(null);
  const [username, setUsername] = useState(null);

  const getUserProfile = async () => {
    try {
      const accessToken = await userAgetnApp.acquireTokenSilent({
        scopes: ['user.read'],
      });

      const user = await getUserDetails(accessToken);
      if (accessToken) {
        setIsAuthenticated(true);
        setEmail(user.mail || user.userPrincipalName);
        setUsername(user.displayName);
      }
    } catch (err) {
      if (err.name === 'InteractionRequiredAuthError') {
        return userAgetnApp
          .acquireTokenPopup({
            scopes: ['user.read'],
          })
          .then((response) => {
            // get access token from response
            // response.accessToken
          })
          .catch((err) => {
            // handle error
          });
      }

      setIsAuthenticated(false);
      setEmail(null);
      setUsername(null);
    }
  };

  const login = async () => {
    const loginn = await userAgetnApp.loginPopup({
      scopes: ['user.read'],
      // prompt: 'select_account',
    });

    console.log('login', loginn);
    await getUserProfile();
  };

  const logOut = async () => {
    await userAgetnApp.logout();
  };

  return (
    <>
      <button type="button" onClick={() => login()}>
        test
      </button>
    </>
  );
}
```

## Browsers/Environment
- [x] Electron

**Comment by hectormmg** [comment]
Hey @Ladvace, `msal@1.x` does not support your use case since it uses the implicit grant, which OAuth 2.0 discourages in your particular scenario. We recommend you use our `msal-node` library for this. I linked to the ElectronTestApp in issue #2701, hopefully that'll be helpful.  **Please note that although we have a working sample, we don't have an officially supported implementation of MSAL for Electron.**

**Comment by hectormmg** [comment]
Closing since the scenario is unsupported. If you have any further questions for your scenario, please raise a new issue.
