### ISSUE TITLE
Cached refresh token is not specific per token when making multiple token requests for different scopes w/B2C

### ISSUE THREAD

**Issue by Jeff-B1** [AzureAD/microsoft-authentication-library-for-js#2815]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.8.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [ ] Other

## Description
In Azure B2C using the auth code flow, an app resource scope requested in the ```/token``` call must also be requested in the ```/authorize``` call in order to receive an ```access_token``` in the ```/token``` response. Furthermore, the ```/authorize``` call does not allow requesting scopes from multiple resources. Thus two separate ```/authorize``` calls are necessary to get two separate ```access_token``` values (e.g. using two ```.ssoSilent``` requests, one for each resource scope needed). While MSAL includes the scope as part of the cache key for an ```access_token```, the cache key for the ```refresh_token``` does not. Thus the most recent ```refresh_token``` gets cached and any subsequent ```/token``` calls using a ```refresh_token``` will use the most recent ```refresh_token``` and not return an ```access_token``` when it is the incorrect one (i.e. a mismatch between the ```refresh_token``` and the requested scope).

## Error Message

- If requesting two app resource scopes, .ssoSilent fails with the following (fails as part of the ```/authorize``` call):
```
ServerError: invalid_request: AADB2C90146: The scope 'https://<tenant>.onmicrosoft.com/<app1>/user_impersonation https://<tenant>.onmicrosoft.com/<app2>/user_impersonation openid profile' provided in request specifies more than one resource for an access token, which is not supported.
Correlation ID: <guid>
Timestamp: 2020-12-30 00:35:12Z

    at ServerError.AuthError [as constructor] (.../msal-browser.js:509:28)
    at new ServerError (.../msal-browser.js:3340:32)
    at ResponseHandler.validateServerAuthorizationCodeResponse (.../msal-browser.js:4507:23)
    at AuthorizationCodeClient.handleFragmentResponse (.../msal-browser.js:4800:29)
    at SilentHandler.<anonymous> (.../msal-browser.js:8539:64)
    at step (.../msal-browser.js:80:27)
    at Object.next (.../msal-browser.js:61:57)
    at .../msal-browser.js:54:75
    at new Promise (<anonymous>)
    at __awaiter (.../msal-browser.js:50:16)
```

- Thus two separate ```.ssoSilent``` calls are used, one for each app resource needed. Using ```forceRefresh: true``` to always attempt to use the ```request_token``` when calling ```.acquireTokenSilent``` shows that the last ```refresh_token``` retrieved is used for subsequent token calls
``` js
POST https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<policy>/oauth2/v2.0/token
...
scope: https://<tenant>.onmicrosoft.com/<app1>/user_impersonation openid profile
code: ...
...

Response: {
  access_token: "..."
  client_info: "..."
  expires_in: 3600
  expires_on: 1609293203
  id_token: "..."
  not_before: 1609289603
  refresh_token: "ey...pVPg"
  refresh_token_expires_in: 86400
  resource: "<guid>"
  scope: "https://<tenant>.onmicrosoft.com/<app1>/user_impersonation"
  token_type: "Bearer"
}
```
``` js
POST https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<policy>/oauth2/v2.0/token
...
scope: https://<tenant>.onmicrosoft.com/<app2>/user_impersonation openid profile
code: ...
...

Response: {
  access_token: "..."
  client_info: "..."
  expires_in: 3600
  expires_on: 1609293204
  id_token: "..."
  not_before: 1609289604
  refresh_token: "ey...FliFg"
  refresh_token_expires_in: 86400
  resource: "<guid>"
  scope: "https://<tenant>.onmicrosoft.com/<app2>/user_impersonation"
  token_type: "Bearer"
}
```
``` js
POST https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<policy>/oauth2/v2.0/token
...
scope: https://<tenant>.onmicrosoft.com/<app1>/user_impersonation openid profile
grant_type: refresh_token
...
refresh_token: ey...FliFg //this is the refresh_token from the second call
...

//no access_token and wrong scope (due to sending wrong refresh_token for requested scope)
Response: {
  client_info: "..."
  id_token: "..."
  not_before: 1609289604
  refresh_token: "..."
  refresh_token_expires_in: 86400
  scope: "https://<tenant>.onmicrosoft.com/<app2>/user_impersonation"
  token_type: "Bearer"
}
```

## MSAL Configuration

```js
var _config = {
    auth: {
        clientId: ...
        , authority: ...
        , knownAuthorities: [...]
        , redirectUri: ...
    }
    , cache: {
        cacheLocation: 'localStorage'
        , storeAuthStateInCookie: true
    }
    , system: {
        loadFrameTimeout: 10000 //10 sec
        , loggerOptions: {
            loggerCallback: function (level, message, containsPii) {
                return; // comment out to log to console

                if (containsPii) {
                    return;
                }
                switch (level) {
                    case msal.LogLevel.Error:
                        console.error(message);
                        return;
                    case msal.LogLevel.Info:
                        console.info(message);
                        return;
                    case msal.LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case msal.LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
            , piiLoggingEnabled: false
        }
    }
};
```

## Reproduction steps
**After each token is loaded (and cached), subsequent calls to get tokens will use the most recent cached ```refresh_token```**

```js
var request_client = {
    scopes: [_clientScope]
    , loginHint: emailAddress
    , domainHint: identityProvider
};

var request_api = {
    scopes: [_apiScope]
    , loginHint: emailAddress
    , domainHint: identityProvider
};

_msalInstance = new msal.PublicClientApplication(_config);

... 

// note: some logic removed for this post

_msalInstance.ssoSilent(request_client)
    .then(function (loginResponse_client) {
        if (loginResponse_client) {
            _msalInstance.ssoSilent(request_api)
                .then(function (loginResponse_api) {
                    if (loginResponse_api) {
                        _currentAccount = _currentAccount || _msalInstance.getAllAccounts()[0];
                       ...
                    }
                })
                .catch(function (error) {
                    ...
                });
        }
    })
    .catch(function (error) {
        ...
    });

...

function getClientToken() {
    var request = {
        scopes: [_clientScope]
        , account: _currentAccount
        , forceRefresh: true // forces refresh_token to be used for repro
    };

    //get token for accessing client api
    return _msalInstance.acquireTokenSilent(request)
        .then(function (tokenResponse) {
            if (tokenResponse && tokenResponse.accessToken) {
                ...
            } else {
                throw 'no token';
            }
        })
        .catch(function (error) {
            ...
        });
}

function getApiToken() {
    var request = {
        scopes: [_apiScope]
        , account: _currentAccount
        , forceRefresh: true // forces refresh_token to be used for repro
    };

    //get token for accessing api
    return _msalInstance.acquireTokenSilent(request)
        .then(function (tokenResponse) {
            if (tokenResponse && tokenResponse.accessToken) {
                ...
            } else {
                throw 'no token';
            }
        })
        .catch(function (error) {
            ...
        });
}
```

## Expected behavior
Cached refresh token should be specific to the requested scope, allowing subsequent calls to ```.acquireTokenSilent``` to use correct ```refresh_token```

Below image shows that localstorage uses two accesstoken cache keys but only one idtoken and one refreshtoken cache key
![image](https://user-images.githubusercontent.com/76757529/103324336-f7ec2780-49fb-11eb-8e83-5a4a44f1df9d.png)

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [X] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by tnorling** [comment]
@Jeff-B1 This is a known issue with the B2C service. There is a work item open with the service to change the behavior of the refresh token to allow redemption for any consented scopes. There's already a long thread open regarding this issue so I'm going to close this as duplicate and you can track #2315 for resolution.

**Comment by Jeff-B1** [comment]
Thank you @tnorling !
