### ISSUE TITLE
MSAL Authenticaton fails for the SPFx webparts with 302 Errors in network tab (in low network speed scenario )

### ISSUE THREAD

**Issue by johnvittneyk** [AzureAD/microsoft-authentication-library-for-js#2975]
## Library

- [ ] `@azure/msal-browser@2.x.x`

## Framework

- [ ] React

## Description
Login Authentication fails in low internet speed scenario. 302 Errors are logged in the network tab. Please check the below screenshot

![image](https://user-images.githubusercontent.com/10572392/106954773-4490f400-675a-11eb-8862-97314bbe7d87.png)
![image](https://user-images.githubusercontent.com/10572392/106955065-b5d0a700-675a-11eb-80c2-f8c1c88a9785.png)

## Error Message

**302 errors in Network tab**

Error: token errorCouldn't retrieve access token
    at Object.o.trackException (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:85627)
    at Function.e.AppInsightsTrackException (https://publiccdn.sharepointonline.com/microsoft.sharepoint.com/teams/dev_uat2ucp/ClientSideAssets/702268e2-697d-415f-84ec-a05467437eef/wwc-base-webpart-web-part_4b6f0588ae732370eb532cc145171528.js:1:202724)
    at https://publiccdn.sharepointonline.com/microsoft.sharepoint.com/teams/dev_uat2ucp/ClientSideAssets/702268e2-697d-415f-84ec-a05467437eef/chunk.12_28efc83a49c56ff44a0d.js:1:20364

Error in fetching Active SEE Teams in fetchActiveSEETeamsCount(). Exception Name: undefined. Exception Message:undefined

## MSAL Configuration

```js
const msalConfig = {
  auth: {
    authority: `https://login.microsoftonline.com/microsoft.onmicrosoft.com`,
    clientId: config.default.AppSettings.msalClientId,
    redirectUri: window.location.href
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
};
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Load an SPFx Webpart in low network speed (<7MBPS)
```js
const allScopes = {
  xyzWebAPIScopes: [
    "https://xyz.azurewebsites.net/user_impersonation",
  ],
  graphAPIScopes: [
    "https://graph.microsoft.com/User.Read.All",
    "https://graph.microsoft.com/Presence.Read.All",
  ]
};

export enum msalAPISource {
  Xyz = "https://campuswebapi",
  MSGraph = "https://graph.microsoft.com"
}

const msalConfig = {
  auth: {
    authority: `https://login.microsoftonline.com/abc.onmicrosoft.com`,
    clientId: config.default.AppSettings.msalClientId,
    redirectUri:  window.location.href,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
};

export class WebAPIHelper {
  public userName: any;
  private myMSALObj: PublicClientApplication;
  private accessTokenCommon: any;
  private httpClient: HttpClient;
  private ssoRequest: AuthorizationUrlRequest = {
    scopes: [],
  };


constructor(wpContext: any, AuthContextCallback?: any, username?: any,isLogin?: boolean) {
    this.httpClient = wpContext.httpClient;
    this.userName = username;
    this.myMSALObj = new PublicClientApplication(msalConfig);
    
    this.myMSALObj
      .handleRedirectPromise()
      .then((tokenResponse) => {
        if (tokenResponse !== null) {
          this.accessTokenCommon = tokenResponse.accessToken;
        } else {
          // If the component needs login (First Webpart to load)
          if(isLogin){
            this.loginForAccessTokenByMSAL();
          }
          else{
          const currentAccounts = this.myMSALObj.getAllAccounts();
          this.handleLoggedInUser(currentAccounts);
          }
        }
      })
      .catch((error) => {
        return null;
      });
  }

  public GetxyzWebAPI(
    apiSource: APISource,
    apiRelativePath: string,
    jsonbody: string = null
  ): Promise<any> {
    return new Promise<any>(
      (resolve: (result: any) => void, reject: (error: any) => void): void => {
        this.getXyzAPIAccessToken(apiSource).then(
          async (accessToken: string): Promise<void> => {
            let fullAPIUrl: string;
            const requestHeaders: Headers = new Headers();
            requestHeaders.append(
              "User-Agent",
              "NONISV|Microsoft|XyzProjectWebparts/1.0"
            );
            requestHeaders.append(
              "X-ClientService-ClientTag",
              "NONISV|Microsoft|XyzProjectWebparts/1.0"
            );
            requestHeaders.append("Authorization", "Bearer " + accessToken);
            requestHeaders.append("Content-type", "application/json");
            const httpClientOptions: IHttpClientOptions = {
              body: jsonbody,
              headers: requestHeaders,
            };
            try {
              if (apiSource == APISource.MSGraph)
                fullAPIUrl = apiSource + "/" + apiRelativePath;
              else fullAPIUrl = this.getAPIBaseURL(apiSource) + apiRelativePath;
              const response = await this.httpClient.get(
                fullAPIUrl,
                HttpClient.configurations.v1,
                httpClientOptions
              );
              const output = await response.json();
              resolve(output);
            } catch (error) {
              reject(error);
            }
          },
          (error: any): void => {
            reject("token error" + error);
          }
        );
      }
    );
  }
  
  private getAPIBaseURL(apiSource: string): string {
   if (apiSource.indexOf("https://xyzwebapi") > -1)
      return config.default.AppSettings.WebApiUri + "/api/";
  }

  private getXyzAPIAccessToken(apiSource: APISource): Promise<string> {
    return new Promise<string>(
      async (
        resolve: (accessToken: string) => void,
        reject: (error: any) => void
      ): Promise<void> => {
        try {
          var accessToken = null;
          accessToken = await this.fetchAccessTokenByScopeMSAL(
            allScopes.xyzWebAPIScopes
          );
          if (accessToken) {
            resolve(accessToken);
          } else {
            reject("Couldn't retrieve access token");
          }
        } catch (ex) {
          reject(ex);
        }
      }
    );
  }

  public async GetGraphApi(apiUrl: string) {
    try {
      var accessToken = null;
      accessToken = await this.fetchAccessTokenByScopeMSAL(
        allScopes.graphAPIScopes
      );
      const options = {
        method: "GET",
        headers: {
          Accept: "application/json",
          "Content-type": "application/json",
          Authorization: "Bearer " + accessToken,
        },
      };
      const response = await this.httpClient.get(
        msalAPISource.MSGraph + apiUrl,
        HttpClient.configurations.v1,
        options
      );
      if (apiUrl.indexOf("photo/$value") > -1) {
        return response;
      }
      const responseJson = await response.json();
      return responseJson;
    } catch (err) {
      console.log(err);
      throw err;
    }
  }
private async fetchAccessTokenByScopeMSAL(specificScope: any): Promise<string> {
    const accessTokenRequest = {
      scopes: specificScope,
      account: this.myMSALObj.getAccountByUsername(this.userName),
    };
    this.ssoRequest.loginHint = this.userName;
    this.ssoRequest.scopes = specificScope;
    return this.myMSALObj
      .acquireTokenSilent(accessTokenRequest)
      .then((response) => {
        return response.accessToken;
      })
      .catch((silentError) => {
        if (silentError instanceof InteractionRequiredAuthError) {
          return this.myMSALObj
            .loginPopup()
            .then((response) => {
              return response.accessToken;
            })
            .catch((popupError) => {
              if (popupError.message.indexOf("popup_window_error") > -1) {
                // Popups are blocked
                return this.redirectLogin(this.ssoRequest);
              }
            });
        } else {
          return null;
        }
      });
  }
  private handleLoggedInUser(currentAccounts: AccountInfo[]) {
    let accountObj = null;
    if (currentAccounts === null && currentAccounts.length === 0) {
      // No user signed in
      return;
    } else if (currentAccounts.length > 1) {
      // More than one user is authenticated, get current one
      accountObj = this.myMSALObj.getAccountByUsername(this.userName);
    } else {
      accountObj = currentAccounts[0];
    }
    if (accountObj !== null) {
      this.acquireAccessToken(this.ssoRequest, accountObj).then(
        (accessToken) => {
          this.accessTokenCommon = accessToken;
          //return this.accessTokenCommon
        }
      );
    }
  }

  private async acquireAccessToken(
    ssoRequest: AuthorizationUrlRequest,
    account: AccountInfo
  ): Promise<string> {
    const accessTokenRequest = {
      scopes: allScopes.graphAPIScopes,
      account: account,
    };
    return this.myMSALObj
      .acquireTokenSilent(accessTokenRequest)
      .then((val) => {
        return val.accessToken;
      })
      .catch((errorinternal) => {
        console.log(errorinternal);
        return null;
      });
  }

 private async loginForAccessTokenByMSAL(): Promise<string> {
    this.ssoRequest.loginHint = this.userName;  
    return this.myMSALObj.ssoSilent(this.ssoRequest).then((response) => {
      return response.accessToken;  
    }).catch((error) => {  
        console.log(error);
        if (error instanceof InteractionRequiredAuthError) {
          return this.myMSALObj.loginPopup()
          .then((response) => {
            return response.accessToken;
          }) 
          .catch(error => {
            if (error.message.indexOf('popup_window_error') > -1) { // Popups are blocked
              return this.redirectLogin(this.ssoRequest);
            }            
          });
        } else {
            return null;
        }
    });  
  }


  private redirectLogin(ssoRequest: AuthorizationUrlRequest): Promise<string> {
    try {
      this.myMSALObj.loginRedirect()
        .then(() => {
          return Promise.resolve('');
        });
    } catch (err) {
      console.log(err);
      return null;
    }
  }

// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
Load seamlessly irrespective of internet speed

## Identity Provider

- [ ] Azure AD

## Browsers/Environment

- [ ] Edge

## Regression

- [ ] Did this behavior work before? No
Version:

## Security

- [ ] Is this issue security related? No

## Source

- [ ] Internal (Microsoft)

**Comment by hesperanca** [comment]
I'm a newbie with async js so I might be completely wrong here but are we allowed to call async functions in a constructor? Isn't it likely to cause problems?

**Comment by johnvittneyk** [comment]
@hesperanca Yes, You are right! We moved the authentication calls to ComponentDidMount and it worked

Thanks

**Comment by johnvittneyk** [comment]
Updated the authenication code in the constructor and moved it to new method Authenticate(isLogin?:boolean)
And we are calling this Authenticate method in ComponentDidMount() method in the webparts.

Now we see that the issue is fixed in one scenario where we clear cache and reload the page.

But this still exists in low network speed scenarios.

```
constructor(wpContext: any, AuthContextCallback?: any, username?: any,isLogin?: boolean) {
    this.httpClient = wpContext.httpClient;
    this.userName = username;
    this.myMSALObj = new PublicClientApplication(msalConfig);
  }

  public async Authenticate(isLogin?:boolean){
    await this.myMSALObj
    .handleRedirectPromise()
    .then(async (tokenResponse) => {
      if (tokenResponse !== null) {
         this.accessTokenCommon = tokenResponse.accessToken;
      } else {
        if(isLogin){
          await this.loginForAccessTokenByMSAL();
        }
        else{
        const currentAccounts = this.myMSALObj.getAllAccounts();
        await this.handleLoggedInUser(currentAccounts);
        }
      }
    })
    .catch((error) => {
      return null;
    });
  }
```

**Comment by tnorling** [comment]
@johnvittneyk Sorry this was missed. A 302 is a redirect, not an error and the error code you've shared is not one thrown by MSAL. Can you confirm what is throwing the error in your case?
