### ISSUE TITLE
msal-browser throws error when running unit tests in react @testing-library

### ISSUE THREAD

**Issue by kulbon** [AzureAD/microsoft-authentication-library-for-js#2980]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.11.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

Create React App
Tyscript
react: "^17.0.1"
@testing-library/react:  "^11.2.3"

## Description
new msal-browser package throws error when running unit tests in tesing-library.

## Error Message
```js
BrowserAuthError: crypto_nonexistent: The crypto object or function is not available. Detail:Browser crypto or msCrypto object not available.

       9 |
      10 | export function ProvideAuth({ children }: Props) {
    > 11 |     const msalInstance = new PublicClientApplication(msalConfig);
         |                          ^
      12 |     return <MsalProvider instance={msalInstance}>{children}</MsalProvider>;
      13 | }
      14 |

      at BrowserAuthError.AuthError [as constructor] (node_modules/@azure/msal-common/dist/index.es.js:413:24)
      at new BrowserAuthError (node_modules/@azure/msal-browser/src/error/BrowserAuthError.ts:128:9)
      at Function.Object.<anonymous>.BrowserAuthError.createCryptoNotAvailableError (node_modules/@azure/msal-browser/src/error/BrowserAuthError.ts:148:16)
      at new BrowserCrypto (node_modules/@azure/msal-browser/src/crypto/BrowserCrypto.ts:31:36)
      at new CryptoOps (node_modules/@azure/msal-browser/src/crypto/CryptoOps.ts:45:30)
      at PublicClientApplication.ClientApplication (node_modules/@azure/msal-browser/src/app/ClientApplication.ts:106:30)
      at new PublicClientApplication (node_modules/@azure/msal-browser/src/app/PublicClientApplication.ts:45:9)
      at ProvideAuth (src/services/authProvider.tsx:11:26)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:99:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:95:26)
      at Object.<anonymous> (src/App.test.tsx:15:22)

```
## MSAL Configuration

```js
export const msalConfig: Configuration = {
    auth: {
        clientId: process.env.REACT_APP_MSAL_ID!, 
        authority: b2cPolicies.authorities.signUpSignIn.authority, 
        knownAuthorities: [b2cPolicies.authorityDomain], 
        redirectUri: process.env.REACT_APP_MSAL_REDIRECT,
    },
    cache: {
        cacheLocation: 'localStorage', 
        storeAuthStateInCookie: false,
    },
};

export const b2cPolicies = {
    names: {
        signUpSignIn: 'B2C_1_SignIn',
        forgotPassword: 'b2c_1_reset',
        editProfile: 'b2c_1_edit_profile',
    },
    authorities: {
        signUpSignIn: {
            authority: process.env.REACT_APP_MSAL_AUTHORITY!,
        },
        forgotPassword: {
            authority: 'xxx.onmicrosoft.com/b2c_1_reset',
        },
        editProfile: {
            authority: 'xxxy.onmicrosoft.com/b2c_1_edit_profile',
        },
    },
    authorityDomain: process.env.REACT_APP_MSAL_AUTHORITY_DOMAIN!,
};
```

## Reproduction steps

```js
///App.text.tsx default from CRA
import React from 'react';
import { render, screen } from '@testing-library/react';
import App from './App';

test('renders learn react link', () => {
    render(<App />);
    const linkElement = screen.getByText(/learn react/i);
    expect(linkElement).toBeInTheDocument();
});

```

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [x] Other (Please add browser name here): NODE.js

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

**Comment by hectormmg** [comment]
Hi @kulbon ! What testing framework are you using underneath? You need to add "crypto" to your test environment globals. Check [this configuration file](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/jest.config.js) for an example of how we do that with `jest`.

**Comment by kulbon** [comment]
@hectormmg i'm using @testing-library/react: "^11.2.3"

Jest.config.js is not working in this case. 
I've tried add this code to the test and it's working

```
Object.defineProperty(global.self, 'crypto', {
    value: {
        // Needed for @azure/msal-browser
        subtle: {
            digest: jest.fn(),
        },
    },
});
```
But then a warning appears:
```
console.error
    Warning: An update to MsalProvider inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act```

**Comment by tnorling** [comment]
@kulbon Can you please try what the error asks you to do? This is an error thrown by `@testing-library/react` and they have documentation describing what this error is and how to resolve, I would recommend looking through their docs. You can also take a look at our [react tests](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react/test), which also use `@testing-library/react`, to see how we've written our tests.
