### ISSUE TITLE
Testing Failure with Both Sample and Custom Code

### ISSUE THREAD

**Issue by metal-slime** [AzureAD/microsoft-authentication-library-for-js#3053]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.11.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.0.0-alpha.4`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

We're trying to setup an Angular 10 project with MSAL. We're at the point where we're beginning to run tests and we're hitting a wall. Whether I run tests in our own project or in the Azure 10 sample, the tests fail returning the following:

```
NullInjectorError: R3InjectorError(DynamicTestModule)[AuthenticationService -> InjectionToken MSAL_GUARD_CONFIG -> InjectionToken MSAL_GUARD_CONFIG]:
          NullInjectorError: No provider for InjectionToken MSAL_GUARD_CONFIG!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'AuthenticationService', 'InjectionToken MSAL_GUARD_CONFIG', 'InjectionToken MSAL_GUARD_CONFIG' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[AuthenticationService -> InjectionToken MSAL_GUARD_CONFIG -> InjectionToken MSAL_GUARD_CONFIG]:
          NullInjectorError: No provider for InjectionToken MSAL_GUARD_CONFIG!
            at NullInjector.get (node_modules/@angular/core/fesm2015/core.js:915:1)
            at R3Injector.get (node_modules/@angular/core/fesm2015/core.js:11076:1)
            at R3Injector.get (node_modules/@angular/core/fesm2015/core.js:11076:1)
            at injectInjectorOnly (node_modules/@angular/core/fesm2015/core.js:801:1)
            at ɵɵinject (node_modules/@angular/core/fesm2015/core.js:805:1)
            at ɵɵdirectiveInject (node_modules/@angular/core/fesm2015/core.js:14601:1)
            at Object.AuthenticationService_Factory [as factory] (ng:///AuthenticationService/ɵfac.js:6:7)
            at R3Injector.hydrate (node_modules/@angular/core/fesm2015/core.js:11243:1)
            at R3Injector.get (node_modules/@angular/core/fesm2015/core.js:11065:1)
            at NgModuleRef$1.get (node_modules/@angular/core/fesm2015/core.js:24193:1)
```

I can't find anything we're missing. Are there any particular steps that need to be taken for this to work with karma testing and ng test? Thanks

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jo-arroyo** [comment]
@metal-slime It looks like you are not injecting the `MSAL_GUARD_CONFIG` in your test files. Please see [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular10-sample-app/src/app/app.component.spec.ts#L28) for an example of how the `MSAL_INSTANCE` is being injected into the test file for the `angular10-sample-app`. The `MSAL_GUARD_CONFIG` needs to be injected in the same way.

**Comment by Msimoneau** [comment]
Hi @jo-arroyo

I've the same error with both angular10-sample-app and angular11-sample-app sample applications.
These samples are working fine, but their tests (in app.component.spec.ts) failed.

Thank you.
