### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by addoyle** [AzureAD/microsoft-authentication-library-for-js#3263]
Using version 3.0.12

I'm getting this error trying to use assertion-based auth:
```
/home/centos/hirehub/node_modules/passport-azure-ad/lib/oidcstrategy.js:1453
    if (self._options.loggingNoPII)
        ^

ReferenceError: self is not defined
    at Strategy._getAccessTokenBySecretOrAssertion (/home/centos/hirehub/node_modules/passport-azure-ad/lib/oidcstrategy.js:1453:9)
    at Strategy.authCodeFlowHandler [as _authCodeFlowHandler] (/home/centos/hirehub/node_modules/passport-azure-ad/lib/oidcstrategy.js:1191:15)
    at async.waterfall (/home/centos/hirehub/node_modules/passport-azure-ad/lib/oidcstrategy.js:642:23)
    at fn (/home/centos/hirehub/node_modules/async/lib/async.js:746:34)
    at /home/centos/hirehub/node_modules/async/lib/async.js:1213:16
    at /home/centos/hirehub/node_modules/async/lib/async.js:166:37
    at /home/centos/hirehub/node_modules/async/lib/async.js:706:43
    at /home/centos/hirehub/node_modules/async/lib/async.js:167:37
    at /home/centos/hirehub/node_modules/async/lib/async.js:1209:30
    at /home/centos/hirehub/node_modules/async/lib/async.js:52:16
```

**Comment by pkanher617** [comment]
Going to close for now, but will make sure to address this in the new version of the library. You can track the changes [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9).
