### ISSUE TITLE
Error ClientAuthError: no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().

### ISSUE THREAD

**Issue by senal** [AzureAD/microsoft-authentication-library-for-js#3451]
### Core Library

@azure/msal-browser

### Core Library Version

2.13.1

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.1

### Description

Before any calls to our backend API, we retrieve a token from msal library. to be sent in the request header.

`instance.acquireTokenSilent({
      ...{scopes: ["openid", "profile", ...config.config.resourceScopes]},
      account: account
    }`

This call has been guarded within a check on the `account` object. 

Note that, at any given moment we have only one account that exists.

**Temp fix to get users moving**
Reload the application after removing what stored in the localStorage.

### Error Message

`Error ClientAuthError: no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().
    at ClientAuthError.AuthError [as constructor] (http://localhost:3000/static/js/vendors~main.chunk.js:11407:20)
    at new ClientAuthError (http://localhost:3000/static/js/vendors~main.chunk.js:11655:24)
    at Function.ClientAuthError.createNoTokensFoundError (http://localhost:3000/static/js/vendors~main.chunk.js:11779:12)
    at RefreshTokenClient.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:17019:33)
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:10997:17)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:10928:14)
    at http://localhost:3000/static/js/vendors~main.chunk.js:10900:67
    at new Promise (<anonymous>)
    at __awaiter$1 (http://localhost:3000/static/js/vendors~main.chunk.js:10879:10)
    at RefreshTokenClient.acquireTokenWithCachedRefreshToken (http://localhost:3000/static/js/vendors~main.chunk.js:17013:12)
    at RefreshTokenClient.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:17002:16)
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:10997:17)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:10928:14)
    at http://localhost:3000/static/js/vendors~main.chunk.js:10900:67
    at new Promise (<anonymous>)
    at __awaiter$1 (http://localhost:3000/static/js/vendors~main.chunk.js:10879:10)`

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
        auth: {
            clientId,
            redirectUri,
            authority,
            navigateToLoginRequestUrl: false,
        },
        cache: {
            cacheLocation:  'localStorage'
        }
    };
```

### Relevant Code Snippets

```javascript
internal impl.
```

### Reproduction Steps

This error looks like intermittent couldn't reproduce it.
But this has happened to our couple of internal developers.

### Expected Behavior

The token retrieval should happen without any errors.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@senal This error means there is no cached tokens for the given request, including no cached refresh token. To resolve, you should prompt your users to login (interactively or via ssoSilent).

**Comment by senal** [comment]
@jasonnutter,

Thanks for this.

But we saw some information was stored in the localStorage at the time of this error.
Does that mean the content in the locale storage neither the cached token nor the cached refresh token?

We had to remove the content in the local storage to get the prompt for the user again.

Do you have any idea how do we reproduce this error in order to test the proposed solution you given above?

Appreciate your help in this regard.
