### ISSUE TITLE
Intermittent BrowserAuthError using loginPopup in a REACT PWA

### ISSUE THREAD

**Issue by SimoneRavetto** [AzureAD/microsoft-authentication-library-for-js#3495]
### Core Library

@azure/msal-browser

### Core Library Version

2.13.1

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.1

### Description

I'm using MSAL JS in order to authenticate users in a PWA application developed using REACT. Sometimes login works perfectly, redirecting users to the home page of the app. Other times login popup opens, users insert their login but then login procedure fails with a BrowserAuthError error.

After a login error a page refresh with browser data cleaning permit users to logon correctly. I can't understand what cause this problem.

### Error Message

BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. 
Please verify that your redirectUri is not clearing the hash. 
Given Url: https://xxxxxx-dev.azurewebsites.net/login
    at t [as constructor] (https://xxxxxx-dev.azurewebsites.net/static/js/6.21bce126.chunk.js:2:163177)
    at new t (https://xxxxxx-dev.azurewebsites.net/static/js/6.21bce126.chunk.js:2:266493)
    at Function.t.createEmptyHashError (https://xxxxxx-dev.azurewebsites.net/static/js/6.21bce126.chunk.js:2:266991)
    at https://xxxxxx-dev.azurewebsites.net/static/js/6.21bce126.chunk.js:2:304999

### Msal Logs

[Tue, 20 Apr 2021 12:46:52 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:loginStart
azure-authentication-config.ts:33 
[Tue, 20 Apr 2021 12:46:52 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:popupOpened
azure-authentication-config.ts:33 
[Tue, 20 Apr 2021 12:47:22 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:loginFailure
azure-authentication-config.ts:33 
[Tue, 20 Apr 2021 12:47:22 GMT] :  : @azure/msal-browser@2.13.1 : Info - BrowserCacheManager.cleanRequestByState: Removing temporary cache items for state: eyJpZCI6IjY4ODkxYTNhLWY1OWMtNGJkMC04MThmLTkyMDliMTA3NTE1YSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0=
azure-authentication-context.ts:72 
BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: https://xxxxxx-dev.azurewebsites.net/login
    at t [as constructor] (https://xxxxxx-dev.azurewebsites.net/static/js/6.fb5452ee.chunk.js:2:162980)
    at new t (https://xxxxxx-dev.azurewebsites.net/static/js/6.fb5452ee.chunk.js:2:267449)
    at Function.t.createEmptyHashError (https://xxxxxx-dev.azurewebsites.net/static/js/6.fb5452ee.chunk.js:2:267947)
    at https://xxxxxx-dev.azurewebsites.net/static/js/6.fb5452ee.chunk.js:2:305955

### MSAL Configuration

```javascript
export const MSAL_CONFIG: Configuration = {
      auth: {
        clientId: AzureActiveDirectoryAppClientId,
        authority: `https://login.microsoftonline.com/${AzureTenantId}`,
        knownAuthorities: [],
        redirectUri: window.location.origin
      },
      cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: true,
      },
      system: {
        loggerOptions: {
          loggerCallback: (level, message, containsPii) => {
            if (containsPii) {
              return;
            }
            switch (level) {
              case LogLevel.Error:
                console.error(message);
                return;
              case LogLevel.Info:
                console.info(message);   // when fails this message appears: "[Thu, 15 Apr 2021 07:06:24 GMT] :  : @azure/msal-browser@2.13.0 : Info - Emitting event: msal:loginFailure"
                return;
              case LogLevel.Verbose:
                console.debug(message);
                return;
              case LogLevel.Warning:
                console.warn(message);
                return;
            }
          },
        },
      },
    };
```

### Relevant Code Snippets

```javascript
Login Method


private myMSALObj: PublicClientApplication = new PublicClientApplication(
    MSAL_CONFIG
  );

this.loginRequest = {
      scopes: [],
      prompt: "select_account",
      redirectUri: BaseUrl
    };

this.myMSALObj
        .loginPopup(this.loginRequest)
        .then((resp: AuthenticationResult) => {
          console.log(resp);
        })
        .catch((err) => {
          console.log(err);   // here the error showed before
        });
```

### Reproduction Steps

1. Login with popup
2. Sometimes BrowserAuthError error occurred

### Expected Behavior

Login make the user redirect to the app home page - this sometimes works

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge, Safari

### Source

External (Customer)

**Comment by SimoneRavetto** [comment]
@jasonnutter I'm trying to debug this problem... 
In _acquireTokenPopupAsync_ function seems that I have the hash empty:

![image](https://user-images.githubusercontent.com/19594796/115440071-a0becc80-a20f-11eb-9c0d-0d518c58ed00.png)

I can't understand where this hash is cleared, also because it has been cleared only sometimes (seems related with the quickness of login procedure, but I'm not so sure).

This is an example of url of the popup: https://login.microsoftonline.com/TENANT/oauth2/v2.0/authorize?client_id=CLIENT&scope=openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fsiteinspection-dev.azurewebsites.net&client-request-id=d2872ffb-6008-4b31-b460-29c2c44a4f42&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.13.1&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=27CIKho95xSrnQQntySxLTM4FIb_IfuMCHB-tdtflv4&code_challenge_method=S256&prompt=select_account&nonce=cf7b7c48-0a87-4e83-928b-efc3f4c67b21&state=eyJpZCI6ImRjMWI2YWI5LTNkN2EtNDhkYy1iZjgzLWU4YTNiOTJkZDY0NSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0%3D

In my custom code there isn't hash clearing, so I'm not able to find the problem. Can you help me? Do you need any other information? 

Thanks
Simone

**Comment by SimoneRavetto** [comment]
Solved changing the redirect url to the same login url - no more problems.
