### ISSUE TITLE
Msal Guard doesn't let me browse after redirect

### ISSUE THREAD

**Issue by matteocusinato** [AzureAD/microsoft-authentication-library-for-js#3591]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0-beta.5

### Description

Hi, I am using the b2c version of azure @ msal-angular. When I updated to version 2.0.0-beta.5 I noticed that after the redirect (after login) it no longer navigates to the desired component and it looks like it is MsalGuard.
I attach a console error if it can be useful.

Thank you!

### Error Message

```
ERROR ClientAuthError: access_token_entity_null: Access token entity is null, please check logs and cache to ensure a valid access token is present.
    at ClientAuthError.AuthError [as constructor] (http://localhost:8100/vendor.js:188449:20)
    at new ClientAuthError (http://localhost:8100/vendor.js:188701:24)
    at Function.ClientAuthError.createAccessTokenEntityNullError (http://localhost:8100/vendor.js:189038:12)
    at Function.<anonymous> (http://localhost:8100/vendor.js:193296:35)
    at step (http://localhost:8100/vendor.js:188028:19)
    at Object.next (http://localhost:8100/vendor.js:187958:14)
    at http://localhost:8100/vendor.js:187930:67
    at new ZoneAwarePromise (http://localhost:8100/polyfills.js:1644:23)
    at __awaiter$1 (http://localhost:8100/vendor.js:187909:10)
    at Function.ResponseHandler.generateAuthenticationResult (http://localhost:8100/vendor.js:193258:12)
```

### MSAL Configuration

```javascript
{
    auth: {
      clientId: environment.clientId,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: environment.redirectUri,
      postLogoutRedirectUri: environment.postLogoutRedirectUri,
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: environment.production ? LogLevel.Error : LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  }
```

### Relevant Code Snippets

```javascript
This is the inaccessible route:

`{ path: 'dashboard', loadChildren: () => import('src/app/pages/dashboard/dashboard.module').then(m => m.DashboardPageModule), canActivate: [MsalGuard]},`
```

### Reproduction Steps

1 Create a route to navigate after login
2 Put the MsalGuard guard on this route

### Expected Behavior

I would expect the route guard to return true.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-angular@2.0.0-beta.5

### Source

External (Customer)

**Comment by eluchsinger** [comment]
This is probably a duplicate of: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3530

**Comment by matteocusinato** [comment]
Close as of duplicate of: #3530
