### ISSUE TITLE
Unable to handle BrowserAuthError from user closing pop up with msal-react 

### ISSUE THREAD

**Issue by kwilkins** [AzureAD/microsoft-authentication-library-for-js#3724]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

I have a simple react app that attempts to login the user automatically with the popup window method, however if the user closes the popup window the react app crashes. I've also seen this happen at certain times when the browser blocks the popup from appearing. I'd like to catch/handle these errors but so far I have been unsuccessful with preventing the app crash. Is this some kind of error that is bubbling up unexpectedly?

I am migrating from react-aad-msal by the way, if that helps any.

### Error Message

AuthError.ts:40 Uncaught (in promise) BrowserAuthError: user_cancelled: User cancelled the flow.
    at BrowserAuthError.AuthError [as constructor] (http://localhost:3000/static/js/vendors~main.chunk.js:17476:20)
    at new BrowserAuthError (http://localhost:3000/static/js/vendors~main.chunk.js:8950:24)
    at Function.BrowserAuthError.createUserCancelledError (http://localhost:3000/static/js/vendors~main.chunk.js:9066:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11497:94

### Msal Logs

[Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createAuthCodeClient called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:popupOpened
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 41c7b400-dc9b-480a-b1e9-70427eb929b6: msal:popupOpened
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback ac9817b2-271a-4a79-a25d-972b742da521: msal:popupOpened
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5a90ab89-0ed2-484b-8d06-afd4ce92973a: msal:popupOpened
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:21 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account
2msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:22 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:loginFailure
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 41c7b400-dc9b-480a-b1e9-70427eb929b6: msal:loginFailure
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
aadMsalAuthenticator.tsx:38 my react code logs this BrowserAuthError: user_cancelled: User cancelled the flow.
    at BrowserAuthError.AuthError [as constructor] (http://localhost:3000/static/js/vendors~main.chunk.js:17476:20)
    at new BrowserAuthError (http://localhost:3000/static/js/vendors~main.chunk.js:8950:24)
    at Function.BrowserAuthError.createUserCancelledError (http://localhost:3000/static/js/vendors~main.chunk.js:9066:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11497:94
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback ac9817b2-271a-4a79-a25d-972b742da521: msal:loginFailure
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-react@1.0.0 : Info - MsalProvider - no account changes
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5a90ab89-0ed2-484b-8d06-afd4ce92973a: msal:loginFailure
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-react@1.0.0 : Info - MsalProvider - msal:loginFailure results in setting inProgress to none
2msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
aadMsalAuthenticator.tsx:38 my react code logs this BrowserAuthError: user_cancelled: User cancelled the flow.
    at BrowserAuthError.AuthError [as constructor] (http://localhost:3000/static/js/vendors~main.chunk.js:17476:20)
    at new BrowserAuthError (http://localhost:3000/static/js/vendors~main.chunk.js:8950:24)
    at Function.BrowserAuthError.createUserCancelledError (http://localhost:3000/static/js/vendors~main.chunk.js:9066:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11497:94
2msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:23 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
aadMsalAuthenticator.tsx:38 my react code logs this BrowserAuthError: user_cancelled: User cancelled the flow.
    at BrowserAuthError.AuthError [as constructor] (http://localhost:3000/static/js/vendors~main.chunk.js:17476:20)
    at new BrowserAuthError (http://localhost:3000/static/js/vendors~main.chunk.js:8950:24)
    at Function.BrowserAuthError.createUserCancelledError (http://localhost:3000/static/js/vendors~main.chunk.js:9066:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11497:94
AuthError.ts:40 Uncaught (in promise) BrowserAuthError: user_cancelled: User cancelled the flow.
    at BrowserAuthError.AuthError [as constructor] (http://localhost:3000/static/js/vendors~main.chunk.js:17476:20)
    at new BrowserAuthError (http://localhost:3000/static/js/vendors~main.chunk.js:8950:24)
    at Function.BrowserAuthError.createUserCancelledError (http://localhost:3000/static/js/vendors~main.chunk.js:9066:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:11497:94
AuthError @ AuthError.ts:40
BrowserAuthError @ BrowserAuthError.ts:151
BrowserAuthError.createUserCancelledError @ BrowserAuthError.ts:257
(anonymous) @ PopupUtils.ts:127
Promise.then (async)
step @ spec.js:344
fulfilled @ spec.js:344
Promise.then (async)
step @ spec.js:344
fulfilled @ spec.js:344
Promise.then (async)
step @ spec.js:344
fulfilled @ spec.js:344
Promise.then (async)
step @ spec.js:344
(anonymous) @ spec.js:344
__awaiter @ spec.js:344
ClientApplication.acquireTokenPopupAsync @ ClientApplication.ts:457
ClientApplication.acquireTokenPopup @ ClientApplication.ts:445
PublicClientApplication.loginPopup @ PublicClientApplication.ts:71
(anonymous) @ unAuthenticatedDisplay.tsx:38
BaseButton._this._onClick @ BaseButton.tsx:778
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
2msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:24 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account
2msalAuthenticationProviderService.ts:91 [Mon, 07 Jun 2021 22:35:25 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account

### MSAL Configuration

```javascript
{
  auth: {
    authority: `https://login.microsoftonline.com/${<my tenant id>}`,
    clientId: '<my client id>',
    redirectUri: urljoin(window.location.origin, 'auth.html')
  }
}
```

### Relevant Code Snippets

```javascript
// This is my component that renders based on whether the user is logged in or not
// The MsalProvider component is set at the App root level as described in the tutorial 

const AadMsalAuthenticator: React.FunctionComponent<IAadMsalAuthenticatorProps> = (props: IAadMsalAuthenticatorProps): JSX.Element => {
  const isAuthenticated = useIsAuthenticated();
  const { result, error } = useMsalAuthentication(InteractionType.Popup);

  useEffect(() => {
    if (result) {
      setAuthenticatedUser();
    }
  }, [result]);

  if (isAuthenticated) {
    return (<>{props.authenticatedComponent}</>);
  } else {
    if (error) {
      // eslint-disable-next-line no-console
      console.log('my react code logs this', error);
    }
    return (
      <ContentWrapperWithDefaultButton
        buttonLabel={error ? 'Close' : 'Cancel'}
        buttonOnClick={props.onCancel}
      >
        {error
          ? <UnAuthenticatedDisplay error={error} />
          : <InProgressDisplay />
        }
      </ContentWrapperWithDefaultButton>
    );
  }
};
```

### Reproduction Steps

1. Load app with msal-react configured to login with pop up window
2. Close pop up window

### Expected Behavior

msal-react should not crash when pop up window is closed but pass error within library

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

Internal (Microsoft)

**Comment by kwilkins** [comment]
As typical debugging goes, I discovered the solution right after I created the incident.

The button users can use to manually login was calling `msalContext.instance.loginPopup()` without awaiting which was throwing the error into the ether and crashing the app. Properly awaiting this call, and wrapping it in try/catch solved this for me.
