### ISSUE TITLE
Calling acquireTokenSilent throws but error cannot be caught

### ISSUE THREAD

**Issue by rhummelmose** [AzureAD/microsoft-authentication-library-for-js#3781]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not applicable

### Description

Calling ssoSilent throws but error cannot be caught.

### Error Message

```
Exception has occurred: ClientAuthError: token_refresh_required: Cannot return token from cache because it must be refreshed. This may be due to one of the following reasons: forceRefresh parameter is set to true, claims have been requested, there is no cached access token or it is expired.
  at ClientAuthError.AuthError [as constructor] (http://localhost:9999/main.react.bundle.js:566:24)
    at new ClientAuthError (http://localhost:9999/main.react.bundle.js:810:28)
    at Function.ClientAuthError.createRefreshRequiredError (http://localhost:9999/main.react.bundle.js:1042:16)
    at SilentFlowClient.<anonymous> (http://localhost:9999/main.react.bundle.js:5645:51)
    at step (http://localhost:9999/main.react.bundle.js:215:23)
    at Object.next (http://localhost:9999/main.react.bundle.js:196:53)
    at http://localhost:9999/main.react.bundle.js:189:71
    at new Promise (<anonymous>)
    at __awaiter$1 (http://localhost:9999/main.react.bundle.js:185:12)
    at SilentFlowClient.acquireCachedToken (http://localhost:9999/main.react.bundle.js:5622:16)
```

### Msal Logs

```
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - preflightBrowserEnvironmentCheck started
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - ssoSilent called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:ssoSilentStart
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - acquireTokenByIframe called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - initializeAuthorizationRequest called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getRedirectUri called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Initializing BaseAuthRequest
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getActiveAccount: No active account
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getTemporaryCache called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.updateCacheEntries called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - initializeServerTelemetryManager called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - createAuthCodeClient called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getClientConfiguration called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getDiscoveredAuthority called
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Creating discovered authority with request authority
MSAL | [Tue, 22 Jun 2021 17:09:49 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - validateAndExtractStateFromHash called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Returning state from hash
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getTemporaryCache called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getTemporaryCache called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-common@4.2.1 : Info - in acquireToken call
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getServerTelemetry called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getThrottlingCache called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getServerTelemetry called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setAccount called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setAccessTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setRefreshTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.cleanRequestByState called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Info - BrowserCacheManager.cleanRequestByState: Removing temporary cache items for state: eyJpZCI6ImFjYzM2MjYyLTIzZTMtNGQ3Ni1iMTMzLTM0MDgzNGVhNGU2YSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoic2lsZW50In19
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.resetRequestCache called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:ssoSilentSuccess
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - preflightBrowserEnvironmentCheck started
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - acquireTokenSilent called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Initializing BaseAuthRequest
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:acquireTokenStart
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - initializeServerTelemetryManager called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - createSilentFlowClient called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getClientConfiguration called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getDiscoveredAuthority called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Creating discovered authority with request authority
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:50 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
MSAL | [Tue, 22 Jun 2021 17:09:51 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit

```

### MSAL Configuration

```javascript
{
    system: {
        loggerOptions: {
            logLevel: msal.LogLevel.Verbose,
            loggerCallback: (level, message, containsPii) => console.log(`MSAL ${message}`),
        },
    },
    auth: {
        clientId: configuration.aad.reactApplicationClientId,
        authority: `https://login.microsoftonline.com/${configuration.aad.tenant}`,
        redirectUri: configuration.aad.reactRedirectUrl,
    },
}
```

### Relevant Code Snippets

```javascript
try {
    const authRequest: msal.PopupRequest & msal.SilentRequest = {
        scopes: [
            `api://${configuration.aad.applicationClientId}/Access.API`,
            "openid",
            "profile",
            "User.Read",
        ],
    };
    const sessionId = localStorage.getItem(AuthLocalStorageKey.SID);
    if (sessionId == null) {
        throw new Error("AuthActionType loginSilent dispatched but no session ID was found in local storage");
    }
    authRequest.sid = sessionId;
    authResult = await msalInstance.ssoSilent(authRequest);
    action.result = authResult;
} catch (error) {
    console.log(`MSAL error: ${error}`);
    action.error = error;
}
return action;
```

### Reproduction Steps

1. Use MSAL.js browser package
2. Run ssoSilent with a session id from local storage
3. Get the error back that cannot be caught

### Expected Behavior

Error should be catchable

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@rhummelmose This error is not being thrown by `ssoSilent`. It is thrown by the `SilentFlowClient` which is created internally when calling `acquireTokenSilent` and should be caught and handled internally by MSAL. It should never be thrown back to you as the developer. Can you please share the code you are using to call `acquireTokenSilent`? Can you also please confirm that you are not using the `SilentFlowClient` directly?

**Comment by rhummelmose** [comment]
@tnorling See the code snippet, that is all I do.

**Comment by tnorling** [comment]
@rhummelmose Something else is being run somewhere. You can see it in the logs shared. `ssoSilent` is succeeding and immediately afterwards `acquireTokenSilent` is called.

**Comment by rhummelmose** [comment]
@tnorling Shit you're right :) I'll close when verified. Thanks.

**Comment by tnorling** [comment]
Great thanks! It's worth repeating that I don't expect `token_refresh_required` error to ever be thrown back to you. If it is we should understand why because MSAL should be swallowing that error.

**Comment by rhummelmose** [comment]
It's happening here:
```typescript
const UserMSALGraphAuthProvider = (
    msalInstance: MSAL.IPublicClientApplication,
    user: User
): Graph.AuthProvider => async (done: Graph.AuthProviderCallback) => {
    const authResult = user.properties as MSAL.AuthenticationResult;
    const tokenRequest = {
        account: authResult.account,
        scopes: ["User.Read"],
    };
    try {
        const tokenResult = await msalInstance.acquireTokenSilent(tokenRequest);
        done(undefined, tokenResult.accessToken);
    } catch (error) {
        done(error, null);
    }
};
```

https://user-images.githubusercontent.com/620878/122988226-ca2bde00-d3a1-11eb-90b5-072bcf7d6bdc.mp4

**Comment by tnorling** [comment]
@rhummelmose From the video it doesn't appear that this error is being thrown to your application, it's being thrown and handled inside msal-browser as I would expect. Are you seeing this error anywhere else when you're not using debug tools? This is an internal mechanism MSAL uses to fallback to making a network call to refresh the token instead of returning a token from the cache.

**Comment by rhummelmose** [comment]
@tnorling you are correct but it is not being swallowed correctly by MSAL, otherwise I wouldn't catch it with the "Uncaught exception" breakpoint.

**Comment by tnorling** [comment]
I'm not sure I understand. It does not appear to be caught by the "Uncaught exception" breakpoint but rather one of the other breakpoints (which are hidden by the recording widget). If it was uncaught I would expect to see it in the console. Nevertheless, if you can reproduce this in a non-debug setting we can take a closer look.

**Comment by rhummelmose** [comment]
@tnorling But if I remove all breakpoints apart from the uncaught exception breakpoint, it still bubbles up to the debugger. We use a lot of packages and only have this type of problem with MSAL.

https://user-images.githubusercontent.com/620878/123048895-32f57380-d3ff-11eb-8042-c54314ed811f.mp4

**Comment by tnorling** [comment]
@rhummelmose I'm not familiar enough with the debugging tool you're using here to have a good answer for you unfortunately. Unless you can show me this error is being thrown to your app or to the browser in a production setting I'm not going to spend time tracking this down, especially as it looks like everything is working as expected after you clear the breakpoint. I can tell you that this error is thrown [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/client/SilentFlowClient.ts#L40) and wrapped in a try catch [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ac876cd1c8fecb7c0f8365082800de30ab60ec60/lib/msal-browser/src/app/PublicClientApplication.ts#L101) so I'm not sure why your debugger would think it's uncaught. If you want to do some investigation on your own and come to us with a solution we would be more than happy to look at a PR.
