### ISSUE TITLE
TypeError: this.fail is not a function

### ISSUE THREAD

**Issue by bonk-se** [AzureAD/microsoft-authentication-library-for-js#3849]
My node server crashes when I get an authentication failure, since it can't handle the error message properly. Here's the crash log:

```
...\node_modules\passport-azure-ad\lib\bearerstrategy.js:602
  return this.fail(message);
              ^
TypeError: this.fail is not a function
    at Strategy.failWithLog (...\node_modules\passport-azure-ad\lib\bearerstrategy.js:602:15)
    at ...\node_modules\passport-azure-ad\lib\bearerstrategy.js:325:21
    at ...\node_modules\passport-azure-ad\lib\jsonWebToken.js:80:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Just before the crash, the error log for an authentication error is printed, containing:
"authentication failed due to: invalid signature"
which matches the failWithLog-functions output

**Comment by jo-arroyo** [comment]
Closing as passport-azure-ad is now in maintenance, and will not be receiving new updates. We are currently working on building new middleware scenarios on top of msal-node, please watch for future msal-node updates.
