### ISSUE TITLE
TypeError: cryptoObj.getRandomValues is not a function; unrelated error when using jest & testing-library/react

### ISSUE THREAD

**Issue by jonybekov** [AzureAD/microsoft-authentication-library-for-js#3876]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I have a project where I've used msal-react & msal-browser in some part of my application. When I try to test some other components (which doesn't depend on msal-browser) using react-testing-library and run npm test I get _TypeError: cryptoObj.getRandomValues is not a function_ error. Before I was getting _crypto_nonexistent_ error like mentioned in [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2980) and managed to fix this error by adding crypto to jest globals using craco.

Here's my jest config.
![Jest config](https://user-images.githubusercontent.com/39439363/126031307-cfe65639-2d21-4d17-a3a6-9165bf660165.png)

### Error Message

 FAIL  src/home/__tests__/offices-explore.test.tsx
  ● Test suite failed to run

    TypeError: cryptoObj.getRandomValues is not a function

      12 |
      13 | import React, { useState, useEffect } from 'react';
    > 14 | import { models, Embed, service } from 'powerbi-client';
         | ^
      15 | import { PowerBIEmbed } from 'powerbi-client-react';
      16 | import { appServices } from 'common/services';
      17 | import { useAccount, useMsal } from '@azure/msal-react';

      at Function.WindowPostMessageProxy.createRandomString (node_modules/powerbi-client/dist/webpack:/powerbi-client/node_modules/window-post-message-proxy/dist/windowPostMessageProxy.js:125:1)
      at new WindowPostMessageProxy (node_modules/powerbi-client/dist/webpack:/powerbi-client/node_modules/window-post-message-proxy/dist/windowPostMessageProxy.js:77:1)
      at wpmpFactory (node_modules/powerbi-client/dist/webpack:/powerbi-client/src/factories.ts:27:10)
      at new Service (node_modules/powerbi-client/dist/webpack:/powerbi-client/src/service.ts:160:17)
      at Object../src/powerbi-client.ts (node_modules/powerbi-client/dist/webpack:/powerbi-client/src/powerbi-client.ts:64:15)
      at __webpack_require__ (node_modules/powerbi-client/dist/webpack:/powerbi-client/webpack/bootstrap:19:1)
      at node_modules/powerbi-client/dist/webpack:/powerbi-client/webpack/bootstrap:83:1
      at node_modules/powerbi-client/dist/powerbi.js:100:10
      at webpackUniversalModuleDefinition (node_modules/powerbi-client/dist/webpack:/powerbi-client/webpack/universalModuleDefinition:3:1)
      at Object.<anonymous> (node_modules/powerbi-client/dist/webpack:/powerbi-client/webpack/universalModuleDefinition:10:2)
      at Object.<anonymous> (src/analytics/PowerBi/powerbi.tsx:14:1)
      at Object.<anonymous> (src/analytics/PowerBi/index.tsx:5:1)
      at Object.<anonymous> (src/main/App/App.tsx:18:1)
      at Object.<anonymous> (src/home/OfficesExplore/offices-explore.tsx:12:1)
      at Object.<anonymous> (src/home/OfficesExplore/index.tsx:1:1)
      at Object.<anonymous> (src/home/__tests__/offices-explore.test.tsx:3:1)

### MSAL Configuration

```javascript
import { PublicClientApplication, Configuration } from '@azure/msal-browser';

const config: Configuration = {
  auth: {
    authority: `https://login.microsoftonline.com/${MsalConfig.Corporate_AAD}`,
    clientId: MsalConfig.ClientId,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
};

export const authenticationParameters = {
  scopes: [
    'https://analysis.windows.net/powerbi/api/App.Read.All',
    'https://analysis.windows.net/powerbi/api/Dataset.Read.All',
    'https://analysis.windows.net/powerbi/api/Dashboard.Read.All',
    'https://analysis.windows.net/powerbi/api/Report.Read.All',
  ],
};

export const msalObj = new PublicClientApplication(config);
```

### Relevant Code Snippets

```javascript
import React from 'react';
import { render } from '@testing-library/react';
import OfficesExplore from 'home/OfficesExplore';

describe('OfficesExplore', () => {
  test('renders without crashing', () => {
    render(
      <OfficesExplore employeeId={ '1' } />
    );
  });
});
```

### Reproduction Steps

 1. write test for the component that doesn't rely one msal-browser/react packages.
 2. run npm test

### Expected Behavior

Npm test command should work without any problems because the component that I am testing doesn't rely on any msal related packages. Moreover I've added crypto to globals as suggested in code samples.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by jonybekov** [comment]
Sorry but I realized that this is unrelated to msal-browser. It's related to powerbi-client. I fixed it using [this comment](https://github.com/microsoft/powerbi-client-react/issues/21#issuecomment-766722092) if anyone needs
