### ISSUE TITLE
[adal-node] crash with error: Entry not found in cache

### ISSUE THREAD

**Issue by sinedied** [AzureAD/microsoft-authentication-library-for-js#4155]
### Core Library

ADAL Node (adal-node)

### Core Library Version

0.2.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I'm using the package `ms-rest-azure@3.0.0` to authenticate users through Azure and get access to their subscription to perform operations on it from a Node.js CLI tool.

For some users that seems to only have 1 subscription in their Azure account, the underlying `adal-node` library crash with the following error message.

### Error Message

{
  error: Error: Entry not found in cache.
      at Logger.createError (/home/olleplus/lab/thundr-auth-server/node_modules/ms-rest-azure/node_modules/adal-node/lib/log.js:216:13)
      at TokenRequest.<anonymous> (/home/olleplus/lab/thundr-auth-server/node_modules/ms-rest-azure/node_modules/adal-node/lib/token-request.js:526:40)
      at /home/olleplus/lab/thundr-auth-server/node_modules/ms-rest-azure/node_modules/adal-node/lib/token-request.js:148:20
      at /home/olleplus/lab/thundr-auth-server/node_modules/ms-rest-azure/node_modules/adal-node/lib/cache-driver.js:366:7
      at /home/olleplus/lab/thundr-auth-server/node_modules/ms-rest-azure/node_modules/adal-node/lib/cache-driver.js:301:7
      at Request._callback (/home/olleplus/lab/thundr-auth-server/node_modules/ms-rest-azure/node_modules/adal-node/lib/util.js:130:7)
      at Request.self.callback (/home/olleplus/lab/thundr-auth-server/node_modules/request/request.js:185:22)
      at Request.emit (events.js:400:28)
      at Request.<anonymous> (/home/olleplus/lab/thundr-auth-server/node_modules/request/request.js:1154:10)
      at Request.emit (events.js:400:28),
  deviceCode: 'DQ36XF3ZB'
}

### MSAL Configuration

```javascript
Not relevant
```

### Relevant Code Snippets

```javascript
This errors occurs during a simple call to `interactiveLogin()` from `ms-rest-azure` library.
```

### Reproduction Steps

Call `interactiveLogin()`, then the error occurs when trying to log in with some Azure accounts (common factor was they had only 1 subscription in it).

This error never occured with MS-owned accounts, only on personal MS account with MSDN or regular subscriptions.

### Expected Behavior

The library should not crash.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@sinedied Have you considered upgrading to `@azure/identity`? It uses MSAL Node under the hood,  and is actively maintained (whereas `ms-rest-azure` and `adal-node` are not).

https://www.npmjs.com/package/@azure/identity
