### ISSUE TITLE
Can not open https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

### ISSUE THREAD

**Issue by xiaolang124** [AzureAD/microsoft-authentication-library-for-js#4329]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Can not open https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration, so I can not get login url from pca or open https://teams.microsoft.com/.

![Uploading image.png…]()

### Error Message

{
"error": "server_error",
"error_description": "AADSTS90041: A transient error has occurred. Please try again.\r\nTrace ID: 021057ef-ac36-42da-9d58-6a2014280000\r\nCorrelation ID: 3f55a7af-b630-4a6f-8999-8df31c1981a9\r\nTimestamp: 2021-12-16 01:52:37Z",
"error_codes": [
90041
],
"timestamp": "2021-12-16 01:52:37Z",
"trace_id": "021057ef-ac36-42da-9d58-6a2014280000",
"correlation_id": "3f55a7af-b630-4a6f-8999-8df31c1981a9"
}

### Msal Logs

stack trace: ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
	at ClientAuthError.AuthError [as constructor] (/home/xiaolang/TeamsFx/packages/vscode-extension/node_modules/@azure/msal-common/dist/index.cjs.js:449:24)
	at new ClientAuthError (/home/xiaolang/TeamsFx/packages/vscode-extension/node_modules/@azure/msal-common/dist/index.cjs.js:701:28)
	at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (/home/xiaolang/TeamsFx/packages/vscode-extension/node_modules/@azure/msal-common/dist/index.cjs.js:738:16)
	at Function.<anonymous> (/home/xiaolang/TeamsFx/packages/vscode-extension/node_modules/@azure/msal-common/dist/index.cjs.js:6703:47)
	at step (/home/xiaolang/TeamsFx/packages/vscode-extension/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
	at Object.throw (/home/xiaolang/TeamsFx/packages/vscode-extension/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
	at rejected (/home/xiaolang/TeamsFx/packages/vscode-extension/node_modules/@azure/msal-common/dist/index.cjs.js:51:65)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

### MSAL Configuration

```javascript
const config = {
  auth: {
    clientId: "7ea7c24c-b1f6-4a20-9d11-9ae12e9e7ac0",
    authority: "https://login.microsoftonline.com/common",
  },
  system: {
    loggerOptions: {
      // @ts-ignore
      loggerCallback(loglevel, message, containsPii) {
        if (loglevel <= LogLevel.Error) {
          VsCodeLogInstance.error(message);
        }
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Error,
    },
  },
  cache: {
    cachePlugin,
  },
};
```

### Relevant Code Snippets

```javascript
this.pca!.getAuthCodeUrl(authCodeUrlParameters).then(async (response: string) => {
        vscode.env.openExternal(vscode.Uri.parse(response));
      });
```

### Reproduction Steps

Can not get AuthCodeUrl

### Expected Behavior

Get authCodeUrl

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

Internal (Microsoft)

**Comment by xiaolang124** [comment]
Can not reproduce, I think this is fixed. Thanks.
