### ISSUE TITLE
[msal-node] ClientAuthError: network_error: Network request failed.

### ISSUE THREAD

**Issue by san-goyal** [AzureAD/microsoft-authentication-library-for-js#4372]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.5.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0.0

### Description

@azure/msal-node library throws error intermittently while retrieving access token using client credential code auth.

### Error Message

```
Exception while executing function: Functions.QueueTriggerFunction Result: Failure
Exception: ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: connect ETIMEDOUT 20.190.159.132:443 | Attempted to reach: https://login.microsoftonline.com/<<tenantid>>/oauth2/v2.0/token

```

### Msal Logs

```
Stack: ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: connect ETIMEDOUT 20.190.159.132:443 | Attempted to reach: https://login.microsoftonline.com/<<tenantid>>/oauth2/v2.0/token
at ClientAuthError.AuthError [as constructor] (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:477:24)
at new ClientAuthError (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:729:28)
at Function.ClientAuthError.createNetworkError (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:772:16)
at NetworkManager.<anonymous> (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:3049:51)
at step (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:79:23)
at Object.throw (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:60:53)
at rejected (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:51:65)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### MSAL Configuration

```javascript
auth: {
                clientId: <<client id>>,
                authority: "https://login.microsoftonline.com/<<tenantID>>/",
                clientSecret: <<client secret>>,
                knownAuthorities: ["https://login.microsoftonline.com/<<tenantID>>/"]
            }
```

### Relevant Code Snippets

```javascript
const msal = require('@azure/msal-node');
        const config = {
            auth: {
                clientId: <<client id>>,
                authority: "https://login.microsoftonline.com/<<tenantID>>/",
                clientSecret: <<client secret>>,
                knownAuthorities: ["https://login.microsoftonline.com/<<tenantID>>/"]
            },
            system: {
                loggerOptions: {
                    loggerCallback(loglevel, message, containsPii) {
                        console.log(message);
                    },
                    piiLoggingEnabled: false,
                    logLevel: msal.LogLevel.Error,
                }
            }
        };
    
        const cca = new msal.ConfidentialClientApplication(config);
        const clientCredentialRequest = {
            scopes: ["https://graph.microsoft.com/.default"],
        };
        cca.acquireTokenByClientCredential(clientCredentialRequest).then((response) => {
            resolve(response.accessToken);
        }).catch((error) => {
            console.log(JSON.stringify(error));
            reject(error);
        })       
```
```


### Reproduction Steps

Above code snippets intermittently fails to return access token. Failure rate is almost ~10% out of thousands calls.

### Expected Behavior

Access token should be returned every time.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

_No response_

### Source

External (Customer)

**Comment by tnorling** [comment]
@san-goyal This error is thrown because the fetch call to the /token endpoint timed out. It suggests there's a network connection issue between your machine and the /token endpoint which could be due to many reasons. There's unfortunately not a whole lot we can do to help you debug this as it's not so much an issue with the library as an issue with your environment. If you're making thousands of calls it is possible you're getting throttled by the server does this still happen when making fewer calls?

**Comment by san-goyal** [comment]
@tnorling  - thank you for your response.

Yes, i have seen many instances where /token endpoints works with higher number of requests but sometimes not.

Setup is plain azure function running on azure tenant without any network layer involvement. I don't find any throttling limit shared by Microsoft for /token endpoint.

**Comment by tnorling** [comment]
> Yes, i have seen many instances where /token endpoints works with higher number of requests but sometimes not.

Does it work more consistently with _fewer_ requests?
