### ISSUE TITLE
TypeError: tslib_1.__spreadArray is not a function with msal 1.4.16

### ISSUE THREAD

**Issue by tsulli** [AzureAD/microsoft-authentication-library-for-js#4541]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.16

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

msal 1.4.16 uses tslib ^1.9.3, but TelemetryManger.ts uses __spreadArray that is only available in tslib ^2.1.0

I have tried adding an upgraded version of tslib to my build but it does not resolve the issue. Deleting node_modules and jspm_packages and reinstalling also does not resolve the issue.

msal 1.4.16 and msal 1.4.12 
tslib 1.14.1
Typescript 3.83 and Typescript 3.9.2

Is my only option to upgrade to msal 2.x (and all the work that entails) or is there another solution?

### Error Message

TypeError: tslib_1.__spreadArray is not a function
    at new ServerRequestParameters (<mylocalpath>\wwwroot\jspm_packages\npm\msal@1.4.16\src\serverrequestparameters.ts:63:31)
    at UserAgentApplication.eval (<mylocalpath>\wwwroot\jspm_packages\npm\msal@1.4.16\src\useragentapplication.ts:743:49)
    at step (<mylocalpath>\wwwroot\jspm_packages\npm\tslib@1.14.1\tslib.js:143:28)
    at Object.eval [as next] (<mylocalpath>\wwwroot\jspm_packages\npm\tslib@1.14.1\tslib.js:124:58)
    at eval (<mylocalpath>\wwwroot\jspm_packages\npm\tslib@1.14.1\tslib.js:117:76)
    at new Promise (<anonymous>)
    at Object.__awaiter (<mylocalpath>\wwwroot\jspm_packages\npm\tslib@1.14.1\tslib.js:113:17)
    at eval (<mylocalpath>\wwwroot\jspm_packages\npm\msal@1.4.16\src\useragentapplication.ts:710:64)
    at new Promise (<anonymous>)
    at UserAgentApplication.acquireTokenSilent (<mylocalpath>\wwwroot\jspm_packages\npm\msal@1.4.16\src\useragentapplication.ts:710:16)

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

N/A

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@tsulli Unfortunately, msal 1.x is only receiving critical security fixes at this point. Unless you are able to use an upgraded version of tslib, our recommendation would be to use the @azure/msal-browser library instead.

**Comment by tsulli** [comment]
> 

Thanks. We had upgrading to msal 2.x in the backlog and this pushed it straight to the top of the queue. I managed to get everything upgraded and mostly working now.
