### ISSUE TITLE
Error when using: import msal from "@azure/msal-node"

### ISSUE THREAD

**Issue by jamesdruhan** [AzureAD/microsoft-authentication-library-for-js#4588]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.7.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When using the import statement for msal-node, all types and interfaces are available but upon compilation msal is undefined.

If I use the require statement then I don't get the importation of the types.

### Error Message

```shell
server-web  | /app/src/routes/Login.ts:85
server-web  |                                   logLevel          : msal.LogLevel.Verbose
server-web  |                               ^
server-web  | TypeError: Cannot read properties of undefined (reading 'LogLevel')
server-web  |     at new Login (/app/src/routes/Login.ts:85:31)
server-web  |     at Object.<anonymous> (/app/src/index.ts:82:16)
server-web  |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
server-web  |     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1475:23)
server-web  |     at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
server-web  |     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1478:12)
server-web  |     at Module.load (node:internal/modules/cjs/loader:981:32)
server-web  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
server-web  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
server-web  |     at node:internal/main/run_main_module:17:47
server-web  | [nodemon] app crashed - waiting for file changes before starting...
```

If I implicitly assign the LogLevel then it just triggers the next error...

```shell
server-web  | [nodemon] starting `node -r ts-node/register --inspect=0.0.0.0:9229 ./src/index.ts`
server-web  | Debugger listening on ws://0.0.0.0:9229/c8860d59-2b53-40dc-8cd6-dd64935864ff
server-web  | For help, see: https://nodejs.org/en/docs/inspector
server-web  | /app/src/routes/Login.ts:91
server-web  |           this.msalClientApp = new msal.ConfidentialClientApplication( this.msalConfig );
server-web  |                                 ^
server-web  | TypeError: Cannot read properties of undefined (reading 'ConfidentialClientApplication')
server-web  |     at new Login (/app/src/routes/Login.ts:91:33)
server-web  |     at Object.<anonymous> (/app/src/index.ts:82:16)
server-web  |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
server-web  |     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1475:23)
server-web  |     at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
server-web  |     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1478:12)
server-web  |     at Module.load (node:internal/modules/cjs/loader:981:32)
server-web  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
server-web  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
server-web  |     at node:internal/main/run_main_module:17:47
server-web  | [nodemon] app crashed - waiting for file changes before starting...
```

### Msal Logs

N/A

### MSAL Configuration

```javascript
this.msalConfig =
{
	auth :
	{
		clientId     : env.AUTH_APP_ID,
		authority    : `https://login.microsoftonline.com/${ env.AUTH_TENANT_ID }/`,
				clientSecret : env.AUTH_CLIENT_SECRET,
	},
	system :
	{
		loggerOptions :
		{
			loggerCallback    : this.log,
			piiLoggingEnabled : true,
			logLevel          : msal.LogLevel.Verbose
		}
	}
};
```

### Relevant Code Snippets

```javascript
// Application Imports
import { IRoute } from "./IRoute";
import { Environment } from "../config/Environment";
import { Logger } from "../lib/logger/Logger";

// Node Module Imports
import express from "express";
import msal from "@azure/msal-node";

// Get environment variables.
const env : Environment = new Environment();

// Create logger.
const appLog : Logger = new Logger();

/**
 * Redirects user to login to Azure Identity.
 */
export class Login implements IRoute
{
	/**
	 * Express router object.
	 * 
	 * @type { express.Router }
	 */
	 public route : express.Router;

	/**
	 * Path of the route.
	 * 
	 * @type { string }
	 */
	 public path : string;

	/**
	 * Configuration object for MSAL
	 * 
	 * @type { msal.Configuration }
	 */
	 protected msalConfig : any;

	/**
	 * MSAL confidential client application object.
	 * 
	 * @type { msal.Configuration }
	 */
	 protected msalClientApp : any;

	/**
	 * @class Configures Login route.
	 * @constructs Login
	 * 
	 * @example
	 * import { Login } from "./routes/Login";
         * 
         * appServer.use( new Login().route );
	 * 
	 * @returns { Login } - Object of the Login class.
	 */
	constructor ()
	{
		// Set configuration.
		this.msalConfig =
		{
			auth :
			{
				clientId     : env.AUTH_APP_ID,
				authority    : `https://login.microsoftonline.com/${ env.AUTH_TENANT_ID }/`,
				clientSecret : env.AUTH_CLIENT_SECRET,
			},
			system :
			{
				loggerOptions :
				{
					loggerCallback    : this.log,
					piiLoggingEnabled : true,
					logLevel          : msal.LogLevel.Verbose
				}
			}
		};

		// Initialize MSAL client application.
		this.msalClientApp = new msal.ConfidentialClientApplication( this.msalConfig );

        this.path  = env.AUTH_PATH_LOGIN;
        this.route = express.Router().get( this.path, this.task );
    }

	/**
	 * The task(s) that are performed when the route is hit.
	 * 
	 * @param req - Request object.
	 * @param res - Response object.
	 */
	public async task ( req : express.Request, res : express.Response ) : Promise<void>
	{
		const authCodeUrlParameters : any =
		{
			scopes      : ["user.read"],
			redirectUri : env.AUTH_PATH_REDIRECT,
		};

		try
		{
			// Request the redirection URL for user login.
			const response = await this.msalClientApp.getAuthCodeUrl( authCodeUrlParameters );

			// Redirect the user.
			res.redirect( response );
		}
		catch ( err )
		{
			req.cookies.pageError = JSON.stringify( err );

			// Redirect to error page.
			res.redirect( '/error.html' );
		}
	}

	/**
	 * Logs a MSAL event.
	 * 
	 * @param level - Log message level.
	 * @param message - Message to be logged.
	 * @param pii - Flag indicating if personal information is included.
	 * 
	 */
	 protected log ( level : any, message : string, pii : boolean ) : void
	 {
		appLog.asInfo( `[${ msal.LogLevel[ level ] }] ${ message }` );
	 }
}
```

### Reproduction Steps

1. Use import statement:

`import msal from "@azure/msal-node";`

2. Write any MSAL code.

### Expected Behavior

```
// Request the redirection URL for user login.
const response = await this.msalClientApp.getAuthCodeUrl( authCodeUrlParameters );
```

The above should return a promise.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by mpminayo** [comment]
How are you installing your package?

**Comment by jamesdruhan** [comment]
I'm using **npm install --save @azure/msal-node**

Here is my package.json:

```json
    "devDependencies": {
        "@types/compression": "^1.7.2",
        "@types/cookie-session": "2.0.44",
        "@types/cors": "2.8.12",
        "@types/express": "4.17.13",
        "@types/morgan": "1.9.3",
        "@types/node": "17.0.21",
        "nodemon": "2.0.15",
        "ts-node": "10.6.0",
        "typescript": "4.6.2"
    },
    "dependencies": {
        "@azure/msal-node": "1.7.0",
        "axios": "0.26.0",
        "body-parser": "1.19.2",
        "compression": "1.7.4",
        "cookie-session": "2.0.0",
        "cors": "2.8.5",
        "csrf": "3.1.0",
        "express": "4.17.3",
        "fs-extra": "10.0.1",
        "helmet": "5.0.2",
        "moment-timezone": "0.5.34",
        "morgan": "1.10.0",
        "validator": "13.7.0",
        "winston": "3.6.0"
    }
```

**Comment by mpminayo** [comment]
Could you check if @azure/msal-node has been installed in the node modules?

**Comment by jamesdruhan** [comment]
It was indeed installed OK.

It appears the solution is to import in this fashion:
```js
import * as msal from "@azure/msal-node";
```

However, It's strange as when I use the normal **import msal from "@azure/msal-node";** VSCode recognizes and validates everything without issue. I only get the error when I compile.

**Comment by samuelkubai** [comment]
I agree @jamesdruhan, that's very strange.

I will go ahead and close the issue for now, as we have found a resolution but feel free to reopen the issue if the problem persists.

**Comment by simmondsty** [comment]
Still an issue, the workaround still works but it's a pain to find this issue in the git.

**Comment by falkzach** [comment]
Ran into this recently with [@azure/msal-react](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react), turned out to be a bad `package-lock.json` file. Hope this helps if anyone else lands here from `npm ci` sudenly failing.
