### ISSUE TITLE
"Interaction in progress" state is not reset when logging out of a specific account in the local logout scenario

### ISSUE THREAD

**Issue by sebrenna** [AzureAD/microsoft-authentication-library-for-js#4697]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Description

Performing a local-only logout with a specific account leaves MSAL in the "interaction in progress" state even after the operation completes. This results in errors when other interactive operations are started, such as a subsequent login. This _does not_ happen if _no account is specified_ on logout.

**Workaround:** since this doesn't happen if the account option is omitted from the logout request, and since our app only allows one account to be logged in at a time, omitting the account option is an acceptable workaround for us at the moment.

### Error Message

```json
{
    "errorCode": "interaction_in_progress",
    "errorMessage": "Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.",
    "subError": "",
    "name": "BrowserAuthError"
}
```

```
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/error/AuthError.ts:45:1)
    at new BrowserAuthError (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/error/BrowserAuthError.ts:167:1)
    at Function.BrowserAuthError.createInteractionInProgressError (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/error/BrowserAuthError.ts:248:1)
    at BrowserCacheManager.setInteractionInProgress (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/cache/BrowserCacheManager.ts:916:1)
    at PublicClientApplication.ClientApplication.preflightInteractiveRequest (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/app/ClientApplication.ts:664:1)
    at PublicClientApplication.ClientApplication.preflightBrowserEnvironmentCheck (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/app/ClientApplication.ts:649:1)
    at PublicClientApplication.<anonymous> (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/app/ClientApplication.ts:213:1)
    at step (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9784:17)
    at Object.next (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9715:14)
    at https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9687:67
    at new Promise (<anonymous>)
    at __awaiter (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9666:10)
    at PublicClientApplication.ClientApplication.acquireTokenRedirect (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:10033:79)
    at PublicClientApplication.<anonymous> (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/app/PublicClientApplication.ts:66:1)
    at step (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9784:17)
    at Object.next (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9715:14)
    at https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9687:67
    at new Promise (<anonymous>)
    at __awaiter (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:9666:10)
    at PublicClientApplication.loginRedirect (https://local.portal.fidalgo.azure-test.net:44333/static/js/vendors~main.chunk.js:10914:79)
    at signIn (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/src/data/services/identity.ts:318:1)
    at runCallEffect (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:524:1)
    at runEffect (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1204:1)
    at digestEffect (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1271:1)
    at next (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1161:1)
    at currCb (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1)
    at runCallEffect (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:539:1)
    at runEffect (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1204:1)
    at digestEffect (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1271:1)
    at next (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1161:1)
    at currCb (https://local.portal.fidalgo.azure-test.net:44333/static/js/C:/Source/azure-devtest-center/src/DeveloperPortal/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1)
```

### Msal Logs

```
[Fri, 08 Apr 2022 21:29:51 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:handleRedirectStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:51 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:handleRedirectEnd
identity.ts:228 [Fri, 08 Apr 2022 21:29:51 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:51 GMT] : [2273ea8c-6a4e-4f41-8596-7d4b20c61009] : @azure/msal-common@6.2.0 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
identity.ts:228 [Fri, 08 Apr 2022 21:29:51 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:52 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : [1d309c80-46dd-4adc-907d-3836cb962e51] : @azure/msal-common@6.2.0 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
identity.ts:228 [Fri, 08 Apr 2022 21:29:54 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:55 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:56 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:56 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:29:57 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenStart
identity.ts:228 [Fri, 08 Apr 2022 21:29:57 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:acquireTokenSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:30:09 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:logoutStart
identity.ts:228 [Fri, 08 Apr 2022 21:30:09 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:logoutSuccess
identity.ts:228 [Fri, 08 Apr 2022 21:30:09 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:logoutEnd
```

### MSAL Configuration

```javascript
{
    "auth": {
        "authority": "https://login.microsoftonline.com/common",
        "clientId": "0140a36d-95e1-4df5-918c-ca7ccd1fafc9",
        "navigateToLoginRequestUrl": true,
        "postLogoutRedirectUri": "https://local.portal.fidalgo.azure-test.net:44333/",
        "redirectUri": "https://local.portal.fidalgo.azure-test.net:44333/signin"
    },
    "cache": {
        "cacheLocation": "localStorage",
        "storeAuthStateInCookie": false
    }
}
```

### Relevant Code Snippets

```javascript
export const signIn = async (options?: Partial<RedirectRequest>): Promise<void> => {
    if (!isInitialized) {
        throw new ClientError('Identity module must be initialized before use.');
    }

    if (application === undefined) {
        throw new ClientError('Unexpected state: Identity module is initialized, but application is not defined.');
    }

    try {
        const account = getActiveAccount();
        const authority = getAuthority(account?.tenantId);
        // Note: account is for login hints. Scenario: user is trying to sign into another tenant w/ same account
        const loginRequest: RedirectRequest = { ...defaultLoginRequest, account, authority, ...(options || {}) };

        await application.loginRedirect(loginRequest);
    } catch (error) {
        throw new ClientError(error);
    }
};

export const signOut = async (skipServerSignOut = false, options?: Partial<EndSessionRequest>): Promise<void> => {
    if (!isInitialized) {
        throw new ClientError('Identity module must be initialized before use.');
    }

    if (application === undefined) {
        throw new ClientError('Unexpected state: Identity module is initialized, but application is not defined.');
    }

    try {
        const account = getActiveAccount();
        const authority = getAuthority(account?.tenantId);
        const logoutRequest: EndSessionRequest = {
            authority,
            account,
            // Having onRedirectNavigate return false will only sign out the user locally
            ...(skipServerSignOut ? { onRedirectNavigate: (_url) => false } : {}),
            ...(options || {}),
        };

        await application.logoutRedirect(logoutRequest);
    } catch (error) {
        throw new ClientError(error);
    }
};

signOut(true);

// Error is thrown on this call
signIn({
    account: ...,
    authority: ...,
    redirectStartPage: ...,
});
```

### Reproduction Steps

1. Sign into your app using the redirect workflow.
2. In the redirect completion handler, set the active account to the account received in the redirection response.
3. Sign out of the app using the redirect workflow with the following request details:
    * `account`: current value of `application.getActiveAccount()`
    * `onRedirectNavigate`: set to a handler that returns false. This will skip redirection and only sign out the user within the browser.
4. Sign into the app again using redirect workflow.

### Expected Behavior

MSAL should allow login to happen after logout exits successfully.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@sebrenna Thanks, I can confirm this is a bug. Will follow up if I have any further questions.

**Comment by jasonnutter** [comment]
For anyone else experiencing this bug, refreshing the page after invoking `logout/logoutRedirect` (with an account passed and `onRedirectNavigate` set to return `false`) should result in the interaction status temporary cache entry to be cleared,

**Comment by eglavin** [comment]
I'm also seeing this since updating to version "@azure/msal-browser": "2.22.1"

**Comment by eglavin** [comment]
Ok, I can reproduce this issue back as far as v2.22.0 as soon as i downgrade to v2.21.0 I'm able to sign out and continue using the login again after.
