### ISSUE TITLE
InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in

### ISSUE THREAD

**Issue by gitmurali** [AzureAD/microsoft-authentication-library-for-js#4741]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

Here's the bit of code that I was working on. I am using MSAL for two SSO apps on same domain for example https://some-domain.com/app1 and https://some-domain.com/app2 and please see the code snippet below.

App 1 seems to be fine it allows user to sign in correctly.However, on app2 when I reload the page it throws an error

MSAL: InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.

I have used instance.acquireTokenRedirect,acquireTokenSilent and identityInstance.loginRedirect() but nothing seemed to work. Any ideas please share. Thanks.

### Error Message

MSAL: InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.

### Msal Logs

InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.
    at InteractionRequiredAuthError.AuthError [as constructor] (webpack-internal:///./node_modules/@azure/msal-common/dist/error/AuthError.js:34:24)
    at new InteractionRequiredAuthError (webpack-internal:///./node_modules/@azure/msal-common/dist/error/InteractionRequiredAuthError.js:49:28)
    at Function.InteractionRequiredAuthError.createNoTokensFoundError (webpack-internal:///./node_modules/@azure/msal-common/dist/error/InteractionRequiredAuthError.js:72:16)
    at RefreshTokenClient.eval (webpack-internal:///./node_modules/@azure/msal-common/dist/client/RefreshTokenClient.js:118:124)
    at step (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:83:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:64:53)
    at eval (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:57:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:53:12)
    at RefreshTokenClient.acquireTokenWithCachedRefreshToken (webpack-internal:///./node_modules/@azure/msal-common/dist/client/RefreshTokenClient.js:112:76)
    at RefreshTokenClient.eval (webpack-internal:///./node_modules/@azure/msal-common/dist/client/RefreshTokenClient.js:103:44)
    at step (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:83:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:64:53)
    at eval (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:57:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/@azure/msal-common/dist/_virtual/_tslib.js:53:12)
    at RefreshTokenClient.acquireTokenByRefreshToken (webpack-internal:///./node_modules/@azure/msal-common/dist/client/RefreshTokenClient.js:72:76)
    at SilentRefreshClient.eval (webpack-internal:///./node_modules/@azure/msal-browser/dist/interaction_client/SilentRefreshClient.js:48:66)
    at step (webpack-internal:///./node_modules/@azure/msal-browser/dist/_virtual/_tslib.js:84:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/@azure/msal-browser/dist/_virtual/_tslib.js:65:53)
    at fulfilled (webpack-internal:///./node_modules/@azure/msal-browser/dist/_virtual/_tslib.js:55:58)

### MSAL Configuration

```javascript
looks something like below but can't share the actual config. 

const identityConfig = {
  clientId: 'abc-xyz-123'
  authority: 'blah blah blah'
  knownAuthorities: ['blah blah blah'], // Mark your B2C tenant's domain as trusted.
  redirectUri: 'http://localhost',
  navigateToLoginRequestUrl: false,
  scopes: ['user.read']
}
```

### Relevant Code Snippets

```javascript
const [userName, setUsername] = useState<string | undefined>()

useEffect(() => {
const fetchDetaiils = async () => {
      if (inProgress === InteractionStatus.None) {
        try {
          const signedInUser = identityInstance.getAllAccounts()[0]
          const resp = await identityInstance.acquireTokenSilent({
            scopes: ['user.read'],
            account,
          })
          const token: Token = resp?.idTokenClaims
          setUsername(token.email)
        } catch (err: unknown) {
          if (err instanceof Error) {
            console.log(err)
            if (err?.name === 'InteractionRequiredAuthError') {
              // await instance.acquireTokenRedirect(loginRequest)
            }
          }
        }
      }
    }

    fetchDetaiils()
```

### Reproduction Steps

1. login to app1 
2. refresh the app2 
3. it should automatically get the login information but it's throwing error 

### Expected Behavior

it should allow login into two sso apps according to this https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#sso-between-apps

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by hectormmg** [comment]
@gitmurali thanks for opening the issue.

As described in the docs you referenced, SSO between apps requires the use of either `login_hint` or `sid` (session ID) in the silent request. Please try to use one of these options as described in the doc.

Out of curiosity, what does the `getAllAccounts` API return on app 2? Given that the MSAL cache storage is separated by domain (i.e. app 2 doesn't have access to app 1's token cache and vice-versa), I would expect that the account object returned is `null` , which means aquireTokenSilent has no reference for SSO.

**Comment by gitmurali** [comment]
@hectormmg from the documentation it looks like both `login_hint` and `sid` are JWT but it doesn't mention which specific `JWT` to use. Can you please highlight which `JWT` `token` to be used ?

`getAllAccounts()` method returned `account` in an `array` and I sent the `account` in the `acquireTokenSilent` call. But, I think the way I'm sending might be wrong. Let me give a try on that and get back here.

**Comment by hectormmg** [comment]
@gitmurali `login_hint` and `sid` are actually claims that you can read out of an ID token, they are not JSON Web Tokens themselves. Both of these claims are actually strings when they are present in the ID token (some ID Token claims have to be opted-into in the client application registration).

**Comment by gitmurali** [comment]
@hectormmg What I get from my `idToken` is the following and I don't see `sid` or `login_hint` in the list of props. 
I have removed actual values for sake of security but from the below list of props do you think any of prop is actually a `sid` or a `login_hint` ?

```
{
   nbf": 1652394472,
  "ver": "1.0",
  "iss": "https://blah-blah-blah/v2.0/",
  "sub": "x-x-x",
  "aud": "x-x-x",
  "nonce": "x-x-x",
  "iat": 1631065482,
  "auth_time": 1651021480,
  "email": "123@xyz.com",
  "extension_MFAEnabled": false,
  "MFA_Methods": "null-null",
  "tfp": "x-x-x",
  "correlationId": "x-x-x"
  }
```

**Comment by gitmurali** [comment]
also I see parameter type of `acquireTokenSilent(silentRequest: SilentRequest)` method is `SilentRequest` which doesn't have `sid` or `login_hint`. See below 


```
export declare type SilentRequest = Omit<CommonSilentFlowRequest, "authority" | "correlationId" | "forceRefresh" | "account" | "requestedClaimsHash"> & {
    redirectUri?: string;
    extraQueryParameters?: StringDict;
    authority?: string;
    account?: AccountInfo;
    correlationId?: string;
    forceRefresh?: boolean;
};
```

**Comment by gitmurali** [comment]
@hectormmg this solved my problem https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md in Firefox or other browsers but Chrome is throwing errors.

**Comment by hectormmg** [comment]
@gitmurali did you use the `ssoSilent` API? That would be the recommended approach for this scenario. 

I apologize, I thought `acquireTokenSilent` could also use login_hint and sid to behave like `ssoSilent`, but I was mistaken. We're discussing possible changes to make acquireTokenSilent handle this scenario better, will update the issue and post a pull request when it's ready.

**Comment by gitmurali** [comment]
@hectormmg I have used `ssoSilent` which fixed the problem. Please can this document be updated https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#sso-between-apps as it's misleading. Thanks.

**Comment by hectormmg** [comment]
@gitmurali we'll look into updating the SSO docs since although technically correct, they may be misleading. Closing the issue since using ssoSilent fixed your problem.
