### ISSUE TITLE
The provided authority is not a trusted authority

### ISSUE THREAD

**Issue by binarydmon** [AzureAD/microsoft-authentication-library-for-js#5046]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

In our Kibana logs the following error occurs very often:

Uncaught (in promise): ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
at t [as constructor] (webpack:///node_modules/@azure/msal-common/dist/error/AuthError.js:27:23)
at new t (webpack:///node_modules/@azure/msal-common/dist/error/ClientAuthError.js:194:27)
at Function.t.createEndpointDiscoveryIncompleteError (webpack:///node_modules/@azure/msal-common/dist/error/ClientAuthError.js:231:15)
at Function.<anonymous> (webpack:///node_modules/@azure/msal-common/dist/authority/AuthorityFactory.js:42:30)
at webpack:///node_modules/@azure/msal-common/dist/_virtual/_tslib.js:75:22
at Object.throw (webpack:///node_modules/@azure/msal-common/dist/_virtual/_tslib.js:56:57)
at s (webpack:///node_modules/@azure/msal-common/dist/_virtual/_tslib.js:47:65)
at l.invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
at Object.onInvoke (webpack:///node_modules/@angular/core/_ivy_ngcc_/fesm2015/core.js:28674:32)
at l.invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)

I can't seem to reproduce this on any of my accounts, it happens for a lot of different users in production.

### Error Message

Uncaught (in promise): ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
at t [as constructor] (webpack:///node_modules/@azure/msal-common/dist/error/AuthError.js:27:23)
at new t (webpack:///node_modules/@azure/msal-common/dist/error/ClientAuthError.js:194:27)
at Function.t.createEndpointDiscoveryIncompleteError (webpack:///node_modules/@azure/msal-common/dist/error/ClientAuthError.js:231:15)
at Function.<anonymous> (webpack:///node_modules/@azure/msal-common/dist/authority/AuthorityFactory.js:42:30)
at webpack:///node_modules/@azure/msal-common/dist/_virtual/_tslib.js:75:22
at Object.throw (webpack:///node_modules/@azure/msal-common/dist/_virtual/_tslib.js:56:57)
at s (webpack:///node_modules/@azure/msal-common/dist/_virtual/_tslib.js:47:65)
at l.invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
at Object.onInvoke (webpack:///node_modules/@angular/core/_ivy_ngcc_/fesm2015/core.js:28674:32)
at l.invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)

### MSAL Configuration

```javascript
msal: {
    scopes: [...],
    config: {
      auth: {
        authority: 'https://login.microsoftonline.com/<our-tenant>.onmicrosoft.com',
        clientId: '7e20f2ad-...-43a3-bdab-...',
        redirectUri: 'https://..../auth',
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
      },
      system: {
        loadFrameTimeout: 30000,
      },
    },
    interceptorConfig: {
      interactionType: InteractionType.Redirect,
      protectedResourceMap: new Map([
        ['https://....', null],
        ['https://....', [...]],
        ['https://a.....com', [...]],
      ]),
    },
    guardConfig: {
      interactionType: InteractionType.Redirect,
      loginFailedRoute: '/login-failed',
      authRequest: {
        scopes: [...],
      },
    },
  },
```

### Relevant Code Snippets

```javascript
/
```

### Reproduction Steps

???

### Expected Behavior

The error does not occur

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@binarydmon This could be due to network connectivity issues. Please let us know when you have a reproduction.

**Comment by binarydmon** [comment]
@jasonnutter could it be related to the old msal version (2.0.4)? 

We haven't had any users complaining about this issue, but we do see a lot of occurrences for the past month (thousands). The userbase is about 15 000.

**Comment by jasonnutter** [comment]
@binarydmon You can try updating the latest versions of MSAL Browser and MSAL Angular and see if that helps. Also, I'd be curious if the format of your authority configuration option makes any difference (i.e. try `https://login.microsoftonline.com/<tenant-id>`).

**Comment by bmahall** [comment]
@binarydmon Any updates?
