### ISSUE TITLE
Resources unprotected with wildcards don't work

### ISSUE THREAD

**Issue by fralejanro** [AzureAD/microsoft-authentication-library-for-js#5166]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.2.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I have a route `/reports/*` in which all the resources are protected except one` /reports/public/*`, when trying to indicate that the resource is unprotected using wildcards, it does not work since it is still trying to obtain tokens. The first time I enter the page from where I call my API I get a ClientConfigurationError and the second time I get a BrowserAuthError. It should be clarified that the page from where I call my API is public, so a login has not been registered, when logging in with a registered user the resource is unprotected.

### Error Message

```
core.js:6456 ERROR Error: Uncaught (in promise): ClientConfigurationError: empty_url_error: URL was empty or null.
ClientConfigurationError: empty_url_error: URL was empty or null.
    at ClientConfigurationError.AuthError [as constructor] (vendor.js:112810:24)
    at ClientConfigurationError.ClientAuthError [as constructor] (vendor.js:113052:28)
    at new ClientConfigurationError (vendor.js:113448:28)
    at ClientConfigurationError.createUrlEmptyError (vendor.js:113490:16)
    at AuthorityFactory.createInstance (vendor.js:109108:108)
    at Function.<anonymous> (vendor.js:109079:66)
    at step (vendor.js:108228:23)
    at Object.next (vendor.js:108209:53)
    at vendor.js:108202:71
    at new ZoneAwarePromise (polyfills.js:11704:29)
    at resolvePromise (polyfills.js:11530:31)
    at polyfills.js:11437:17
    at polyfills.js:11453:33
    at ZoneDelegate.invoke (polyfills.js:10689:26)
    at Object.onInvoke (vendor.js:56337:33)
    at ZoneDelegate.invoke (polyfills.js:10688:52)
    at Zone.run (polyfills.js:10451:43)
    at polyfills.js:11593:36
    at ZoneDelegate.invokeTask (polyfills.js:10723:31)
    at Object.onInvokeTask (vendor.js:56324:33)
```

```
core.js:6456 ERROR Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (AuthError.js:27:1)
    at new BrowserAuthError (BrowserAuthError.js:169:1)
    at BrowserAuthError.createInteractionInProgressError (BrowserAuthError.js:236:1)
    at BrowserCacheManager.setInteractionInProgress (BrowserCacheManager.js:813:23)
    at ClientApplication.preflightInteractiveRequest (ClientApplication.js:603:29)
    at ClientApplication.preflightBrowserEnvironmentCheck (ClientApplication.js:590:18)
    at PublicClientApplication.<anonymous> (ClientApplication.js:161:22)
    at step (_tslib.js:75:1)
    at Object.next (_tslib.js:56:45)
    at _tslib.js:49:1
    at resolvePromise (zone.js:1213:1)
    at new ZoneAwarePromise (zone.js:1390:1)
    at __awaiter (_tslib.js:45:1)
    at ClientApplication.acquireTokenRedirect (ClientApplication.js:155:25)
    at MsalService.acquireTokenRedirect (azure-msal-angular.js:42:20)
    at MsalInterceptor.acquireTokenInteractively (azure-msal-angular.js:390:1)
    at CatchSubscriber.selector (azure-msal-angular.js:362:1)
    at CatchSubscriber.error (catchError.js:27:1)
    at subscribeToPromise.js:8:6
```

### MSAL Configuration

```javascript
import {InjectionToken, NgModule, APP_INITIALIZER} from '@angular/core';
import {
  IPublicClientApplication, PublicClientApplication,
  LogLevel, InteractionType
} from '@azure/msal-browser';
import {
  MsalGuard, MsalInterceptor, MsalBroadcastService,
  MsalInterceptorConfiguration, MsalModule, MsalService,
  MSAL_GUARD_CONFIG, MSAL_INSTANCE, MSAL_INTERCEPTOR_CONFIG,
  MsalGuardConfiguration
} from '@azure/msal-angular';
import {HTTP_INTERCEPTORS} from '@angular/common/http';
import {ConfigService} from "./services/config.service";

const AUTH_CONFIG_URL_TOKEN = new InjectionToken<string>('AUTH_CONFIG_URL');
const isIE = window.navigator.userAgent.indexOf("MSIE ") > -1 || window.navigator.userAgent.indexOf("Trident/") > -1; // Remove this line to use Angular Universal

export function initializerFactory(env: ConfigService, configUrl: string): any {
  const promise = env.init(configUrl).then((value) => {
    console.log('finished getting configurations dynamically.');
  });
  return () => promise;
}

export function loggerCallback(logLevel: LogLevel, message: string) {
  console.log(message);
}

export function MSALInstanceFactory(config: ConfigService): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: config.getSettings('clientId'),
      authority: config.getSettings('authority'),
      redirectUri: config.getSettings('redirectUri'),
      postLogoutRedirectUri: config.getSettings('postLogoutRedirectUri')
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: isIE
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(config: ConfigService): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>|null>();
  const apiProtectResourceMap = config.getSettings('protectedResourceMap');
  const services: string [] = [
    '/users/*',
    '/clients/*',
    '/payments/*'
  ]
  protectedResourceMap.set(config.getSettings('APIGraph'), ['user.read']);
  protectedResourceMap.set('/reports/public/*', null);
  protectedResourceMap.set('/reports/*', [apiProtectResourceMap]);
  services.forEach(service => protectedResourceMap.set(service, [apiProtectResourceMap]));
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.read']
    },
    loginFailedRoute: '/login-failed'
  };
}

@NgModule({
  declarations: [],
  imports: [MsalModule]
})
export class ConfigModule {
  static forRoot(configFile: string) {
    return {
      ngModule: ConfigModule,
      providers: [
        ConfigService,
        {provide: AUTH_CONFIG_URL_TOKEN, useValue: configFile},
        {
          provide: APP_INITIALIZER, useFactory: initializerFactory,
          deps: [ConfigService, AUTH_CONFIG_URL_TOKEN], multi: true
        },
        {
          provide: MSAL_INSTANCE,
          useFactory: MSALInstanceFactory,
          deps: [ConfigService]
        },
        {
          provide: MSAL_GUARD_CONFIG,
          useFactory: MSALGuardConfigFactory,
          deps: [ConfigService]
        },
        {
          provide: MSAL_INTERCEPTOR_CONFIG,
          useFactory: MSALInterceptorConfigFactory,
          deps: [ConfigService]
        },
        MsalService,
        MsalGuard,
        MsalBroadcastService,
        {
          provide: HTTP_INTERCEPTORS,
          useClass: MsalInterceptor,
          multi: true
        }
      ]
    };
  }
}
```

### Relevant Code Snippets

```javascript
export function MSALInterceptorConfigFactory(config: ConfigService): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>|null>();
  const apiProtectResourceMap = config.getSettings('protectedResourceMap');
  const services: string [] = [
    '/users/*',
    '/clients/*',
    '/payments/*'
  ]
  protectedResourceMap.set(config.getSettings('APIGraph'), ['user.read']);
  protectedResourceMap.set('/reports/public/*', null);
  protectedResourceMap.set('/reports/*', [apiProtectResourceMap]);
  services.forEach(service => protectedResourceMap.set(service, [apiProtectResourceMap]));
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}
```

### Reproduction Steps

Add an unprotected and a wildcard-protected resource that start with the same name

### Expected Behavior

I hope that for the resources in the url /reports/public/* tokens are not requested regardless of whether I am logged in or not and that for the resources in /reports/* tokens are requested

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by fralejanro** [comment]
After a long read of the documentation, I realized that I had to manually subscribe to handleRedirectObservable since my public routes were obviously not going to be protected by MSAL Guard. After this and a configuration of my routes by lazy loading it worked for me.
