### ISSUE TITLE
Memory Leak Error with MsalAuthenticationTemplate

### ISSUE THREAD

**Issue by svdHero** [AzureAD/microsoft-authentication-library-for-js#5245]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.2

### Public or Confidential Client?

Public

### Description

I have a component that is secured via the React wrapper component [`<MsalAuthenticationTemplate/>`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#msalauthenticationtemplate-component).

Inside this component, I use some async API function to load data via React's `useEffect` hook. I specifically made sure that all actions are canceled in the effect clean-up callback.

However, when I load the component and then unload it before the async function's Promise is resolved, I get the following error in the browser console:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at MsalAuthenticationTemplate (http://localhost:3000/static/js/bundle.js:40504:5)
    at MyProblematicComponent (http://localhost:3000/static/js/bundle.js:5274:28)
```

It seems as if the memory leak layed within `<MsalAuthenticationTemplate/>`. When I remove this wrapper component, the problem goes away.

### Error Message

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at MsalAuthenticationTemplate (http://localhost:3000/static/js/bundle.js:40504:5)
    at MyProblematicComponent (http://localhost:3000/static/js/bundle.js:5274:28)

printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:23914
scheduleUpdateOnFiber @ react-dom.development.js:21840
dispatchAction @ react-dom.development.js:16139
(anonymous) @ useMsalAuthentication.ts:127
Promise.then (async)
(anonymous) @ useMsalAuthentication.ts:126
(anonymous) @ useMsalAuthentication.ts:173
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
```

### Msal Logs

```
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : @azure/msal-browser@2.26.0 : Info - Emitting event: msal:initializeStart
azure-auth-provider.ts:19 Event "msal:initializeStart" received.
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : @azure/msal-browser@2.26.0 : Info - Emitting event: msal:initializeEnd
azure-auth-provider.ts:19 Event "msal:initializeEnd" received.
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : @azure/msal-browser@2.26.0 : Info - Emitting event: msal:handleRedirectStart
azure-auth-provider.ts:19 Event "msal:handleRedirectStart" received.
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : @azure/msal-react@1.4.2 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : [1c55e8ad-ece1-49e6-90b4-8007aa2c986c] : msal.js.browser@2.26.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : @azure/msal-browser@2.26.0 : Info - Emitting event: msal:handleRedirectEnd
azure-auth-provider.ts:19 Event "msal:handleRedirectEnd" received.
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : @azure/msal-react@1.4.2 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:22 GMT] : @azure/msal-react@1.4.2 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:25 GMT] : @azure/msal-react@1.4.2 : Info - useMsalAuthentication - User is authenticated, attempting to acquire token
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:25 GMT] : @azure/msal-browser@2.26.0 : Info - Emitting event: msal:acquireTokenStart
azure-auth-provider.ts:19 Event "msal:acquireTokenStart" received.
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:25 GMT] : @azure/msal-browser@2.26.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart
azure-auth-provider.ts:19 Event "msal:acquireTokenFromNetworkStart" received.
azure-auth-config.ts:86 [Wed, 28 Sep 2022 10:59:27 GMT] : @azure/msal-browser@2.26.0 : Info - Emitting event: msal:acquireTokenSuccess
azure-auth-provider.ts:19 Event "msal:acquireTokenSuccess" received.
azure-auth-provider.ts:55 Handling event "msal:acquireTokenSuccess"...
azure-auth-provider.ts:57 Login successful. Setting account information...
azure-auth-provider.ts:59 Account information set.
azure-auth-provider.ts:60 All accounts: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee-b2c_1a_signup_signin.xxxxxxxx-yyyy-zzzz-dddd-eeeeeeeeeeee
azure-auth-provider.ts:61 Active account: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee-b2c_1a_signup_signin.xxxxxxxx-yyyy-zzzz-dddd-eeeeeeeeeeee
react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at MsalAuthenticationTemplate (http://localhost:3000/static/js/bundle.js:24840:5)
    at MyProblematicComponent (http://localhost:3000/static/js/bundle.js:615:28)
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:23914
scheduleUpdateOnFiber @ react-dom.development.js:21840
dispatchAction @ react-dom.development.js:16139
(anonymous) @ useMsalAuthentication.ts:127
Promise.then (async)
(anonymous) @ useMsalAuthentication.ts:126
(anonymous) @ useMsalAuthentication.ts:173
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
```

### MSAL Configuration

```ts
const ua = window.navigator.userAgent
const msie = ua.indexOf("MSIE ")
const msie11 = ua.indexOf("Trident/")
const msedge = ua.indexOf("Edge/")
const firefox = ua.indexOf("Firefox")
const isIE = msie > 0 || msie11 > 0 // eslint-disable-line @typescript-eslint/no-unused-vars
const isEdge = msedge > 0
 // Only needed if you need to support the redirect flow in Firefox incognito:
const isFirefox = firefox > 0  // eslint-disable-line @typescript-eslint/no-unused-vars


export const msalConfig: Configuration = {
    auth: {
        clientId: process.env.REACT_APP_CLIENT_ID as string,
        authority: b2cConfiguration.policies.signUpSignIn.authority,
        knownAuthorities: [b2cConfiguration.authorityDomain],
        redirectUri: process.env.REACT_APP_REDIRECT_URI as string,
        navigateToLoginRequestUrl: true,
        postLogoutRedirectUri: process.env.REACT_APP_POST_LOGOUT_REDIRECT_URI as string
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: isEdge // Set this to "true" if you are having issues on Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message)
                        return
                    case LogLevel.Info:
                        console.debug(message)
                        return
                    case LogLevel.Verbose:
                        console.debug(message)
                        return
                    case LogLevel.Warning:
                        console.warn(message)
                        return
                }
            }
        }
    }
}
```

### Relevant Code Snippets

```ts
import { InteractionStatus, InteractionType, RedirectRequest } from "@azure/msal-browser"
import { MsalAuthenticationTemplate, useMsal } from "@azure/msal-react"
import { useEffect, useState } from "react"
import { b2cConfiguration } from "../../bt-auth/azure/azure-auth-config"

function useIsAuthInProgress(): boolean {
    const {inProgress} = useMsal()
    return inProgress !== InteractionStatus.None
}

export const loginRequest: RedirectRequest = {
    scopes: [
    ],
    authority: b2cConfiguration.policies.signUpSignIn.authority
}

function getFooFromApi(): Promise<string> {
    const myFooPromise = new Promise<string>((resolve, reject) => {
        setTimeout(() => resolve("My awsome foo"), 5000)
      })
    return myFooPromise
}

export function MyProblematicComponent() {
    const isAuthInProgress = useIsAuthInProgress()
    const [foo, setFoo] = useState<string>("INIT")

    // ####################
    useEffect(() => {
        let isCanceled = false
        if(isAuthInProgress){
            setFoo("LOADING")
        } else {
            setFoo("LOADING")
            getFooFromApi()
            .then(result => {
                if(!isCanceled){
                    setFoo(result)
                }
            })
            .catch(error => {
                if(!isCanceled){
                    console.error(error)
                }
            })
        }
        return () => {isCanceled = true}
    }, [isAuthInProgress])
    // ####################
    return (
        <MsalAuthenticationTemplate authenticationRequest={loginRequest} interactionType={InteractionType.Redirect}>
            <div>
                <p>{foo}</p>
            </div>
        </MsalAuthenticationTemplate>
    )
}

export function MyTestBed() {
    const [showComponent, setShowComponent] = useState<boolean>(false)
    // ####################
    return (
        <div>
            <div>
                <button onClick={() => setShowComponent(!showComponent)}>{showComponent? "unload" : "load"}</button>
            </div>
            <div>
                { showComponent
                    ? <MyProblematicComponent/>
                    : <p>Component not loaded</p>
                }
            </div>
        </div>
    )
}
```

### Reproduction Steps

1. Create an empty App with the component `<MyTestBed/>`.
2. Click on the `load` button.
3. Wait 1 second and click on the `unload` button.
4. Wait 5 seconds.
5. Check the browser console output.

### Expected Behavior

No error in browser console.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by hectormmg** [comment]
@svdHero thanks for bringing this to our attention, I'll investigate as soon as I can.

**Comment by hectormmg** [comment]
@svdHero so from what we can see this isn't an issue with MSAL React, but more of a React restriction. Unmounting a component will not cancel an asynchronous call that has been queued, meaning the app will still attempt to make the state update even if the component is unmounted.

**Comment by svdHero** [comment]
@hectormmg you are absolutely right. That is a React restriction. However, you are missing the point of my problem description. The stacktrace suggests that the problem lies within the React component `MsalAuthenticationTemplate` which is an integral part of MSAL React. So it is, indeed, an issue with MSAL React, unless I am totally mistaken.

In my component I am using the clean-up function `() => {isCanceled = true}` in order to avoid state updates after the component has been unmounted. I assume that inside `MsalAuthenticationTemplate` such a clean-up function is missing somewhere. At least that's what the error message indicates.

**Comment by svdHero** [comment]
Having said that, at first glance I cannot see any `useEffect` in [MsalAuthenticationTemplate.tsx](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/926f1c2ba0598575e23dfd8cdd8b79fa3a3d19ff/lib/msal-react/src/components/MsalAuthenticationTemplate.tsx), but maybe it is hidden in some of the hooks used in `MsalAuthenticationTemplate`?

**Comment by tnorling** [comment]
@svdHero I am not able to reproduce this either with our samples or with the code snippets you shared. Could you please put together a minimal reproduction so that I may investigate in more depth? I have a suspicion that [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/src/hooks/useMsalAuthentication.ts#L127) is the problem, however, I'd like to be able to confirm before making any changes (also so that I can verify the changes actually fix the problem)

**Comment by svdHero** [comment]
@tnorling I am preparing a simple reproduction app. Can I somehow PM you in order to send you the `.env` file with the IDs for our company B2C? Is it okay to write to your Microsoft email address?

**Comment by tnorling** [comment]
You may email me at my Microsoft email. Let's start with just the app, I'll use my own B2C instance and if I still can't get it to repro I'll reach out. In theory if this is a bug in the library the authority should be irrelevant.

**Comment by svdHero** [comment]
Dear msftbot, please leave this open. I am sick atm, but I will provide a repro app on monday.

**Comment by svdHero** [comment]
@tnorling I have added a demo app for reproducing the error. You can find it here:
https://github.com/svdHero/msal-mem-leak-demo-app
It is not as minimal as it could be, as I just stripped down our prod app, but it should be simple enough to focus on the main issue here.

I will send you an email with my .env file, so that you can start straight away with our B2C, create an account and test it.

**Comment by svdHero** [comment]
@tnorling any update on this? Can I provide more information or code?

**Comment by tnorling** [comment]
My apologies I haven't had a chance to look at this yet. I will take a look next week.

**Comment by svdHero** [comment]
Okay. No problem. Thanks for letting me know. I am very grateful that you're looking into this.

**Comment by tnorling** [comment]
@svdHero Thanks for providing a repro. I was able to confirm that this is a bug in msal-react and will try to get a PR with a fix out in our next release of the library.

**Comment by svdHero** [comment]
I've just updated to the latest release and everything works beautifully. Thank you @tnorling for your work.
