### ISSUE TITLE
ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Multiple ID tokens differ only the environment property value.

### ISSUE THREAD

**Issue by anujjain85** [AzureAD/microsoft-authentication-library-for-js#5377]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Public or Confidential Client?

Public

### Description

We have been using MSAL react for quite some time. Some of our users are getting into this error, either while calling client.getActiveAccount() or acquireTokenSilent.

Error:
_ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account._

We have done initial investigation and the here are the results:
1. The localStorage has 2 accounts and 2 Id tokens for the same home account id, client id, realm, username. The only difference is the value of the environment property. One account has: login.window.net, other has login.microsoftonline.com.
2. On further investigation we figured, the "environment" value is obtained/determined from preferred_cache data from authority metadata fetched from the following URL. 
https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
![image](https://user-images.githubusercontent.com/33482465/200699435-4ce9d503-3eb1-42ce-9349-78bd0ad551d6.png)
3. From the image above, the MSAL js considers the values in the metadata.0.aliases to be practically equivalent to value set in metadata.0.preferred_cache property.
3. So, MSAL js allows to store account info + ID tokens based on another environment/preferred_Cache value even though another account and tokens exist with a known environment/preferred_cache value.

### Error Message

ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..
		at t [as constructor] (host-a365.en.bundle.js:40:3944)
		at new t (host-a365.en.bundle.js:40:10794)
		at Function.t.createMultipleMatchingTokensInCacheError (host-a365.en.bundle.js:40:12682)
		at t.e.readIdTokenFromCache (host-a365.en.bundle.js:53:179262)
		at host-a365.en.bundle.js:53:173121

### MSAL Configuration

```javascript
auth: {
      clientId: settings.ClientId,
      authority: settings.MsalConfigAuthority,
    },
    cache: {
      cacheLocation: 'localStorage'
    },
    system: {
      loadFrameTimeout: 15000
    }
  }
```

### Relevant Code Snippets

```javascript
Same as recommended by MSAL React documentation
```

### Reproduction Steps

This issue is occuring to some of our users. The repro steps have not been ascertained yet. We are not sure why some client machines download authority metadata with a different preferred_cache value.

### Expected Behavior

Before adding new account or tokens to localStorage, MSAL js should detect if localStorage already has an account and token with a preferred_cache value 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@anujjain85 The way that id tokens are cached includes the environment in the cache key. Have you tried calling acquireToken again following this error, providing the authority or the account?

**Comment by ghost** [comment]
@anujjain85 This issue has been automatically marked as stale because it is marked as requiring author feedback but has not had any activity for **5 days**. If your issue has been resolved please let us know by closing the issue. If your issue has **not** been resolved please leave a comment to keep this open. It will be closed automatically in **7 days** if it remains stale.
