### ISSUE TITLE
Client certificate issue when attempting to fetch https://login.microsoftonline.com/db05faca-c82a-4b9d-b9c5-0f64b6755421/v2.0/.well-known/openid-configuration

### ISSUE THREAD

**Issue by justinmchase** [AzureAD/microsoft-authentication-library-for-js#5487]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.5

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Confidential

### Description

We are getting an error when attempting to use this library after updating from 1.5 to 1.14:

> endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/db05faca-c82a-4b9d-b9c5-0f64b6755421/v2.0/.well-known/openid-configuration

When I just go to that endpoint in my browser it works just fine but for some reason I am no longer able to retrieve it from my server. I managed to disable certificate validation by creating a custom https agent:

```
new https.Agent({ rejectUnauthorized: false })
```

And it now starts working, so it seems like there is some kind of a certificate validation problem with that endpoint. Do I require some kind of special certs that I need to have installed to make this work? I am just using the `node:16` base Docker image for my server and not doing anythign fancy with certificates at all.

### Error Message

 endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/db05faca-c82a-4b9d-b9c5-0f64b6755421/v2.0/.well-known/openid-configuration

#### callstack

```
at ClientAuthError.AuthError [as constructor] (/var/app/node_modules/@azure/msal-common/src/error/AuthError.ts:49:9)
at new ClientAuthError (/var/app/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:215:15)
at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (/var/app/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:261:16)
at Function.<anonymous> (/var/app/node_modules/@azure/msal-common/src/authority/AuthorityFactory.ts:49:35)
at step (/var/app/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
at Object.throw (/var/app/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
at rejected (/var/app/node_modules/@azure/msal-common/dist/index.cjs.js:51:65)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### MSAL Configuration

```javascript
const authority = 'https://login.microsoftonline.com/db05faca-c82a-4b9d-b9c5-0f64b6755421'
new ConfidentialClientApplication({
  auth: {
    clientId,
    clientSecret,
    authority,  
    knownAuthorities: [authority],
  }
})
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

Using the above msal config, simply call any api such as:

```
await client.getAuthCodeUrl({
  scopes: DEFAULT_SCOPE,
  redirectUri: this.getRedirectUri(),
  domainHint: 'example.com',
  loginHint: email,
  state: encodedState,
})
```

Or you can reproduce this in a single line with docker like so:

```
docker run --entrypoint sh docker.repo1.uhc.com/node:16-alpine -c 'wget https://login.microsoftonline.com/db05faca-c82a-4b9d-b9c5-0f64b6755421/v2.0/.well-known/openid-configuration'
```

Which emits this error:

> Connecting to login.microsoftonline.com (40.126.28.23:443)
> 48ABA7EA8D7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
> ssl_client: SSL_connect
> wget: error getting response: Connection reset by peer

### Expected Behavior

I expect it to connect and have no certificate issues.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

@azure/msal-node 1.5.0

### Source

External (Customer)

**Comment by justinmchase** [comment]
I was able to confirm that this is actually a red herring. My company VPN does something funny with certificates, closing for now.
