### ISSUE TITLE
jsonwebtoken 9.0.0 version update started giving runtime error with node 18+ version "Right-hand side of 'instanceof' is not an object "

### ISSUE THREAD

**Issue by bornkiraupgrade** [AzureAD/microsoft-authentication-library-for-js#5716]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

With node 18+ version, 

When updated the jsonwebtoken to 9.0.0, my pipeline started to fail giving runtime error as "Right-hand side of 'instanceof' is not an object " at jsonwebtoken\sign.js:108:58

### Error Message

Right-hand side of 'instanceof' is not an object 

TypeError: Right-hand side of 'instanceof' is not an object
2023-02-24T12:15:51.8277499Z     at Object.module.exports [as sign] (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\jsonwebtoken\sign.js:108:58)
2023-02-24T12:15:51.8278567Z     at ClientAssertion.createJwt (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:2255:29)
2023-02-24T12:15:51.8279942Z     at ClientAssertion.getJwt (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:2219:19)
2023-02-24T12:15:51.8281354Z     at ConfidentialClientApplication.getClientAssertion (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:1924:39)
2023-02-24T12:15:51.8282834Z     at ConfidentialClientApplication.buildOauthClientConfiguration (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:1908:54)
2023-02-24T12:15:51.8283947Z     at process._tickCallback (internal/process/next_tick.js:68:7)

### Msal Logs

TypeError: Right-hand side of 'instanceof' is not an object
2023-02-24T12:15:51.8277499Z     at Object.module.exports [as sign] (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\jsonwebtoken\sign.js:108:58)
2023-02-24T12:15:51.8278567Z     at ClientAssertion.createJwt (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:2255:29)
2023-02-24T12:15:51.8279942Z     at ClientAssertion.getJwt (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:2219:19)
2023-02-24T12:15:51.8281354Z     at ConfidentialClientApplication.getClientAssertion (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:1924:39)
2023-02-24T12:15:51.8282834Z     at ConfidentialClientApplication.buildOauthClientConfiguration (D:\a\_tasks\EsrpRelease_be2a31a6-134a-482d-a926-deef3349ffca\4.0.12\node_modules\@azure\msal-node\dist\msal-node.cjs.development.js:1908:54)
2023-02-24T12:15:51.8283947Z     at process._tickCallback (internal/process/next_tick.js:68:7)

### MSAL Configuration

```javascript
Mentioned below
```

### Relevant Code Snippets

```javascript
var authorityHostUrl = Constant.AuthorityHostUrl;
        var tenant = this.config?.DomainTenantId;
        var authorityUrl = authorityHostUrl + '/' + tenant;
        var resourceUri = this.config!.ServiceEndpointUrl;
    
        const clientConfig = {
            auth: {
                clientId: this.config!.ClientId!,
                authority: authorityUrl,
                clientCertificate: {
                    thumbprint: this.config!.AuthCertThumbprint!,
                    privateKey: this.config!.AuthPrivateKey!,
                    x5c: this.config!.AuthPublicCert!
                }
            }
        };
    
        const cca = new Msal.ConfidentialClientApplication(clientConfig);
        var gatewayScope = resourceUri + Constant.APIAccessDefaultScope;
        const clientCredentialRequest = {

            scopes: [gatewayScope]
        };
    
        await cca.acquireTokenByClientCredential(clientCredentialRequest).then((response) => {

            this.accessToken = response?.accessToken!;
        }).catch((error) => {

            console.log(ExceptionMessages.TokenAcquiringError);
            console.log(error); // This is where the error is thrown
            throw error;
        });
```

### Reproduction Steps

using above code with mentioned versions below, it gives error

"jsonwebtoken": "^9.0.0",
"@azure/msal-node": "^1.15.0",
"@azure/identity": "^3.1.3",

node 18+,
npm 9+,
typescript 4.5+

### Expected Behavior

It should simply work.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
This looks like an issue with the `jsonwebtoken` library, can you take this up with them?

**Comment by bornkiraupgrade** [comment]
> This looks like an issue with the `jsonwebtoken` library, can you take this up with them?

Yes sure. Trying to repro in local as well, once I get more insights, will update this thread and also create ticket on jsonwebtoken.

**Comment by Sheshagiri** [comment]
@bornkiraupgrade and I work on the same team and apparently we were not targeting the correct node version which resulted in this error. @tnorling thank you for having a look at this, good to close this.

**Comment by tnorling** [comment]
Thanks for the update, glad you got it sorted out!

**Comment by bornkiraupgrade** [comment]
This is fixed now. Figured that we were pinning Node 10 version to be used at runtime, somewhere in the configuration and it was causing the nonexistence of crypto package (jsonwebtoken is dependent on crypto package which comes out of the box in Node latest versions)
