### ISSUE TITLE
MSA Logout without Selecting Account results in invalid_request Exceptions

### ISSUE THREAD

**Issue by JasonGore** [AzureAD/microsoft-authentication-library-for-js#5743]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

* `loginRedirect` or `loginPopup` as MSA account
* Sign out of MSA using `logoutRedirect`, but do not select MSA account on logout account selection screen
* Either navigate back or reload app, MSAL `getAllAccounts` shows no active accounts so app requires login
* Redirect login as same MSA account (which still appears on MSAL login account selection screen)
* Get thrown exception on both `handleRedirectPromise` and `loginPopup` flows

Error indicates both `username` and `login_hint` cannot be provided, but as far as I can tell, our app is providing neither. I assume this is internal implementation detail. The only recovery at this point is manual user intervention. My current workaround is to manually ask the user to do a full signout making sure to select the account to ensure full logout. It seems MSAL should either leave user signed in or do a full signout rather than what appears to be a mixed state that prevents subsequent signins without unhandled and unrecoverable exceptions being thrown.

### Error Message
```
redirectPromiseResult ServerError: invalid_request: The parameters 'username' and 'login_hint' cannot both be provided.
    at ServerError.AuthError [as constructor] (AuthError.ts?363e:49:1)
    at new ServerError (ServerError.ts?c483:13:1)
    at ResponseHandler.validateServerAuthorizationCodeResponse (ResponseHandler.ts?47a5:91:1)
    at AuthorizationCodeClient.handleFragmentResponse (AuthorizationCodeClient.ts?c80e:149:1)
    at RedirectHandler.eval (RedirectHandler.ts?4af1:105:1)
    at step (vendors-node_modules_azure_msal-browser_dist_app_PublicClientApplication_js.5d63b11a362ed1473199.js:111:23)
    at Object.next (vendors-node_modules_azure_msal-browser_dist_app_PublicClientApplication_js.5d63b11a362ed1473199.js:92:53)
    at vendors-node_modules_azure_msal-browser_dist_app_PublicClientApplication_js.5d63b11a362ed1473199.js:85:71
    at new Promise (<anonymous>)
    at __awaiter (vendors-node_modules_azure_msal-browser_dist_app_PublicClientApplication_js.5d63b11a362ed1473199.js:81:12)
```

### Msal Logs

Since I have a consistent repro, I can provide if useful, not sure offhand how to enable verbose logging

### MSAL Configuration

```javascript
auth: {
  clientId: MsalAuthService.authClientId,
  redirectUri: `${window.location.origin}/authLanding.html`,
  clientCapabilities: ['CP1'],
  authority: getTenantAuthority(),
  navigateToLoginRequestUrl: true
},
cache: {
  cacheLocation: 'localStorage',
  storeAuthStateInCookie: false
}
```

### Relevant Code Snippets

```javascript
loginRedirect(redirectRequest);
logoutRedirect(request);

// Either
try {
  redirectPromiseResult = await this.msalInstance.handleRedirectPromise();
} catch (e) {
  this.updateServiceState('SignOutRequired');
  return;
}

// Or
await this.loginPopup(request);

// Result in invalid_request exceptions of the same subtype
```

### Reproduction Steps

1. Call `loginRedirect`, `handleRedirectPromise` and `logoutRedirect` repeatedly with MSA account, making sure not to select MSA account during logout
2. Also occurs with `loginPoup` and `logoutRedirect` repeatedly 

### Expected Behavior

MSAL should either leave user signed in or do a full signout rather than what appears to be a mixed state that prevents subsequent signins without unhandled and unrecoverable exceptions being thrown.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by JasonGore** [comment]
Modified original report as exception is thrown for multiple MSAL functions. This exception is getting thrown for both `handleRedirectPromise` and `loginPopup` calls.

**Comment by tnorling** [comment]
@JasonGore Can you send me a network trace of this behavior (email on my profile)? I don't believe MSAL sets `username` anywhere and `loginHint` would only be provided if you pass an account or a loginHint into the login API so I'm not quite sure where these would be coming from...

The logout behavior you describe is expected. MSAL.js does not get any signal from the server to identify which user was selected on the sign out screen or even if the server signout is successful, thus the behavior on logout is that MSAL.js clears the cache and then optimistically sends the user to the server signout page where they may or may not select the account they wish to sign out of. More on logout [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md)

**Comment by ghost** [comment]
@JasonGore This issue has been automatically marked as stale because it is marked as requiring author feedback but has not had any activity for **5 days**. If your issue has been resolved please let us know by closing the issue. If your issue has **not** been resolved please leave a comment to keep this open. It will be closed automatically in **7 days** if it remains stale.
