### ISSUE TITLE
b2c-user-flows error AADB2C90084: Public clients should not send a client_secret

### ISSUE THREAD

**Issue by ddombrowsky** [AzureAD/microsoft-authentication-library-for-js#5808]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.16.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Public or Confidential Client?

Confidential

### Description

I have a b2c setup working using a C#/.NET application, and it works fine.  I wanted a script using node to do some additional work.

Going through the sample code in `samples/msal-node-samples/b2c-user-flows` will not allow me to log in.  

```
ServerError: invalid_request: undefined - [undefined]: AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.

Correlation ID: 3391c555-09cb-457d-b163-5c1cda1f2d4f
```

I'm using a confidential app settings because this is supposed to access the API directly, and because that's what the sample code uses.  I think this might be incorrect.

It does work if I apply this patch to change it to a public client with no client secret:

```
@@ -381,7 +385,6 @@ if (argv.$0 === "index.js") {
         auth: {
             clientId: config.authOptions.clientId,
             authority: config.policies.authorities.signUpSignIn.authority,
-            clientSecret: config.authOptions.clientSecret,
             knownAuthorities: [config.policies.authorityDomain],
         },
         cache: {
@@ -399,7 +402,7 @@ if (argv.$0 === "index.js") {
     };
 
     // Create an MSAL PublicClientApplication object
-    const confidentialClientApp = new msal.ConfidentialClientApplication(confidentialClientConfig);
+    const confidentialClientApp = new msal.PublicClientApplication(confidentialClientConfig);
 
     // Execute sample application with the configured MSAL PublicClientApplication
     return main(config, confidentialClientApp, null, redirectUri);
```

### Error Message

AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.

### MSAL Configuration

```javascript
redacted
```

### Relevant Code Snippets

code fails on this call in https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/b2c-user-flows/index.js#L306

```javascript



310                         const tokenResponse = await clientApplication.acquireTokenByCode(req.session.authCodeRequest);
```

### Reproduction Steps

1. download the sample code
2. configure it to your B2C environment
3. try and login using the site started with `node index.js`

### Expected Behavior

You should be able to log in to a properly configured system, following the readme.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @ddombrowsky.
I wasn't able to re-produce the issue. Configuring `authOptions` for `samples/msal-node-samples/b2c-user-flows` with no additional changes to the code worked fine for me. Could you please share [verbose logs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md)? It looks like the configuration issue to me.

**Comment by ddombrowsky** [comment]
Thanks @konstantin-msft .   I'm not sure what we're doing differently.  All I change is the `authOptions` and `policies.authorities` in `samples/msal-node-samples/b2c-user-flows/config/customConfig.json`, then run `node index.js` and I get the problem.

I enabled trace logs in `index.js`, and here's the redacted version:

```
Msal Node Auth Code Sample app listening on port 4200!
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Info - getAuthCodeUrl called
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Verbose - initializeRequestScopes called
[Fri, 24 Mar 2023 02:05:07 GMT] : [9ee3c770-0a4d-42d8-a4f8-194ca646b484] : @azure/msal-node@1.16.0 : Verbose - buildOauthClientConfiguration called
[Fri, 24 Mar 2023 02:05:07 GMT] : [9ee3c770-0a4d-42d8-a4f8-194ca646b484] : @azure/msal-node@1.16.0 : Verbose - building oauth client configuration with the authority: https://tenant.b2clogin.com/example.com/B2C_1_signupin
[Fri, 24 Mar 2023 02:05:07 GMT] : [9ee3c770-0a4d-42d8-a4f8-194ca646b484] : @azure/msal-node@1.16.0 : Verbose - createAuthority called
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Trace - Retrieving all cache keys
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Verbose - Attempting to get cloud discovery metadata in the config
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Verbose - Known Authorities: tenant.b2clogin.com
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Verbose - Authority Metadata: N/A
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Verbose - Canonical Authority: https://tenant.b2clogin.com/example.com/b2c_1_signupin/
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
[Fri, 24 Mar 2023 02:05:07 GMT] : @azure/msal-node@1.16.0 : Verbose - Found cloud discovery metadata in the config.
[Fri, 24 Mar 2023 02:05:08 GMT] : @azure/msal-node@1.16.0 : Trace - Item key: authority-metadata-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-tenant.b2clogin.com
[Fri, 24 Mar 2023 02:05:08 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:08 GMT] : @azure/msal-node@1.16.0 : Trace - Setting cache key value store
[Fri, 24 Mar 2023 02:05:08 GMT] : [9ee3c770-0a4d-42d8-a4f8-194ca646b484] : @azure/msal-node@1.16.0 : Verbose - Auth code client created
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Info - acquireTokenByCode called
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Verbose - initializeRequestScopes called
[Fri, 24 Mar 2023 02:05:09 GMT] : [27facecb-48ea-4da0-a0b7-2696874a962b] : @azure/msal-node@1.16.0 : Verbose - buildOauthClientConfiguration called
[Fri, 24 Mar 2023 02:05:09 GMT] : [27facecb-48ea-4da0-a0b7-2696874a962b] : @azure/msal-node@1.16.0 : Verbose - building oauth client configuration with the authority: https://tenant.b2clogin.com/example.com/B2C_1_signupin
[Fri, 24 Mar 2023 02:05:09 GMT] : [27facecb-48ea-4da0-a0b7-2696874a962b] : @azure/msal-node@1.16.0 : Verbose - createAuthority called
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Retrieving all cache keys
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Item key: authority-metadata-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-tenant.b2clogin.com
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Verbose - Attempting to get cloud discovery metadata in the config
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Verbose - Known Authorities: tenant.b2clogin.com
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Verbose - Authority Metadata: N/A
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Verbose - Canonical Authority: https://tenant.b2clogin.com/example.com/b2c_1_signupin/
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Verbose - Found cloud discovery metadata in the config.
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Item key: authority-metadata-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-tenant.b2clogin.com
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Setting cache key value store
[Fri, 24 Mar 2023 02:05:09 GMT] : [27facecb-48ea-4da0-a0b7-2696874a962b] : @azure/msal-node@1.16.0 : Verbose - Auth code client created
[Fri, 24 Mar 2023 02:05:09 GMT] : [27facecb-48ea-4da0-a0b7-2696874a962b] : @azure/msal-common@11.0.0 : Info - in acquireToken call in auth-code client
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Item key: server-telemetry-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Item key: throttling.{"clientId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","authority":"https://tenant.b2clogin.com/example.com/b2c_1_signupin/","scopes":["openid","profile","offline_access"],"authenticationScheme":"Bearer"}
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Item key: server-telemetry-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Item key: server-telemetry-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Fri, 24 Mar 2023 02:05:09 GMT] : @azure/msal-node@1.16.0 : Trace - Getting cache key-value store
ServerError: invalid_request: undefined - [undefined]: AADB2C90084: Public clients should not send a client_secret when redeeming a publicly acquired grant.
Correlation ID: 7c029376-ab62-44dc-a9e0-9fd4ed98724e
Timestamp: 2023-03-24 02:05:09Z
 - Correlation ID: undefined - Trace ID: undefined
    at ServerError.AuthError [as constructor] (microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:518:24)
    at new ServerError (microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:3393:28)
    at ResponseHandler.validateTokenResponse (microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:5288:19)
    at AuthorizationCodeClient.<anonymous> (microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:5596:41)
    at step (microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:79:23)
    at Object.next (microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:60:53)
    at fulfilled (microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:50:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'm running this from git commit c72bd52d9 `2023-03-20 20:28:15 -0700 GitHub: Update caching and performance docs (#5784)`

**Comment by konstantin-msft** [comment]
@ddombrowsky Thanks for the logs. Unfortunately, it's still not clear why this happens. Can you please share Fiddler or Network (HAR) trace? You can send it to my email, which is in my profile.

**Comment by hectormmg** [comment]
@bgavrilMS seems to be a Confidential Client issue, could you please take a look?

**Comment by ddombrowsky** [comment]
I'm afraid I haven't found the time to make a secure copy of a network trace of my client's azure B2C authentication scheme.  I'm not sure when I will be able to do that.

It's very possible it's my client's azure setup that's wrong, I'm just failing to see how.

**Comment by bgavrilMS** [comment]
What is your redirect URI? This determines if the app is public client or confidential client. Did you register this as web ?
<img width="398" alt="image" src="https://user-images.githubusercontent.com/12273384/233142042-c4699e26-3c57-462a-b806-c570f2456e32.png">

**Comment by ghost** [comment]
@ddombrowsky This issue has been automatically marked as stale because it is marked as requiring author feedback but has not had any activity for **5 days**. If your issue has been resolved please let us know by closing the issue. If your issue has **not** been resolved please leave a comment to keep this open. It will be closed automatically in **7 days** if it remains stale.

**Comment by ddombrowsky** [comment]
@bgavrilMS 
I just ran into this issue again with a different app using a similar Azure B2C configuration and a non-node Razor pages-based web app.  The redirect URI was set to be a Single Page App (SPA) and not a web app.  Switching it to a web app fixed it.  Can you confirm my understanding of the reason?

* Using the client secret in a web app is safe, because the secret is stored server side and is transmitted as part of the authentication workflow, and not directly seen by the user's browser.
* It is _not_ safe in a SPA (such as one that uses `MSAL.js`), because the login workflow is controlled by javascript on the browser side, so an additional step needs to happen to get a token that the browser can use for the authentication workflow.  

Is this correct?

**Comment by bgavrilMS** [comment]
Yes, in a traditional web app, where the backend performs the authentication logic, you use the "ConfidentialClientApplication" part of MSAL / the OAuth protocol. Backend can keep secrets. Having a secret demonstrates that the machine is known to the token issuer, i.e. it demonstrates confidentiality (hence the name ConfidentialClientApplication). Typical flow is: 

- ask the user to login by redirecting them to the /authorize endpoint of the identity provider
- after the user logs in (MFA etc.), the identity provider redirects to a route / controller of your web site along with an authorization code
- the backend logic for that controller / route triggers and you exchange the authorization code for a token (via MSAL's AcquireTokenByAuthCode - which is part of confidential client)

I am not an expert in SPA, but afaik it is more like a public client (desktop app / mobile app), i.e. you cannot deploy secrets to it.
