### ISSUE TITLE
Authority provided in login request or PublicClientApplication config does not match the environment of the provided account

### ISSUE THREAD

**Issue by fong1999** [AzureAD/microsoft-authentication-library-for-js#6154]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.11.x

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

Hi!

For some reason, it worked before, now it stopped working locally. We are getting this error below: Anything that we are missing? Thanks!

https://localhost.nwie.net:3000/

```
test error type -->  ClientConfigurationError: authority_mismatch: Authority mismatch error. Authority provided in login request or PublicClientApplication config does not match the environment of the provided account. Please use a matching account or make an interactive request to login to this authority.
    at ClientConfigurationError.AuthError [as constructor] (AuthError.ts:49:1)
    at ClientConfigurationError.ClientAuthError [as constructor] (ClientAuthError.ts:222:1)
    at new ClientConfigurationError (ClientConfigurationError.ts:115:1)
    at ClientConfigurationError.createAuthorityMismatchError (ClientConfigurationError.ts:315:1)
    at SilentCacheClient.<anonymous> (BaseInteractionClient.ts:143:1)
    at step (MindbreezeClientService.ts:37:1)
    at Object.next (MindbreezeClientService.ts:37:1)
    at fulfilled (MindbreezeClientService.ts:37:1)
    at nrWrapper ((index):64:35611)
```

### Relevant Code Snippets

```javascript
const loginRequest = {
  scopes: ["openid", "profile", "User.Read"]
}

export const tokenRequest = {
  scopes: [
    "user.read",
  ]
}

const tokenRequestForceRefresh = {
  scopes: ["User.Read"],
  forceRefresh: true,
}

export let myMSALObj = new PublicClientApplication(msalConfig);
export let username = "";

export function hasActiveMsalSession(): boolean {
  return !!username;
}

function getTokenRedirect(request:any) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  const currentAccount = myMSALObj.getAllAccounts();

  request.account = currentAccount;
  return myMSALObj.acquireTokenSilent(request).catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      console.log("test MSAL acquireTokenSilent - if");
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.log("test error type --> ", error);
      console.log("test MSAL acquireTokenSilent - else");
      console.warn("MsalAuthService >>> getTokenRedirect : "+ error);
    }
  });
}

export function getAccessToken(): Promise<string> {
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.accessToken) {
      return "";
    } else {
      return response.accessToken;
    }
  })
}

export function getIdTokenFromAzure(): Promise<string> {
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.idToken) {
      return "";
    } else {
      return response.idToken;
    }
  })
}

function getMindbreezeHeaders(numberOfCallAttempts: number = 0): Promise<any> {
  return getIdTokenFromAzure().then(accessToken => {
    //Check if the response is null or has errors, if it is/does, retry getting the access token up to 5 times
    if (numberOfCallAttempts >= 5) {
      //Will return a 401 error on trying to make the request but prevents the page from erroring due to resp being null..
      //Future: Possibly add logging to Splunk with error and user data
      return null;
    }
    else if (!accessToken) {
      return getMindbreezeHeaders(numberOfCallAttempts + 1);
    }
    else {
      return accessToken;
    }
  });
}

/** Get Authorization jwt token for request to Mindbreeze */
export const getAuthorizationToken = (): any => {
  return getIdTokenFromAzure().then(token => {
    // return token ? `Bearer ${token}` : false;
    console.log("test --- ", token);
    if(token) {
      sessionStorage.setItem("idToken.for.search", `Bearer ${token}`)
      return `Bearer ${token}`;
    }
    return false;
  })
}

export const isTokenCurrent = (token:string): boolean => {
  let decodedToken = jwt_decode<JwtPayload>(token);
  let currentDate = new Date();
  let result = true;

  if(decodedToken?.exp && currentDate.getTime() > (decodedToken.exp * 1000)) {
      result = false;
  }
  return result;
}

export const getMindbreezeHeadersWithForceRefresh = (): any => {
  return getIdTokenFromAzureWithForceRefresh().then(token => {
    // return token ? `Bearer ${token}` : false;
    if(token) {
      sessionStorage.setItem("idToken.for.search", `Bearer ${token}`)
      return `Bearer ${token}`;
    }
    return false;
  })
}

export const getIdTokenFromAzureWithForceRefresh =(): Promise<string> => {
  return getTokenRedirect(tokenRequestForceRefresh).then(response => {
    if (!response || !response.idToken) {
      return "";
    } else {
      return response.idToken;
    }
  })
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@fong1999 can we see the MSAL config? Also, if you can send a Fiddler trace to the e-mail on my profile that would help diagnose the issue. The error suggests the user account does not belong to the authority the token is being requested from.

**Comment by fong1999** [comment]
@hectormmg  Hi Hector, Thanks much for your response! 

Do you mean this configuration?

```
export const msalConfig: Msal.Configuration = {
  auth: {
    clientId: EnvironmentService.getAzureClientId(),
    redirectUri: `${window.location.origin}`,
    authority: `https://login.microsoftonline.com/${EnvironmentService.getAzureTenantId()}`
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: true,
  }
}
 ```
 I will send you the trace tomorrow. 
 
Thanks!

**Comment by fong1999** [comment]
@hectormmg Hi Hector, 

Sorry, I am allowed to share the trace info. But I was able to compare the trace between my local and prod. 

I see the difference is the my local trace: 

Localhost has below, but prod does not.

_"stsservicecookie=estsfd; path=/; secure; samesite=none; httponly",_

Any ideas? 

Thanks!

**Comment by fong1999** [comment]
@hectormmg  

Hi Hector, 

I am just following up on this issue. Please let me know if you need more information. 

Thanks so much!

**Comment by fong1999** [comment]
@hectormmg  

Hi Hector, we found out that the @msal-browser latest version is causing the issue we are facing. We had to use version 2.37.0 to fix it. Any information on any known issue with version 2.37.1? 

```
    "@azure/msal-browser": "2.37.0",
    "@azure/msal-react": "1.5.2",
```

https://www.npmjs.com/package/@azure/msal-browser/v/2.37.1
https://www.npmjs.com/package/@azure/msal-browser?activeTab=versions

Thanks!

**Comment by lalimasharda** [comment]
Hey @fong1999 , can you confirm that the environment set in your account object that is being passed to acquireTokenSilent API matches or is an alias of the authority you have specified in your login request or the MSAL config? Note that the authority provided in the login request takes higher priority, so please check there first!

**Comment by fong1999** [comment]
@lalimasharda Hi, Thanks for your reply! Yes, we verified that there is no Azure SSO configuration and react code changes to the app. With the updating the library version number as a workaround, we were able to solve the issue. But we had to catch an error for Chrome browser. 

```
  .catch(err => {
    console.error(err);
  })
```
Any information on any known issue with version 2.37.1? 

Thanks!

**Comment by lalimasharda** [comment]
Hey @fong1999 , can you debug and confirm that the account set in your silent request belongs to the authority you have mentioned in your MSAL config? Also, can you please share verbose MSAL.js logs for this issue? I just need some clarity on the code flow.

**Comment by lalimasharda** [comment]
Also on another note, in your code snippet below, it does not seem that you are passing in the correct account object. Can you please cross check once? :

function getTokenRedirect(request:any) {
const currentAccount = myMSALObj.getAllAccounts();

  request.account = currentAccount;
  return myMSALObj.acquireTokenSilent(request).catch(error => {  ...

**Comment by fong1999** [comment]
@lalimasharda Thank you for the suggestions! 

Here is the current code snippet: What are we missing? Thanks!

```
function getTokenRedirect(request:any) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  const currentAccount = myMSALObj.getAllAccounts();

  request.account = currentAccount;
  console.log("testing -- request.account: ", request.account);
  return myMSALObj.acquireTokenSilent(request).catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      console.log("testing -- request.account: in if : ", request.account);
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.log("testing -- request.account: in else : ", request.account);
      console.log("test error type --> ", error);
      console.log("test MSAL acquireTokenSilent - else");
      console.warn("MsalAuthService >>> getTokenRedirect : "+ error);
    }
  });
}
```

**Comment by lalimasharda** [comment]
const currentAccount = myMSALObj.getAllAccounts(); 

This method will return an array of all accounts in cache and not just the current one. You should try getActiveAccount() instead to get the current active account assuming you have done setActiveAccount() properly after getting tokens for the first time.

**Comment by fong1999** [comment]
@hectormmg  Thanks for the info!

What do you think below code snippet that is from another front end app that we manage? Will the way that we are setting setActiveAccount helps with the issue we have?  Thanks!

```
if (!BrowserUtils.isIframe()) {
  myMSALObj = new Msal.PublicClientApplication(msalConfig);
  // Redirect: once login is successful and redirects with tokens, call Graph API
  myMSALObj.handleRedirectPromise().then(handleResponse).catch(err => {
    console.error(err);
  });
}

export function hasActiveMsalSession(): boolean {
  return !!username;
}

function handleResponse(resp) {
  if (resp !== null) {
    username = resp.account.username;
    myMSALObj.setActiveAccount(resp.account);
  } else {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    const currentAccounts = myMSALObj.getAllAccounts();
    if (currentAccounts === null) {
      return;
    } else if (currentAccounts.length > 1) {
      // Add choose account code here
      console.warn("MsalAuthService >>> handleResponse >>> Multiple accounts detected.");
    } else if (currentAccounts.length === 0) {
      signIn();
    } else if (currentAccounts.length === 1) {
      username = currentAccounts[0].username;
      myMSALObj.setActiveAccount(currentAccounts[0]);
    }
  }
}

function signIn() {
  myMSALObj.loginRedirect(loginRequest);
}

function getTokenRedirect(request) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  return myMSALObj.acquireTokenSilent(request).catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.warn("MsalAuthService >>> getTokenRedirect : " + error);
    }
  });
}
```

**Comment by lalimasharda** [comment]
Yes, the above code snippet looks good to me for setActiveAccount but you also have to call getActiveAccount() to get the current active account that is required in AcquireTokenSilent requests.

**Comment by fong1999** [comment]
> Yes, the above code snippet looks good to me for setActiveAccount but you also have to call getActiveAccount() to get the current active account that is required in AcquireTokenSilent requests.

@lalimasharda Hi! Thank you for your suggestion! 

Where should I call getActiveAccount()? Could you please share an example? 

We call getAllAccounts() in the code. Does this work? 

```
function handleResponse(resp) {
  if (resp !== null) {
    username = resp.account.username;
    myMSALObj.setActiveAccount(resp.account);
  } else {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    const currentAccounts = myMSALObj.getAllAccounts();
    if (currentAccounts === null) {
      return;
    } else if (currentAccounts.length > 1) {
      // Add choose account code here
      console.warn("MsalAuthService >>> handleResponse >>> Multiple accounts detected.");
    } else if (currentAccounts.length === 0) {
      signIn();
    } else if (currentAccounts.length === 1) {
      username = currentAccounts[0].username;
      myMSALObj.setActiveAccount(currentAccounts[0]);
    }
  }
}

```

Thanks much in advance!
