### ISSUE TITLE
Cannot login with Power BI Dataset.Read.All scope

### ISSUE THREAD

**Issue by Fernaperg** [AzureAD/microsoft-authentication-library-for-js#6252]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

Hello, I'm trying to create a token for my react application to connect to users Power BI Dataset.Read.All. I already added this configuration into the App registrations configuration on the Azure Portal.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/125584508/4bc26032-9986-4eae-99e6-7f0e0e06e602)

I have the following code:

```js
function MicrosoftSingInButton({ onLogin }) {
  const { instance } = useMsal()

  const handleLogin = () => {
    instance
      .loginPopup({
        scopes: [
          'https://graph.microsoft.com/User.Read',
          'https://graph.microsoft.com/User.ReadBasic.All',
          'https://analysis.windows.net/powerbi/api/Dataset.Read.All',
        ],
      })
      .then(onLogin)
      .catch((e) => {
        console.error(e) // Error shown here
      })
  }
  return (
    <Button
      variant="secondary"
      className="w-100 p-2 loginmicrosoftbutton"
      onClick={handleLogin}
    >
      <Image
        alt={t('Microsoft icon')}
        src="/Microsoft-icon.svg"
        height={25}
        width={25}
        style={{ display: 'inline-block' }}
      />
      <span
        className="text-dark mx-2"
        style={{ fontSize: 14, fontFamily: 'Roboto' }}
      >
          Sign in with Microsoft
      </span>
    </Button>
  )
}
```

The error displayed on the console is:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/125584508/17dd3338-4c8c-45ad-8c4a-ed84969e6e45)

If I remove the Dataset.Read.All scope it works perfectly (but I need this scope in order to retrieve table data).

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'c15d4110-db1b-41e3-b371-d2629d24af59',
    authority: 'https://login.microsoftonline.com/common',
    redirecUri: '/',
    postLogoutRedirectUri: '/',
    clientCapabilities: ['CP1'],
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return
        }
        // eslint-disable-next-line
        switch (level) {
          case LogLevel.Error:
            console.error(message)
            return
          case LogLevel.Info:
            console.info(message)
            return
          case LogLevel.Verbose:
            console.debug(message)
            return
          case LogLevel.Warning:
            console.warn(message)
            return
        }
      },
    },
  },
}
```

### Relevant Code Snippets

```javascript
function MicrosoftSingInButton({ onLogin }) {
  const { instance } = useMsal()

  const handleLogin = () => {
    instance
      .loginPopup({
        scopes: [
          'https://graph.microsoft.com/User.Read',
          'https://graph.microsoft.com/User.ReadBasic.All',
          'https://analysis.windows.net/powerbi/api/Dataset.Read.All',
        ],
      })
      .then(onLogin)
      .catch((e) => {
        console.error(e) // Error shown here
      })
  }
  return (
    <Button
      variant="secondary"
      className="w-100 p-2 loginmicrosoftbutton"
      onClick={handleLogin}
    >
      <Image
        alt={t('Microsoft icon')}
        src="/Microsoft-icon.svg"
        height={25}
        width={25}
        style={{ display: 'inline-block' }}
      />
      <span
        className="text-dark mx-2"
        style={{ fontSize: 14, fontFamily: 'Roboto' }}
      >
          Sign in with Microsoft
      </span>
    </Button>
  )
}
```

### Identity Provider

None

### Source

External (Customer)

**Comment by tnorling** [comment]
You can't request scopes for multiple resources in a single request. Try logging in with the graph scopes first then call `acquireTokenSilent` with just the PowerBI scopes.

**Comment by Fernaperg** [comment]
Thank you very much. Now I'm trying to request this scopes as you suggest on component mount after login with the following snippet:

```javascript
  const { instance, inProgress, accounts } = useMsal()

  useEffect(() => {
    if (inProgress !== InteractionStatus.None) return

    const accessTokenRequest = {
      scopes: ['https://analysis.windows.net/powerbi/api/Dataset.Read.All'],
      account: accounts[0],
    }
    instance
      .acquireTokenSilent(accessTokenRequest)
      .then((accessTokenResponse) => {
        // Acquire token silent success
        let accessToken = accessTokenResponse.accessToken
        console.log('accessToken ------------>', accessToken)
      })
      .catch((error) => {
        if (error instanceof InteractionRequiredAuthError) {
          instance
            .acquireTokenPopup(accessTokenRequest)
            .then(function (accessTokenResponse) {
              // Acquire token interactive success
              let accessToken = accessTokenResponse.accessToken
              console.log('accessToken 2 ------------>', accessToken)
            })
            .catch(function (error) {
              // Acquire token interactive failure
              console.log(error)
            })
        }
        console.log(error)
      })
  }, [instance, accounts, inProgress])
```

I know once the access token is obtained I should stop it and avoid another execution of the method `acquireTokenSilent` but right not it is returning me the following error:

```txt
ServerError: invalid_scope: 70011 - [2023-07-20 11:29:28Z]: AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://analysis.windows.net/powerbi/api/Dataset.Read.All openid profile offline_access' does not exist.
Trace ID: a02b4c4b-fb51-4c8f-b08d-c6ddafd58f00
Correlation ID: b6734e18-7096-4b34-8ea5-2a592644fc9b
Timestamp: 2023-07-20 11:29:28Z - Correlation ID: b6734e18-7096-4b34-8ea5-2a592644fc9b - Trace ID: a02b4c4b-fb51-4c8f-b08d-c6ddafd58f00
```
I also tried it changing the scope to `Dataset.Read.All` but it returns the same error.

Do you know what should I change?

Thank you in advance!

**Comment by konstantin-msft** [comment]
@Fernaperg Can you please try to use `https://analysis.windows.net/powerbi/api/.default` scope?

**Comment by Fernaperg** [comment]
Changing to this scope, it returns me the exact same error:

```txt
ServerError: invalid_scope: 70011 - [2023-07-25 07:59:40Z]: AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://analysis.windows.net/powerbi/api/.default openid profile offline_access' does not exist.
Trace ID: f2f0a137-7ca0-415e-a923-8f9dfa561b00
Correlation ID: 506d94d3-0fc9-444e-a232-f663b95807ee
Timestamp: 2023-07-25 07:59:40Z - Correlation ID: 506d94d3-0fc9-444e-a232-f663b95807ee - Trace ID: f2f0a137-7ca0-415e-a923-8f9dfa561b00
    at ServerError.AuthError [as constructor] (AuthError.ts:49:1)
    at new ServerError (ServerError.ts:13:1)
    at ResponseHandler.validateTokenResponse (ResponseHandler.ts:99:1)
    at RefreshTokenClient.<anonymous> (RefreshTokenClient.ts:64:1)
    at step (MathUtils.ts:23:1)
    at Object.next (MathUtils.ts:23:1)
    at fulfilled (MathUtils.ts:23:1)
```

**Comment by Fernaperg** [comment]
The problem persists, could you give me some hint on how to solve it?

**Comment by Fernaperg** [comment]
Hello? Can anyone help? I'm a little bit in a hurry now, I need to know something about this issue. Can you help me @tnorling, @konstantin-msft, @sameerag or anyone?

**Comment by sameerag** [comment]
@Fernaperg Did you also contact the PowerBI folks for the correct scopes?

**Comment by tnorling** [comment]
The error means your app registration does not have this scope registered, please double check the appId on your registration matches the clientId you are providing to MSAL and the scope has been added to the permissions. If you think this is an error please open a [support case with Azure AD](https://azure.microsoft.com/en-us/support/create-ticket/), this error not thrown or controlled by MSAL.js and thus our ability to troubleshoot will, unfortunately, be limited.
