### ISSUE TITLE
Vite/Vue3, dependency scan issue (packageMetadata in msal-browser)

### ISSUE THREAD

**Issue by daglenn1960** [AzureAD/microsoft-authentication-library-for-js#6805]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.6.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Public or Confidential Client?

Public

### Description

Issue with @azure/msal-browser (happens with any msal-browser 3.x.x. version):

- Node.js v 18.17.1.   
- npm v 10.1.0
- vue v 3.4.5
- vite: v 4.5.1

 VITE v4.5.1  ready in 526 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error:   Failed to scan for dependencies from entries:
  C:/afni_dev/afniACM/AfniAcm/index.html

  X [ERROR] Missing "./dist/packageMetadata" specifier in "@azure/msal-browser" package [plugin vite:dep-scan]

    src/stores/lookup.js:1:21:
      1 │ import { name } from '@azure/msal-browser/dist/packageMetadata'
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Error Message

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/afni_dev/afniACM/AfniAcm/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44748:19)
    at handlePlugins (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:1292:21)
    at buildOrContextImpl (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:978:5)
    at Object.buildOrContext (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:786:5)
    at C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:2186:27)
    at Object.context (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:2026:58)
    at prepareEsbuildScanner (file:///C:/afni_dev/afniACM/AfniAcm/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44531:26)

    at failureErrorWithLog (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:1649:15)
    at C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:1058:25
    at runOnEndCallbacks (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:1484:45)
    at buildResponseToResult (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:1056:7)
    at C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:1068:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:1067:54)
    at handleRequest (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:729:19)
    at handleIncomingPacket (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:755:7)
    at Socket.readFromStdout (C:\afni_dev\afniACM\AfniAcm\node_modules\vite\node_modules\esbuild\lib\main.js:679:7)

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: configGetValue("func_api_clientid"), // afniformsaastestfunc 
    authority: configGetValue("func_api_authority"),
    redirectUri: configGetValue("redirect_uri"), // Must be registered as a SPA redirectURI on your app registration
    postLogoutRedirectUri: configGetValue("redirect_uri") // Must be registered as a SPA redirectURI on your app registration
  },
  cache: {
    cacheLocation: 'localStorage'
  },
  system: {
      loggerOptions: {
          loggerCallback: (level, message, containsPii) => {
              if (containsPii) {
                  return;
              }
              switch (level) {
                  case LogLevel.Error:
                      console.error(message);
                      return;
                  case LogLevel.Info:
                      // console.info(message);
                      return;
                  case LogLevel.Verbose:
                      // console.debug(message);
                      return;
                  case LogLevel.Warning:
                      console.warn(message);
                      return;
                  default:
                      return;
              }
          },
          logLevel: LogLevel.Verbose
      }
  }
};
```

### Relevant Code Snippets

```javascript
n/a, vite fails to run application
```

### Reproduction Steps

npm run dev

### Expected Behavior

Running dev environment

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
The referenced file [does exist](https://www.npmjs.com/package/@azure/msal-browser/v/3.6.0?activeTab=code) in the published package. We are not experts in Vite and can't speculate as to why this is breaking with your toolchain. If there's specific changes we need to make to support this please feel free to open a PR or a new issue with suggestions.

**Comment by t3o-it** [comment]
If it happens to someone else, since I scratched my head for a while to find out what was the problem, in my case it was just an accidental auto import of 
```
import { name } from '@azure/msal-browser/dist/packageMetadata'
``` 
somewhere in the code... :man_facepalming:
