### ISSUE TITLE
ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved when using Axios interceptor to add JWT to requests

### ISSUE THREAD

**Issue by sgspinola** [AzureAD/microsoft-authentication-library-for-js#6850]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.10

### Public or Confidential Client?

Public

### Description

I've integrated MSAL in my React SPA by using an Axios interceptor to inject the header with the JWT on every API call. It works fine across the app for different GET, POST and DELETE requests, but in a particular request I am getting the following error when calling `acquireTokenSilent`:

```
[Fri, 26 Jan 2024 12:34:37 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 12:34:37 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.js:51
2
[Fri, 26 Jan 2024 12:34:37 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 12:34:37 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Perf: Visibility change detected
authConfig.js:51
ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved
    at createClientAuthError (/Users/xxxx/dev/appsec-handbook/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:340:1)
    at Module.createDiscoveredInstance (/Users/xxxx/dev/appsec-handbook/node_modules/@azure/msal-common/src/authority/AuthorityFactory.ts:70:1)
    at async SilentCacheClient.validateRequestAuthority (/Users/xxxx/dev/appsec-handbook/node_modules/@azure/msal-browser/src/interaction_client/BaseInteractionClient.ts:229:1)
    at async SilentCacheClient.initializeBaseRequest (/Users/xxxx/dev/appsec-handbook/node_modules/@azure/msal-browser/src/interaction_client/BaseInteractionClient.ts:149:1)
    at async SilentCacheClient.initializeSilentRequest (/Users/xxxx/dev/appsec-handbook/node_modules/@azure/msal-browser/src/interaction_client/SilentCacheClient.ts:119:1)
    at async StandardController.acquireTokenSilentAsync (/Users/xxxx/dev/appsec-handbook/node_modules/@azure/msal-browser/src/controllers/StandardController.ts:2044:1)
    at async StandardController.acquireTokenSilent (/Users/xxxx/dev/appsec-handbook/node_modules/@azure/msal-browser/src/controllers/StandardController.ts:1954:1)
    at async https://localhost:3000/static/js/bundle.js:3733:22
    at async Axios.request (https://localhost:3000/static/js/bundle.js:87244:14) {errorCode: 'endpoints_resolution_error', errorMessage: 'Endpoints cannot be resolved', subError: '', name: 'ClientAuthError', stack: 'ClientAuthError: endpoints_resolution_error: …/localhost:3000/static/js/bundle.js:87244:14)', …}
```

Is my approach for the instance initialization and obtaining the tokens correct? Is this an MSAL related issue?

### Error Message

Stack trace of the failing OIDC configuration request:
```
sendGetRequestAsync @ https://localhost:3000/static/js/bundle.js:72868
getEndpointMetadataFromNetwork @ https://localhost:3000/static/js/bundle.js:74516
(anonymous) @ https://localhost:3000/static/js/bundle.js:82315
updateEndpointMetadata @ https://localhost:3000/static/js/bundle.js:74419
(anonymous) @ https://localhost:3000/static/js/bundle.js:82315
resolveEndpointsAsync @ https://localhost:3000/static/js/bundle.js:74346
(anonymous) @ https://localhost:3000/static/js/bundle.js:82315
createDiscoveredInstance @ https://localhost:3000/static/js/bundle.js:74928
(anonymous) @ https://localhost:3000/static/js/bundle.js:82315
getDiscoveredAuthority @ https://localhost:3000/static/js/bundle.js:72088
validateRequestAuthority @ https://localhost:3000/static/js/bundle.js:70031
initializeBaseRequest @ https://localhost:3000/static/js/bundle.js:69982
(anonymous) @ https://localhost:3000/static/js/bundle.js:82315
initializeSilentRequest @ https://localhost:3000/static/js/bundle.js:71654
(anonymous) @ https://localhost:3000/static/js/bundle.js:82315
acquireTokenSilentAsync @ https://localhost:3000/static/js/bundle.js:68448
(anonymous) @ https://localhost:3000/static/js/bundle.js:82315
acquireTokenSilent @ https://localhost:3000/static/js/bundle.js:68372
acquireTokenSilent @ https://localhost:3000/static/js/bundle.js:64355
(anonymous) @ https://localhost:3000/static/js/bundle.js:3733
_request @ https://localhost:3000/static/js/bundle.js:87331
request @ https://localhost:3000/static/js/bundle.js:87244
httpMethod @ https://localhost:3000/static/js/bundle.js:87383
wrap @ https://localhost:3000/static/js/bundle.js:88488
(anonymous) @ https://localhost:3000/static/js/bundle.js:186
postTool @ https://localhost:3000/static/js/bundle.js:185
handleSubmit @ https://localhost:3000/static/js/bundle.js:3056
callCallback @ https://localhost:3000/static/js/bundle.js:28224
invokeGuardedCallbackDev @ https://localhost:3000/static/js/bundle.js:28268
invokeGuardedCallback @ https://localhost:3000/static/js/bundle.js:28325
invokeGuardedCallbackAndCatchFirstError @ https://localhost:3000/static/js/bundle.js:28339
executeDispatch @ https://localhost:3000/static/js/bundle.js:32483
processDispatchQueueItemsInOrder @ https://localhost:3000/static/js/bundle.js:32509
processDispatchQueue @ https://localhost:3000/static/js/bundle.js:32520
dispatchEventsForPlugins @ https://localhost:3000/static/js/bundle.js:32529
(anonymous) @ https://localhost:3000/static/js/bundle.js:32689
batchedUpdates$1 @ https://localhost:3000/static/js/bundle.js:47081
batchedUpdates @ https://localhost:3000/static/js/bundle.js:28072
dispatchEventForPluginEventSystem @ https://localhost:3000/static/js/bundle.js:32688
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ https://localhost:3000/static/js/bundle.js:30194
dispatchEvent @ https://localhost:3000/static/js/bundle.js:30188
dispatchDiscreteEvent @ https://localhost:3000/static/js/bundle.js:30165
```

### MSAL Logs

Here are the logs from a successful request:

```log
[Fri, 26 Jan 2024 13:01:35 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:01:35 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.js:51
2
[Fri, 26 Jan 2024 13:01:35 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:01:35 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getAccessToken - Returning access token
authConfig.js:51
[Fri, 26 Jan 2024 13:01:35 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:01:35 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenSuccess
authConfig.js:51
2
[Fri, 26 Jan 2024 13:01:35 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
```

And from the request having the problem:

```log
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.js:51
2
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
react-dom.development.js:29840
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeStart
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeEnd
authConfig.js:51
3
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
2
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-browser@3.7.1 : Info - initialize has already been called, exiting early.
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [dc071b6e-4cba-47e7-8d3d-6cc1e2210ea5] : msal.js.browser@3.7.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectEnd
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-react@2.0.10 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-react@2.0.10 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
authConfig.js:51
3
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-react@2.0.10 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-react@2.0.10 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
authConfig.js:51
3
[Fri, 26 Jan 2024 13:02:51 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
```

If repeated once more, the message `Info -Perf: Visibility change detected` preceeds the ClientAuthError:

```log
[Fri, 26 Jan 2024 13:17:42 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51 [Fri, 26 Jan 2024 13:17:42 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.js:51 [Fri, 26 Jan 2024 13:17:42 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
authConfig.js:51 [Fri, 26 Jan 2024 13:17:42 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token
 [Fri, 26 Jan 2024 13:17:42 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Perf: Visibility change detected
 ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved
    at createClientAuthError (:3000/static/js/bundle.js:79061:10)
    at Module.createDiscoveredInstance (:3000/static/js/bundle.js:74931:92)
    at async SilentCacheClient.validateRequestAuthority (:3000/static/js/bundle.js:70031:33)
    at async SilentCacheClient.initializeBaseRequest (:3000/static/js/bundle.js:69982:7)
    at async SilentCacheClient.initializeSilentRequest (:3000/static/js/bundle.js:71654:25)
    at async StandardController.acquireTokenSilentAsync (:3000/static/js/bundle.js:68448:29)
    at async StandardController.acquireTokenSilent (:3000/static/js/bundle.js:68400:13)
    at async :3000/static/js/bundle.js:3733:22
    at async Axios.request (:3000/static/js/bundle.js:87244:14)
 Fetch failed loading: GET "https://<myb2c>.b2clogin.com/<myb2c>.onmicrosoft.com/b2c_1_login/v2.0/.well-known/openid-configuration".
sendGetRequestAsync @ bundle.js:72868
getEndpointMetadataFromNetwork @ bundle.js:74516
(anonymous) @ bundle.js:82315
updateEndpointMetadata @ bundle.js:74419
(anonymous) @ bundle.js:82315
resolveEndpointsAsync @ bundle.js:74346
await in resolveEndpointsAsync (async)
(anonymous) @ bundle.js:82315
createDiscoveredInstance @ bundle.js:74928
(anonymous) @ bundle.js:82315
getDiscoveredAuthority @ bundle.js:72088
validateRequestAuthority @ bundle.js:70031
initializeBaseRequest @ bundle.js:69982
(anonymous) @ bundle.js:82315
initializeSilentRequest @ bundle.js:71654
(anonymous) @ bundle.js:82315
acquireTokenSilentAsync @ bundle.js:68448
(anonymous) @ bundle.js:82315
acquireTokenSilent @ bundle.js:68372
acquireTokenSilent @ bundle.js:64355
(anonymous) @ bundle.js:3733
Promise.then (async)
_request @ bundle.js:87331
request @ bundle.js:87244
httpMethod @ bundle.js:87383
wrap @ bundle.js:88488
(anonymous) @ bundle.js:186
postTool @ bundle.js:185
handleSubmit @ bundle.js:3056
callCallback @ bundle.js:28224
invokeGuardedCallbackDev @ bundle.js:28268
invokeGuardedCallback @ bundle.js:28325
invokeGuardedCallbackAndCatchFirstError @ bundle.js:28339
executeDispatch @ bundle.js:32483
processDispatchQueueItemsInOrder @ bundle.js:32509
processDispatchQueue @ bundle.js:32520
dispatchEventsForPlugins @ bundle.js:32529
(anonymous) @ bundle.js:32689
batchedUpdates$1 @ bundle.js:47081
batchedUpdates @ bundle.js:28072
dispatchEventForPluginEventSystem @ bundle.js:32688
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ bundle.js:30194
dispatchEvent @ bundle.js:30188
dispatchDiscreteEvent @ bundle.js:30165
Navigated to https://localhost:3000/tools/add?
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
authConfig.js:51 [Fri, 26 Jan 2024 13:17:43 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeStart
authConfig.js:51 [Fri, 26 Jan 2024 13:17:43 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeEnd
```

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
import { LogLevel } from "@azure/msal-browser";

const REACT_APP_OAUTH_REDIRECT_URL = process.env.REACT_APP_OAUTH_REDIRECT_URL

export const b2cPolicies = {
    names: {
        signUpSignIn: 'B2C_1_LOGIN'
    },
    authorities: {
        signUpSignIn: {
            authority: 'https://<myb2c>.b2clogin.com/<myb2c>onmicrosoft.com/B2C_1_LOGIN',
        }
    },
    authorityDomain: '<myb2c>.b2clogin.com',
};

export const msalConfig = {
    auth: {
        clientId: 'xxxxxx,
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain], 
        redirectUri: REACT_APP_OAUTH_REDIRECT_URL,
        postLogoutRedirectUri: REACT_APP_OAUTH_REDIRECT_URL,
        navigateToLoginRequestUrl: false,
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false,
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                console.log(message)
            },
            LogLevel: LogLevel.Verbose,
            piiLoggingEnabled: true
        },
    },
};
export const loginRequest = {
    scopes: [
        "https://<mytenant>/appsec/api/Tools"
    ]
};
```

### Relevant Code Snippets

```javascript
how I initialize the client and interceptor:

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { PublicClientApplication, EventType, InteractionRequiredAuthError } from '@azure/msal-browser';
import { msalConfig, loginRequest } from "./authConfig.js";
import axios from 'axios';

const msalInstance = new PublicClientApplication(msalConfig);
await msalInstance.initialize()

// Global handler to add JWT to requests
axios.interceptors.request.use(async config => {
  try {
    const activeAccount = msalInstance.getActiveAccount() || null
    const response = await msalInstance.acquireTokenSilent({ scopes: [ "https://<mydomain>/appsec/api/Tools" ], account: activeAccount })
    // Update the header with the new token
    config.headers['Authorization'] = `Bearer ${response.accessToken}`
    // Resend the original config
    return config
  } catch (error) {
    if (error instanceof InteractionRequiredAuthError) {
      msalInstance.acquireTokenRedirect(loginRequest)
    } else {
      console.log(error)
    }
  }
})

msalInstance.addEventCallback((event) => {
  if (
    (event.eventType === EventType.LOGIN_SUCCESS ||
      event.eventType === EventType.ACQUIRE_TOKEN_SUCCESS ||
      event.eventType === EventType.SSO_SILENT_SUCCESS) &&
    event.payload.account
  ) {
    msalInstance.setActiveAccount(event.payload.account);
  }
});

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
  <React.StrictMode>
    <App instance={msalInstance} />
  </React.StrictMode>
);
```

### Reproduction Steps

For the call having the issue, the behavior is as follows:
- POST request is sent using Axios
- Interceptor is called and `acquireTokenSilent` is used to retrieve the current token/refresh it.
- Current page gets reloaded and POST request does not happen.
- If I repeat the request (submit form again), I now see a call to the `openid-configuration` endpoint in the browser tools (with NS_BINDING_ABORTED error in Firefox) (this is when the ClientAuthError is visible in the console) (URL used for this call is correct, and I can see the config if opened in another tab)

### Expected Behavior

An access token is obtained and included in the request as with the rest of requests.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by tnorling** [comment]
> NS_BINDING_ABORTED

This is likely the problem. It sounds like your system or browser is aborting the call, that's something we won't be able to help you debug.

You can, however, skip this network request from going out at all by following the directions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/performance.md#bypass-authority-metadata-resolution). Do note, however, that you will be responsible for keeping this config up to date if there are changes.
