### ISSUE TITLE
Teams app on chrome browser unable to login for custom application

### ISSUE THREAD

**Issue by kundan-kf** [AzureAD/microsoft-authentication-library-for-js#6912]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.1

### Public or Confidential Client?

Public

### Description

We have developed a Teams application using reactjs. We are using @microsoft/teams-js to authenticate user with our b2c policy in a Popup window.
`microsoftTeams.authentication.authenticate({url: window.location.origin + '/authstart?loginHint=emaild&isTA=true', successCB, failureCB})`

The authflow executes successfully and the popup gets closed, once it comes back to parent browser msal account evaluates to false.

`const { instance, accounts } = useMsal();`
`instance.setActiveAccount(account);`
`const thereAreAccounts = !!accounts.length || !!instance.getAllAccounts().length;`
**_` // evaluates to false`_**

The flow was working absolutely fine with the older version of chrome, it occurred after Oct 2023 chrome(version >116) update.

A separate issue is logged for 'microsoft-teams-library-js' https://github.com/OfficeDev/microsoft-teams-library-js/issues/1943, but the issue is not with TeamsJS library. The app is working fine in both Teams classic and New version.

### Error Message

TeamsAppAuthProvider.tsx:56 Uncaught TypeError: Cannot read properties of undefined (reading 'payload')
    at Object.successCallback (TeamsAppAuthProvider.tsx:56:34)
    at c (MicrosoftTeams.min.js:1:22970)
    at n.callHandler (MicrosoftTeams.min.js:1:9482)
    at MicrosoftTeams.min.js:1:3504
    at u (MicrosoftTeams.min.js:1:2364)
    at l.messageListener (MicrosoftTeams.min.js:1:4338)

Login flow :: See Below    
Teams App -> Popup(login with cred successful) ->Teams App(account is still null) -> Popup(User is already authenticated, returns without data) -> Teams App(Error Occurred)  

### MSAL Logs

Unable to capture since the popup closes immediately.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    "auth": {
        "clientId": "3aa9d188-0aaa-4fe6-a652-6ce8a0e80bbc",
        "authority": "https://vertexb2ckf.b2clogin.com/vertexb2ckf.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_IC2BQAUE",
        "knownAuthorities": [
            "vertexb2ckf.onmicrosoft.com",
            "vertexb2ckf.b2clogin.com"
        ],
        "cloudDiscoveryMetadata": "",
        "authorityMetadata": {
            "authorization_endpoint": "https://vertexb2ckf.b2clogin.com/vertexb2ckf.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_IC2BQAUE/oauth2/v2.0/authorize",
            "claims_supported": ["name","given_name","family_name","sub","idp","tid","client_email","organization_id","employee_number","employee_id","is_ic2_executive","idp_access_token","group_ids","group_names","iss","iat","exp","aud","acr","nonce","auth_time"],
            "end_session_endpoint": "https://vertexb2ckf.b2clogin.com/vertexb2ckf.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_IC2BQAUE/oauth2/v2.0/logout",
            "id_token_signing_alg_values_supported": [
                "RS256"
            ],
            "issuer": "https://vertexb2ckf.b2clogin.com/eeba91ff-5b83-4e85-9213-594b7ae398b0/v2.0/",
            "jwks_uri": "https://vertexb2ckf.b2clogin.com/vertexb2ckf.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_IC2BQAUE/discovery/v2.0/keys",
            "response_modes_supported": [
                "query",
                "fragment",
                "form_post"
            ],
            "response_types_supported": [
                "code",
                "code id_token",
                "code token",
                "code id_token token",
                "id_token",
                "id_token token",
                "token",
                "token id_token"
            ],
            "scopes_supported": [
                "openid"
            ],
            "subject_types_supported": [
                "pairwise"
            ],
            "token_endpoint": "https://vertexb2ckf.b2clogin.com/vertexb2ckf.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN_IC2BQAUE/oauth2/v2.0/token",
            "token_endpoint_auth_methods_supported": [
                "client_secret_post",
                "client_secret_basic"
            ]
        },
        "redirectUri": "https://kf-ic2b-qa-ee.azureedge.net/authend",
        "postLogoutRedirectUri": "https://kf-ic2b-qa-ee.azureedge.net",
        "navigateToLoginRequestUrl": false,
        "clientCapabilities": [],
        "protocolMode": "AAD",
        "azureCloudOptions": {
            "azureCloudInstance": 0,
            "tenant": ""
        },
        "skipAuthorityMetadataCache": false
    },
    "cache": {
        "cacheLocation": "localStorage",
        "temporaryCacheLocation": "sessionStorage",
        "storeAuthStateInCookie": false,
        "secureCookies": false,
        "cacheMigrationEnabled": true,
        "claimsBasedCachingEnabled": true
    },
    "system": {
        "tokenRenewalOffsetSeconds": 300,
        "preventCorsPreflight": false,
        "loggerOptions": {
            "logLevel": 2,
            "piiLoggingEnabled": false
        },
        "networkClient": {},
        "navigationClient": {},
        "loadFrameTimeout": 0,
        "windowHashTimeout": 60000,
        "iframeHashTimeout": 6000,
        "navigateFrameWait": 0,
        "redirectNavigationTimeout": 30000,
        "asyncPopups": false,
        "allowRedirectInIframe": false,
        "allowNativeBroker": false,
        "nativeBrokerHandshakeTimeout": 2000,
        "pollIntervalMilliseconds": 30,
        "cryptoOptions": {
            "useMsrCrypto": false
        }
    },
    "telemetry": {
        "application": {
            "appName": "",
            "appVersion": ""
        }
    }
}
```

### Relevant Code Snippets

```javascript
const authenticate = useCallback(
    (email?: string) => {
      microsoftTeams.authentication.authenticate({
        url: window.location.origin + `/authstart?loginHint=${email}&isTA=true`,
        successCallback: (event: any) => {
          // Delete payload as success callback was called
          localStorage.removeItem(storagePersistedKey.MSALPayload);
          const payload = event!.payload!;
          const authTokenData = onGetAuthTokenSuccess(
            payload,
            instance,
            true,
            false
          );
          if (authTokenData.is_ic2_executive) {
            setAuthStatus({ status: AuthenticationStatus.Failed });
            setErrorMessage(CustomLoginError.executiveUserNotAllowed);
            return;
          }
          setAuthStatus({
            status: AuthenticationStatus.Succeeded,
            token: payload.idToken,
          });
          setMGTExplicitSignIn(payload.idToken);
        },
        failureCallback: (reason?: string) => {
          // Handling payload in here until issue https://github.com/OfficeDev/microsoft-teams-library-js/issues/629 be fixed
          const payloadFromMsal: any = localStorage.getItem(
            storagePersistedKey.MSALPayload
          );
          if (payloadFromMsal) {
            const paylodFromMsalParsed = JSON.parse(payloadFromMsal);

            localStorage.setItem(
              storagePersistedKey.MSALIDToken,
              paylodFromMsalParsed.idToken
            );
            setAuthStatus({
              status: AuthenticationStatus.Succeeded,
              token: paylodFromMsalParsed.idToken,
            });
            setMGTExplicitSignIn(paylodFromMsalParsed.idToken);
            const account = paylodFromMsalParsed.account;
            instance.setActiveAccount(account);
          } else {
            setAuthStatus({ status: AuthenticationStatus.Failed });
            setErrorMessage(reason ?? ErrorMessage.commonError);
          }
        },
      });
    },
    [instance]
  );
```

### Reproduction Steps

1. Open any TeamsApp in chrome 116+ version with custom sso 
2. Login within popup window
3. Observe the console log

### Expected Behavior

The Parent browser should receive the msal accounts, or the popup window should share the same msalInstance with parent browser. Seems the popup window run in a custom domain where the application is deployed and the app runs in Teams domain.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Regression

still works with chrome <116 version

### Source

External (Customer)

**Comment by sameerag** [comment]
@kundan-kf Teams `chrome browser` called `Teams on web` still is managed by Teams Authentication team. I would like them to investigate this first before MSAL JS debugs it. Can we have them check that this is handled well in `Teams web`?
