### ISSUE TITLE
Problem with msal-node ElectronSystemBrowserTestApp authentication

### ISSUE THREAD

**Issue by MrCodeWeaver** [AzureAD/microsoft-authentication-library-for-js#7005]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.6.6

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

I have the [ElectronSystemBrowserTestApp ](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp)sample app setup and running, and it opens the browser and I can sign in with my Entra ID account, and it redirects back to localhost, but then throws a network error. This is happening in an environment that is doing deep packet inspection with a self signed certificate

### Error Message

ClientAuthError: network_error: Network request failedmpleted in 2ms
at createClientAuthError (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:37238:12) 
at NetworkManager.sendPostRequest (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:38047:104)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
at async AuthorizationCodeClient.executePostToTokenEndpoint (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:35940:26)
at async AuthorizationCodeClient.acquireToken (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:35474:26)
at async PublicClientApplication.acquireTokenByCode (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:42349:20)
at async PublicClientApplication.acquireTokenInteractive (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:43831:20) {
errorCode: 'network_error',
errorMessage: 'Network request failed',
subError: '',
correlationId: '1c865e56-7f7d-44c5-a8fd-69c39dad7318'
}

### MSAL Logs

[Thu, 04 Apr 2024 19:06:25 GMT] : [] : @azure/msal-node@2.6.6 : Info - getTokenCache called
[Thu, 04 Apr 2024 19:06:25 GMT] : [1c865e56-7f7d-44c5-a8fd-69c39dad7318] : @azure/msal-node@2.6.6 : Info - getAuthCodeUrl called
[Thu, 04 Apr 2024 19:06:25 GMT] : [1c865e56-7f7d-44c5-a8fd-69c39dad7318] : @azure/msal-node@2.6.6 : Info - Building oauth client configuration with the following authority: https://login.microsoftonline.com/organizations/oauth2/v2.0/token.
[Thu, 04 Apr 2024 19:06:32 GMT] : [] : @azure/msal-node@2.6.6 : Info - acquireTokenByCode called
[Thu, 04 Apr 2024 19:06:32 GMT] : [1c865e56-7f7d-44c5-a8fd-69c39dad7318] : @azure/msal-node@2.6.6 : Info - Building oauth client configuration with the following authority: https://login.microsoftonline.com/organizations/oauth2/v2.0/token.
ClientAuthError: network_error: Network request failedmpleted in 2ms
at createClientAuthError (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:37238:12) 
at NetworkManager.sendPostRequest (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:38047:104)
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
at async AuthorizationCodeClient.executePostToTokenEndpoint (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:35940:26)
at async AuthorizationCodeClient.acquireToken (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:35474:26)
at async PublicClientApplication.acquireTokenByCode (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:42349:20)
at async PublicClientApplication.acquireTokenInteractive (C:\git\microsoft-authentication-library-for-js\samples\msal-node-samples\ElectronSystemBrowserTestApp\.webpack\main\index.js:43831:20) {
errorCode: 'network_error',
errorMessage: 'Network request failed',
subError: '',
correlationId: '1c865e56-7f7d-44c5-a8fd-69c39dad7318'
}

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [X] Pending

### MSAL Configuration

```javascript
{
    "authOptions":
        {
            "clientId": "Enter_the_Application_Id_Here",
            "authority": "https://login.microsoftonline.com/organizations"
        },
    "resourceApi":
    {
        "endpoint": "Enter_the_Graph_Endpoint_Here",
        "scopes": ["User.Read", "Mail.Read"]
    },
    "customProtocol":
    {
        "name": "msal{Enter_the_Application_Id_Here}"
    },
    "cache": {
        "cacheLocation": "./data/cache.json"
    }
}
```

### Relevant Code Snippets

```javascript
const authResponse = await this.clientApplication.acquireTokenInteractive({
                ...tokenRequest,
                openBrowser,
                successTemplate: _successTemplate,
                errorTemplate: _errorTemplate,
            });
```

### Reproduction Steps

1. an environment that is doing deep packet inspection with a self signed certificate
1. Download the [ElectronSystemBrowserTestApp ](https://github.dev/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp/src/AuthProvider.ts)and configure the application id

1. Run the app and sign in > browser will open and then sign in with Entra ID account.
1. After sucessful auth in browser, will redirect back to local host and MSAL will give network error

### Expected Behavior

I would expect MSAL to use the reponse from local host

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by JapNolt** [comment]
@tnorling @bgavrilMS @Robbie-Microsoft

**Comment by tnorling** [comment]
Looks like it's failing on the POST to /token. Given you're proxying requests I would surmise that would be the cause but without more information, namely a network request it's hard to tell. Can you turn off the proxy? Does it succeed?

**Comment by MrCodeWeaver** [comment]
If I turn the proxy off, I can authenticate, and then turn the proxy back on and my app works fine. 
what is happeing is the browser will open and then sign in with Entra ID account. After sucessful auth in browser, will redirect back to local host and MSAL will give network error.
I can get fiddler logs or HAR file from the browser. Where should I upload them?
