### ISSUE TITLE
Endpoints cannot be resolved after enabling custom domains

### ISSUE THREAD

**Issue by slavanga** [AzureAD/microsoft-authentication-library-for-js#7066]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.13.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.15

### Public or Confidential Client?

Public

### Description

After enabling a custom domain according to the [docs](https://learn.microsoft.com/en-us/azure/active-directory-b2c/custom-domain?pivots=b2c-user-flow) and configuring it in the app, the error `endpoints_resolution_error` comes up and no redirect to the login page is triggered.

### Error Message

```
ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://auth.example.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/b2c_1_si/v2.0/.well-known/openid-configuration
    at ClientAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new ClientAuthError (ClientAuthError.ts:214:1)
    at ClientAuthError.createEndpointDiscoveryIncompleteError (ClientAuthError.ts:261:1)
    at Function.<anonymous> (AuthorityFactory.ts:46:1)
    at step (MathUtils.ts:23:1)
    at Object.throw (MathUtils.ts:23:1)
    at rejected (MathUtils.ts:23:1)
```

### MSAL Logs

Note: Domain and ID are redacted

```
[Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-browser@2.31.0 : Info - Emitting event: msal:initializeStart
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-browser@2.31.0 : Info - Emitting event: msal:initializeEnd
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-browser@2.31.0 : Info - initialize has already been called, exiting early.
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-browser@2.31.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : [33cc3ba6-175d-46b4-992e-b6a04f116f0f] : msal.js.browser@2.31.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-browser@2.31.0 : Info - Emitting event: msal:handleRedirectEnd
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:56 [Tue, 30 Apr 2024 07:44:18 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
authConfig.js:56 [Tue, 30 Apr 2024 07:44:22 GMT] : @azure/msal-browser@2.31.0 : Info - Emitting event: msal:loginStart
authConfig.js:56 [Tue, 30 Apr 2024 07:44:22 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
authConfig.js:56 [Tue, 30 Apr 2024 07:44:22 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
localhost/:1 Access to fetch at 'https://auth.example.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/b2c_1_si/v2.0/.well-known/openid-configuration' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
authConfig.js:56 [Tue, 30 Apr 2024 07:44:22 GMT] : @azure/msal-browser@2.31.0 : Info - Emitting event: msal:loginFailure
NavigationBar.jsx:24 ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://auth.example.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/b2c_1_si/v2.0/.well-known/openid-configuration
    at ClientAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new ClientAuthError (ClientAuthError.ts:214:1)
    at ClientAuthError.createEndpointDiscoveryIncompleteError (ClientAuthError.ts:261:1)
    at Function.<anonymous> (AuthorityFactory.ts:46:1)
    at step (MathUtils.ts:23:1)
    at Object.throw (MathUtils.ts:23:1)
    at rejected (MathUtils.ts:23:1)
authConfig.js:56 [Tue, 30 Apr 2024 07:44:22 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:loginFailure results in setting inProgress from login to none
authConfig.js:56 [Tue, 30 Apr 2024 07:44:22 GMT] : @azure/msal-react@1.4.10 : Info - MsalProvider - msal:loginFailure results in setting inProgress from login to none
```

### Network Trace (Preferrably Fiddler)

- [x] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    "auth": {
        "clientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "authority": "https://auth.example.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/b2c_1_si",
        "knownAuthorities": [
            "auth.example.com"
        ],
        "redirectUri": "/",
        "postLogoutRedirectUri": "/",
        "navigateToLoginRequestUrl": false
    },
    "cache": {
        "cacheLocation": "sessionStorage",
        "storeAuthStateInCookie": false
    },
    "system": {
        "loggerOptions": {
            "logLevel": 3
        }
    }
}
```

### Relevant Code Snippets

```javascript
Used the SPA example code:
https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/2-call-api-b2c/SPA
```

### Reproduction Steps

1. Setup custom domain according to [docs](https://learn.microsoft.com/en-us/azure/active-directory-b2c/custom-domain?pivots=b2c-user-flow)
2. Update msal config in [SPA example code](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/2-call-api-b2c/SPA)
3. Run example app and click on "Sign In" -> "Sign in using Redirect"

### Expected Behavior

Login redirect and auth flow should work the same as before enabling the custom domain.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
Either this endpoint: `https://auth.example.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/b2c_1_si/v2.0/.well-known/openid-configuration` needs to return CORS headers or you can skip the call entirely by manually passing the metadata this endpoint provides to MSAL via config: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/performance.md#bypass-authority-metadata-resolution

Closing as this is not something MSAL can address.

**Comment by vella-nicholas** [comment]
@tnorling can you elaborate on this statement please?

"Either this endpoint: https://auth.example.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/b2c_1_si/v2.0/.well-known/openid-configuration needs to return CORS headers"

**Comment by vella-nicholas** [comment]
@slavanga Any luck in fixing this issue? We have exactly the same problem
