### ISSUE TITLE
TypeError for cached AD FS account in V3

### ISSUE THREAD

**Issue by gabbsmo** [AzureAD/microsoft-authentication-library-for-js#7269]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.21.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Public or Confidential Client?

Public

### Description

After upgrading from V2 to V3 and added the required `initialize()` call, `handleRedirectPromise()` will throw a TypeError. This does not seem to happen with Azure AD accounts.

### Error Message

TypeError: Cannot set properties of undefined (setting 'tenantProfiles')
    at BrowserCacheManager.updateOutdatedCachedAccount (CacheManager.mjs:568:39)
    at BrowserCacheManager.getAccount (BrowserCacheManager.ts:399:21)
    at CacheManager.mjs:268:33
    at Array.forEach (<anonymous>)
    at BrowserCacheManager.getAccountsFilteredBy (CacheManager.mjs:263:24)
    at BrowserCacheManager.getAllAccounts (CacheManager.mjs:37:46)
    at getAllAccounts (AccountManager.ts:21:41)
    at StandardController.getAllAccounts (StandardController.ts:1354:16)
    at StandardController.handleRedirectPromiseInternal (StandardController.ts:413:39)
    at StandardController.handleRedirectPromise (StandardController.ts:386:33)

### MSAL Logs

[Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - BrowserCrypto: modern crypto interface available
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - BrowserCacheManager - createKeyMaps called.
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - BrowserCacheManager:createKeyMaps - account and token key maps already exist, skipping migration.
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - initialize called
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Info - Emitting event: msal:initializeStart
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - Claims-based caching is disabled. Clearing the previous cache with claims
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - Executing function clearTokensAndKeysWithClaims
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - BrowserCacheManager.getTokenKeys called
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - BrowserCacheManager.getAccessTokenCredential: cache hit
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - Returning result from clearTokensAndKeysWithClaims
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Info - Emitting event: msal:initializeEnd
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - handleRedirectPromise called
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - getAllAccounts called
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:05 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - BrowserCacheManager.getAccountKeys called
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:09 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - BrowserCacheManager.getAccount called
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:12 GMT] : [] : @azure/msal-common@14.14.1 : Verbose - updateOutdatedCachedAccount: Found a single-tenant (outdated) account entity in the cache, migrating to multi-tenant account entity
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:12 GMT] : [] : @azure/msal-browser@3.21.0 : Trace - BrowserCacheManager.getAccountKeys called
msalServiceProvider.js:63 [Fri, 23 Aug 2024 15:28:12 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise

### Network Trace (Preferrably Fiddler)

N/A since no network traffic with the identity provider at this point.

### MSAL Configuration

```javascript
{
    "auth": {
        "clientId": "SOME_GUID",
        "authority": "https://adfs.contoso/adfs",
        "redirectUri": "https://localhost:44300",
        "navigateToLoginRequestUrl": false,
        "knownAuthorities": [
            "https://adfs.contoso/adfs"
        ],
        "protocolMode": "OIDC"
    },
    "cache": {
        "cacheLocation": "localStorage"
    },
    "system": {
        "loggerOptions": {
            "logLevel": 4
        }
    }
}
```

### Relevant Code Snippets

```javascript
_msalInstance = new msal.PublicClientApplication(msalConfig);
_loginRedirectPromise = _msalInstance.initialize().then(function () {
    return _msalInstance.handleRedirectPromise();
});
```

### Reproduction Steps

1. Sign in to SPA running V2 using AD FS
2. Upgrade to V3 and do the required code changes for the upgrade
3. Refresh the SPA

### Expected Behavior

Attempt to upgrade previously cached AD FS accounts should not fail.

### Identity Provider

ADFS

### Browsers Affected (Select all that apply)

Edge

### Regression

@azure/msal-browser 2.38.3

### Source

External (Customer)

**Comment by fmontaltcv** [comment]
HI, same error here...
i am looking for a work around and i found this:

![image](https://github.com/user-attachments/assets/8616f689-4a22-4ce6-a8d6-1aec6abf8e33)

It seems that the problem is when is getting the accounts the startWith() function is keysensitive so that function doesn't found any account... then the array it is empty and then fails... looks like a bug from MSAL

The problem is in the function updateOutdatedCachedAccount in the file CacheManager.mjs
![image](https://github.com/user-attachments/assets/823182c3-bbab-4cfa-8fc0-2f995f16fe54)

**Comment by fmontaltcv** [comment]
More info:

![image](https://github.com/user-attachments/assets/483e21cd-b0aa-447a-a875-3ee6534be2da)

Looks like the msal.acount.keys that it is set in the localStorage it is in lowercase so... that is the problem... i am lloking if there is a way to set in the original stream

**Comment by RubSR** [comment]
Same problem here, 2 weeks without any answer? It's a huge problem.

**Comment by shurdev** [comment]
We have the same problem, when updating to v3, do we have a solution planned?

**Comment by fmontaltmer** [comment]
I have created this MR to fix the problem, please vote up to be set in the next version
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/7287

**Comment by DHerreto** [comment]
Same problem here. How's the MR going? Seems like a pretty simple fix?

**Comment by fmontaltmer** [comment]
Hello, i am still waiting for merge mi fix of this problem into dev... any news?
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/7287

**Comment by gabbsmo** [comment]
@tnorling sorry to bother you, but you seem to be the MSFT person on this project. Could you point us in the right direction to get this fixed? As it is now, rolling out V3 is blocked for users of AD FS and possibly other OIDC providers.

ping: @sameerag @hectormmg @jo-arroyo @peterzenz @Robbie-Microsoft @konstantin-msft @lalimasharda @shylasummers

**Comment by kyleholmes** [comment]
@gabbsmo did you wind up finding a workaround? downgrading back to v2?

**Comment by gabbsmo** [comment]
@kyleholmes no workaround sadly. Staying on V2 for now. Did you test with the latest V3?

**Comment by kyleholmes** [comment]
@gabbsmo latest v3 version still has the same issue:

_account key_: **K**yle.holmes@m...
_msal.account.keys_: **k**yle.holmes@m...

such a small change - very disappointing. v2 is incompatible with anything above angular 15, so not an option for us.

**Comment by gabbsmo** [comment]
@Robbie-Microsoft Is there anyone at Microsoft that can comment on this issue?

**Comment by kyleholmes** [comment]
For anyone who checks this thread in the future - after upgrading to v4 (msal-angular 4.0.4, msal-browser 4.2.0) and fiddling around for a while I was eventually able to get this working with angular 19.

My main roadblock was the following - for anyone who runs into this upgrading to v4:
![Image](https://github.com/user-attachments/assets/b5facb8c-55e0-414e-b0e7-afddd10c8bc0)
had to move away from HashLocationStrategy, otherwise was getting stuck in an endless rerouting loop. just removed useHash from the router config.

**Comment by gabbsmo** [comment]
@kyleholmes so V4 does not have the issue with casing of the local storage key you mentioned previously?

**Comment by kyleholmes** [comment]
@gabbsmo that's correct. they've actually removed that function entirely as part of this commit: https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/9487771574d6f1e2705cb47e6c715ec5147b06a9#diff-9386241630b242163033adcf355efb44fbb1f78fc9516e3553f226e4a5c0738b
