### ISSUE TITLE
cannot build MsalAngularjsDemoApp

### ISSUE THREAD

**Issue by pbalzer** [AzureAD/microsoft-authentication-library-for-js#807]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 1.0.2

</code></pre>

## Current behavior
After performing 'npm install' and 'npm start' as descrobed in the README.md, I get this error:
> msal-angularjsapp@0.1.0 start C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp
> webpack-dev-server

C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv-keywords\keywords\instanceof.js:52
    throw new Error('invalid "instanceof" keyword value ' + c);
    ^

Error: invalid "instanceof" keyword value Promise
    at getConstructor (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv-keywords\keywords\instanceof.js:52:11)
    at Ajv.compile (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv-keywords\keywords\instanceof.js:21:27)
    at Object.useCustomRule (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\compile\index.js:289:26)
    at Object.generate_custom [as code] (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\dotjs\custom.js:31:24)
    at Object.generate_validate [as validate] (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\dotjs\validate.js:228:37)
    at Object.generate_anyOf [as code] (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\dotjs\anyOf.js:34:27)
    at generate_validate (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\dotjs\validate.js:228:37)
    at localCompile (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\compile\index.js:99:22)
    at Ajv.compile (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\compile\index.js:67:13)
    at _compile (C:\Users\itr00626\source\repos\microsoft-authentication-library-for-js\lib\msal-angularjs\samples\MsalAngularjsDemoApp\node_modules\ajv\lib\ajv.js:328:29)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msal-angularjsapp@0.1.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msal-angularjsapp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\itr00626\AppData\Roaming\npm-cache\_logs\2019-07-03T06_45_44_297Z-debug.log

## Expected behavior

Start http server without errors.

**Comment by jasonnutter** [comment]
I was able to reproduce this, fix coming shortly. Thanks for the heads up!

**Comment by jasonnutter** [comment]
@pbalzer Checkout the branch in the PR above and let me know if that fixes the issue you were seeing (you'll want to delete `node_modules` and rerun `npm install`).

**Comment by pbalzer** [comment]
Ok it builds fine now. Thx!
