### ISSUE TITLE
MSAL for Angular Jest test not working

### ISSUE THREAD

**Issue by chr1soscl** [AzureAD/microsoft-authentication-library-for-js#858]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.2
My jest information:
"@nrwl/jest": "8.1.0",
"jest": "24.1.0",
"jest-preset-angular": "^7.1.1",
"jest-zone-patch": "0.0.10",
"ts-jest": "24.0.0",

</code></pre>

## Current behavior

I am running my ng test with jest and getting an error with the following message:

Jest encountered an unexpected token
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

Here's what you can do:
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/en/configuration.html

Details:

C:\myProject\node_modules\@azure\msal-angular\dist\broadcast.service.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Injectable } from '@angular/core';
                                                                                                ^

SyntaxError: Unexpected token {

**Comment by jasonnutter** [comment]
@chr1soscl Would you be able to put together a sample project that closely matches your setup that demonstrates the issue? It will help us more quickly debug the issue, thanks!

**Comment by chr1soscl** [comment]
@jasonnutter  
https://github.com/chr1soscl/NXMsalJest

**Comment by jasonnutter** [comment]
@chr1soscl Thanks!

**Comment by jasonnutter** [comment]
We have published a new version of msal-angular that should fix this issue:

`npm install @azure/msal-angular@0.1.4-beta.1`

Please test this version and let us know if there are any issues. We will promote to a stable release once we're confident this version doesn't introduce any regressions. Thanks!

**Comment by chr1soscl** [comment]
> We have published a new version of msal-angular that should fix this issue:
> 
> `npm install @azure/msal-angular@0.1.4-beta.1`
> 
> Please test this version and let us know if there are any issues. We will promote to a stable release once we're confident this version doesn't introduce any regressions. Thanks!

Hi Jason,
I took the changes, but now I am getting a different error:
 NullInjectorError: StaticInjectorError(DynamicTestModule)[MsalGuard -> InjectionToken MSAL_CONFIG]:
      StaticInjectorError(Platform: core)[MsalGuard -> InjectionToken MSAL_CONFIG]:
        NullInjectorError: No provider for InjectionToken MSAL_CONFIG!
this is happening with one of my components to which I am applying the MsalGuard and I have the MsalGuard declared in the providers in the app module, also in the spec file.

**Comment by chr1soscl** [comment]
> > We have published a new version of msal-angular that should fix this issue:
> > `npm install @azure/msal-angular@0.1.4-beta.1`
> > Please test this version and let us know if there are any issues. We will promote to a stable release once we're confident this version doesn't introduce any regressions. Thanks!
> 
> Hi Jason,
> I took the changes, but now I am getting a different error:
> NullInjectorError: StaticInjectorError(DynamicTestModule)[MsalGuard -> InjectionToken MSAL_CONFIG]:
> StaticInjectorError(Platform: core)[MsalGuard -> InjectionToken MSAL_CONFIG]:
> NullInjectorError: No provider for InjectionToken MSAL_CONFIG!
> this is happening with one of my components to which I am applying the MsalGuard and I have the MsalGuard declared in the providers in the app module, also in the spec file. I will try to replicate this issue in the project above. Also I used MsalModule.forRoot, like this:
> MsalModule.forRoot({
> clientID: 'myClientId',
> authority: 'myAuthority',
> popUp: true,
> consentScopes: ["user.read"]
> })
> so not quite sure why MSAL_CONFIG is required for injection.

Hi Jason, the issue above I fixed it by declaring the module in my spec file the same way I declared it at my app module. that removes the MSAL_CONFIG complain, but now I get a different error from msalService:

 TypeError: Cannot read property 'events' of undefined
at new MsalService (../../node_modules/@azure/msal-angular/src/msal.service.ts:66:21)
      at _createClass (../../../packages/core/src/view/ng_module.ts:178:14)
      at _createProviderInstance (../../../packages/core/src/view/ng_module.ts:144:20)
      at resolveNgModuleDep (../../../packages/core/src/view/ng_module.ts:106:13)
      at NgModuleRef_.get (../../../packages/core/src/view/refs.ts:507:12)
      at resolveDep (../../../packages/core/src/view/provider.ts:423:43)
      at createClass (../../../packages/core/src/view/provider.ts:283:24)
      at createDirectiveInstance (../../../packages/core/src/view/provider.ts:136:20)
      at createViewNodes (../../../packages/core/src/view/view.ts:303:28)
      at createRootView (../../../packages/core/src/view/view.ts:210:3)
      at callWithDebugContext (../../../packages/core/src/view/services.ts:630:23)
      at Object.debugCreateRootView [as createRootView] (../../../packages/core/src/view/services.ts:122:10)
      at ComponentFactory_.create (../../../packages/core/src/view/refs.ts:93:27)
      at initComponent (../../../../packages/core/testing/src/test_bed.ts:589:28)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:390:52)
      at Object.onInvoke (../../../packages/core/src/zone/ng_zone.ts:273:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:150:43)
      at NgZone.run (../../../packages/core/src/zone/ng_zone.ts:171:50)
      at TestBedViewEngine.createComponent (../../../../packages/core/testing/src/test_bed.ts:593:56)
      at Function.TestBedViewEngine.createComponent (../../../../packages/core/testing/src/test_bed.ts:232:36)

**Comment by jasonnutter** [comment]
I have not seen that error before, and I'm not sure what would cause it, unfortunately. Can you reproduce this issue in the test project?

**Comment by chr1soscl** [comment]
> I have not seen that error before, and I'm not sure what would cause it, unfortunately. Can you reproduce this issue in the test project you posted above? (`0.1.4-beta.1` appears to work in the sample project)

Hi James, 
I did try to recreate the issue in my sample project, but my sample project does not have a clientId and authority, so it is not exactly the same scenario, do you have any sample clientid and authority? that I could apply to the sample project.

**Comment by jasonnutter** [comment]
@chr1soscl Try the values here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/samples/VanillaJSTestApp/index.html#L23-L24
